// SPDX-FileCopyrightText: 2026 Plux contributors
// SPDX-License-Identifier: Apache-2.0

package registry

import (
	"bytes"
	"errors"
	"fmt"
	"io/fs"
	"maps"
	"slices"
	"strconv"
	"strings"
)

// lockComment heads the lock file.
const lockComment = "Permanent IDs of the widget and action registries (BND-011, ADR-0010). " +
	"Generated by schemagen: entries are appended, never changed or removed."

// Lock is the append-only record of every permanent ID ever assigned,
// including those of retired names (BND-011).
//
// Keys are paths: "widget/<Type>", "widget/<Type>/prop/<name>" (also
// "event", "slot"), "type/<Name>", "type/<Name>/field/<name>",
// "enum/<Name>", "enum/<Name>/value/<name>", "action/<name>" and
// "action/<name>/input/<name>". An ID is unique among the keys of its
// scope, the key without its last segment.
type Lock struct {
	// IDs maps each key to its ID.
	IDs map[string]uint32
}

// lockFile is the JSON shape of the lock.
type lockFile struct {
	Comment string            `json:"$comment"`
	IDs     map[string]uint32 `json:"ids"`
}

// ReadLock reads the lock at file; a missing file is an empty lock.
func ReadLock(file string) (Lock, error) {
	f, err := decodeFile[lockFile](file)
	if errors.Is(err, fs.ErrNotExist) {
		return Lock{IDs: map[string]uint32{}}, nil
	}
	if err != nil {
		return Lock{}, err
	}
	return ParseLock(f.IDs)
}

// ParseLock checks that ids form a valid lock: well-formed keys and IDs
// unique within their scope.
func ParseLock(ids map[string]uint32) (Lock, error) {
	l := Lock{IDs: maps.Clone(ids)}
	if l.IDs == nil {
		l.IDs = map[string]uint32{}
	}
	var p problems
	owners := map[string]string{}
	for _, k := range slices.Sorted(maps.Keys(l.IDs)) {
		scope, ok := lockScope(k)
		if !ok {
			p.add(LockFile, "malformed key %q", k)
			continue
		}
		id := l.IDs[k]
		if id == 0 {
			p.add(LockFile, "%s: IDs start at 1", k)
		}
		slot := scope + "#" + strconv.FormatUint(uint64(id), 10)
		if other, dup := owners[slot]; dup {
			p.add(LockFile, "%s and %s share ID %d", other, k, id)
		}
		owners[slot] = k
	}
	return l, p.err()
}

// lockScope returns the scope of a key and whether the key is well formed.
func lockScope(key string) (string, bool) {
	parts := strings.Split(key, "/")
	for _, s := range parts {
		if s == "" {
			return "", false
		}
	}
	member := map[string]string{"widget": "prop event slot", "type": "field", "enum": "value", "action": "input"}
	kinds, ok := member[parts[0]]
	switch {
	case !ok:
		return "", false
	case len(parts) == 2:
		return parts[0], true
	case len(parts) == 4 && slices.Contains(strings.Fields(kinds), parts[2]):
		return strings.Join(parts[:3], "/"), true
	default:
		return "", false
	}
}

// Entries returns the lock keys and IDs of every registry entry and member.
func (r *Registry) Entries() map[string]uint32 {
	ids := map[string]uint32{}
	for _, w := range r.Widgets {
		k := "widget/" + w.Type
		ids[k] = w.ID
		for _, m := range w.Props {
			ids[k+"/prop/"+m.Name] = m.ID
		}
		for _, m := range w.Events {
			ids[k+"/event/"+m.Name] = m.ID
		}
		for _, m := range w.Slots {
			ids[k+"/slot/"+m.Name] = m.ID
		}
	}
	for _, t := range r.Types {
		k := "type/" + t.Name
		ids[k] = t.ID
		for _, f := range t.Fields {
			ids[k+"/field/"+f.Name] = f.ID
		}
	}
	for _, e := range r.Enums {
		k := "enum/" + e.Name
		ids[k] = e.ID
		for _, v := range e.Values {
			ids[k+"/value/"+v.Name] = v.ID
		}
	}
	for _, a := range r.Actions {
		k := "action/" + a.Name
		ids[k] = a.ID
		for _, in := range a.Inputs {
			ids[k+"/input/"+in.Name] = in.ID
		}
	}
	return ids
}

// Merge returns the lock with entries added. It fails when a name already
// in the lock has a different ID, or when a new name takes an ID the lock
// has given to another name of the same scope, including a retired one.
func (l Lock) Merge(entries map[string]uint32) (Lock, error) {
	out := maps.Clone(l.IDs)
	if out == nil {
		out = map[string]uint32{}
	}
	owners := map[string]string{}
	for k, id := range l.IDs {
		scope, _ := lockScope(k)
		owners[scope+"#"+strconv.FormatUint(uint64(id), 10)] = k
	}
	var p problems
	for _, k := range slices.Sorted(maps.Keys(entries)) {
		id := entries[k]
		if old, ok := l.IDs[k]; ok {
			if old != id {
				p.add(k, "ID changed from %d to %d; permanent IDs are never reassigned (BND-011)", old, id)
			}
			continue
		}
		scope, _ := lockScope(k)
		if other, taken := owners[scope+"#"+strconv.FormatUint(uint64(id), 10)]; taken {
			p.add(k, "ID %d already belongs to %s; permanent IDs are never reused (BND-011)", id, other)
			continue
		}
		out[k] = id
	}
	if err := p.err(); err != nil {
		return Lock{}, err
	}
	return Lock{IDs: out}, nil
}

// CheckAppendOnly fails unless every entry of base is in l with the same
// ID, so no permanent ID is ever changed or dropped (BND-011).
func (l Lock) CheckAppendOnly(base Lock) error {
	var p problems
	for _, k := range slices.Sorted(maps.Keys(base.IDs)) {
		id, ok := l.IDs[k]
		switch {
		case !ok:
			p.add(k, "removed from the lock; entries are never removed (BND-011)")
		case id != base.IDs[k]:
			p.add(k, "ID changed from %d to %d in the lock (BND-011)", base.IDs[k], id)
		}
	}
	return p.err()
}

// Encode renders the lock as JSON with sorted keys, one entry per line.
func (l Lock) Encode() []byte {
	var b bytes.Buffer
	b.WriteString("{\n  \"$comment\": " + strconv.Quote(lockComment) + ",\n  \"ids\": {")
	for i, k := range slices.Sorted(maps.Keys(l.IDs)) {
		if i > 0 {
			b.WriteByte(',')
		}
		fmt.Fprintf(&b, "\n    %s: %d", strconv.Quote(k), l.IDs[k])
	}
	if len(l.IDs) > 0 {
		b.WriteString("\n  ")
	}
	b.WriteString("}\n}\n")
	return b.Bytes()
}
