// SPDX-FileCopyrightText: 2026 Plux contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: plux/v1/common.proto

package pluxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Severity of a diagnostic (ADR-0018).
type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_INFO        Severity = 1
	Severity_SEVERITY_WARNING     Severity = 2
	Severity_SEVERITY_ERROR       Severity = 3
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_INFO",
		2: "SEVERITY_WARNING",
		3: "SEVERITY_ERROR",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_INFO":        1,
		"SEVERITY_WARNING":     2,
		"SEVERITY_ERROR":       3,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_plux_v1_common_proto_enumTypes[0].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_plux_v1_common_proto_enumTypes[0]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_plux_v1_common_proto_rawDescGZIP(), []int{0}
}

// Page asks for one page of a list endpoint (SRV-004). No list endpoint
// returns an unbounded result: an unset page_size uses the server default
// and any value above the maximum is clamped to it.
type Page struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// page_size is the maximum number of items to return.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// page_token continues an earlier call. Tokens are opaque and
	// integrity-protected; they are bound to the filter and ordering they
	// were issued for and are rejected by any other query.
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// filter selects items with the documented filter syntax of the endpoint.
	Filter string `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	// order_by names fields to sort by, each optionally followed by " desc".
	OrderBy string `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	// read_mask limits each returned item to the named fields; an empty
	// mask returns whole items.
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,5,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_plux_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_plux_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Page) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *Page) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *Page) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *Page) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *Page) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

// PageResult carries the continuation of a list response.
type PageResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// next_page_token is empty on the last page.
	NextPageToken string `protobuf:"bytes,1,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// total_size is the number of items matching the filter, when the
	// endpoint can count them cheaply; zero otherwise.
	TotalSize     int32 `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResult) Reset() {
	*x = PageResult{}
	mi := &file_plux_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResult) ProtoMessage() {}

func (x *PageResult) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResult.ProtoReflect.Descriptor instead.
func (*PageResult) Descriptor() ([]byte, []int) {
	return file_plux_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *PageResult) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *PageResult) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

// Range is a half-open range of Unicode code points inside an expression.
type Range struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         int32                  `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End           int32                  `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Range) Reset() {
	*x = Range{}
	mi := &file_plux_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Range) ProtoMessage() {}

func (x *Range) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Range.ProtoReflect.Descriptor instead.
func (*Range) Descriptor() ([]byte, []int) {
	return file_plux_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *Range) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Range) GetEnd() int32 {
	if x != nil {
		return x.End
	}
	return 0
}

// Location identifies a value inside a project.
type Location struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// file is the document's path in the project layout, with forward slashes.
	File string `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	// path is a JSON Pointer (RFC 6901) into the document.
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// range narrows the location to characters inside a PXL expression.
	Range         *Range `protobuf:"bytes,3,opt,name=range,proto3" json:"range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_plux_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_plux_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *Location) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Location) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Location) GetRange() *Range {
	if x != nil {
		return x.Range
	}
	return nil
}

// PatchOp is one JSON Patch (RFC 6902) operation.
type PatchOp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// op is "add", "remove", "replace", "move", "copy" or "test".
	Op   string `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	From string `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	// value is the JSON value of "add", "replace" and "test", as bytes, so
	// that it keeps the canonical form the document model defines.
	Value         []byte `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchOp) Reset() {
	*x = PatchOp{}
	mi := &file_plux_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchOp) ProtoMessage() {}

func (x *PatchOp) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchOp.ProtoReflect.Descriptor instead.
func (*PatchOp) Descriptor() ([]byte, []int) {
	return file_plux_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *PatchOp) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *PatchOp) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PatchOp) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *PatchOp) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// Diagnostic is a finding about a document (ADR-0018, Appendix F).
type Diagnostic struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// code is the stable "PLX-NNNN" code.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// reason is the code's stable name.
	Reason        string      `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Severity      Severity    `protobuf:"varint,3,opt,name=severity,proto3,enum=plux.v1.Severity" json:"severity,omitempty"`
	Location      *Location   `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Message       string      `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Cause         string      `protobuf:"bytes,6,opt,name=cause,proto3" json:"cause,omitempty"`
	Fix           string      `protobuf:"bytes,7,opt,name=fix,proto3" json:"fix,omitempty"`
	Patch         []*PatchOp  `protobuf:"bytes,8,rep,name=patch,proto3" json:"patch,omitempty"`
	DocUrl        string      `protobuf:"bytes,9,opt,name=doc_url,json=docUrl,proto3" json:"doc_url,omitempty"`
	Related       []*Location `protobuf:"bytes,10,rep,name=related,proto3" json:"related,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Diagnostic) Reset() {
	*x = Diagnostic{}
	mi := &file_plux_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnostic) ProtoMessage() {}

func (x *Diagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnostic.ProtoReflect.Descriptor instead.
func (*Diagnostic) Descriptor() ([]byte, []int) {
	return file_plux_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *Diagnostic) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Diagnostic) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Diagnostic) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *Diagnostic) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Diagnostic) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Diagnostic) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *Diagnostic) GetFix() string {
	if x != nil {
		return x.Fix
	}
	return ""
}

func (x *Diagnostic) GetPatch() []*PatchOp {
	if x != nil {
		return x.Patch
	}
	return nil
}

func (x *Diagnostic) GetDocUrl() string {
	if x != nil {
		return x.DocUrl
	}
	return ""
}

func (x *Diagnostic) GetRelated() []*Location {
	if x != nil {
		return x.Related
	}
	return nil
}

// Actor is who performed an action.
type Actor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kind is "user", "token", "device", "system" or "ci".
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Id   string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// display is a human-readable name; never an email address.
	Display       string `protobuf:"bytes,3,opt,name=display,proto3" json:"display,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Actor) Reset() {
	*x = Actor{}
	mi := &file_plux_v1_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Actor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Actor) ProtoMessage() {}

func (x *Actor) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Actor.ProtoReflect.Descriptor instead.
func (*Actor) Descriptor() ([]byte, []int) {
	return file_plux_v1_common_proto_rawDescGZIP(), []int{6}
}

func (x *Actor) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Actor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Actor) GetDisplay() string {
	if x != nil {
		return x.Display
	}
	return ""
}

// LimitUsage is the current usage of one limit at one scope (LIM-005).
type LimitUsage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key is the limit's registry key, such as "bundle.pluginSize".
	Key  string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Unit string `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	// scope is "installation", "organization", "app" or "plugin".
	Scope string `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	Value int64  `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`
	// effective is the limit in force here after the hierarchy is resolved.
	Effective int64 `protobuf:"varint,5,opt,name=effective,proto3" json:"effective,omitempty"`
	// hard_max is the value no scope may exceed.
	HardMax int64 `protobuf:"varint,6,opt,name=hard_max,json=hardMax,proto3" json:"hard_max,omitempty"`
	// warning is true once usage reaches 80% of effective (LIM-003).
	Warning       bool `protobuf:"varint,7,opt,name=warning,proto3" json:"warning,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LimitUsage) Reset() {
	*x = LimitUsage{}
	mi := &file_plux_v1_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LimitUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LimitUsage) ProtoMessage() {}

func (x *LimitUsage) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LimitUsage.ProtoReflect.Descriptor instead.
func (*LimitUsage) Descriptor() ([]byte, []int) {
	return file_plux_v1_common_proto_rawDescGZIP(), []int{7}
}

func (x *LimitUsage) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LimitUsage) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *LimitUsage) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *LimitUsage) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *LimitUsage) GetEffective() int64 {
	if x != nil {
		return x.Effective
	}
	return 0
}

func (x *LimitUsage) GetHardMax() int64 {
	if x != nil {
		return x.HardMax
	}
	return 0
}

func (x *LimitUsage) GetWarning() bool {
	if x != nil {
		return x.Warning
	}
	return false
}

// Artifact is a stored, content-addressed object (SRV-023, REL-024).
type Artifact struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sha256 is the hash of the artifact's bytes, lower-case hex.
	Sha256 string `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Size   int64  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// urls are the locations to fetch it from, most preferred first.
	Urls []string `protobuf:"bytes,3,rep,name=urls,proto3" json:"urls,omitempty"`
	// media_type is the artifact's media type.
	MediaType     string `protobuf:"bytes,4,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_plux_v1_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_plux_v1_common_proto_rawDescGZIP(), []int{8}
}

func (x *Artifact) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *Artifact) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Artifact) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *Artifact) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

// AuditEntry is one record of the append-only audit log (SEC-140).
type AuditEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Time  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Actor *Actor                 `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
	// action is the registered action name, such as "plugin.lock.override".
	Action string `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	// target_kind and target_id identify what the action was performed on.
	TargetKind string `protobuf:"bytes,5,opt,name=target_kind,json=targetKind,proto3" json:"target_kind,omitempty"`
	TargetId   string `protobuf:"bytes,6,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	SourceIp   string `protobuf:"bytes,7,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	UserAgent  string `protobuf:"bytes,8,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	RequestId  string `protobuf:"bytes,9,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// before_hash and after_hash are SHA-256 of the affected content.
	BeforeHash    string `protobuf:"bytes,10,opt,name=before_hash,json=beforeHash,proto3" json:"before_hash,omitempty"`
	AfterHash     string `protobuf:"bytes,11,opt,name=after_hash,json=afterHash,proto3" json:"after_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEntry) Reset() {
	*x = AuditEntry{}
	mi := &file_plux_v1_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEntry) ProtoMessage() {}

func (x *AuditEntry) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEntry.ProtoReflect.Descriptor instead.
func (*AuditEntry) Descriptor() ([]byte, []int) {
	return file_plux_v1_common_proto_rawDescGZIP(), []int{9}
}

func (x *AuditEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditEntry) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *AuditEntry) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *AuditEntry) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditEntry) GetTargetKind() string {
	if x != nil {
		return x.TargetKind
	}
	return ""
}

func (x *AuditEntry) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *AuditEntry) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *AuditEntry) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *AuditEntry) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AuditEntry) GetBeforeHash() string {
	if x != nil {
		return x.BeforeHash
	}
	return ""
}

func (x *AuditEntry) GetAfterHash() string {
	if x != nil {
		return x.AfterHash
	}
	return ""
}

// TrashItem is a deleted app, plugin or page awaiting restore (GOV-031).
type TrashItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// kind is "app", "plugin" or "page".
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	DeletedBy     *Actor                 `protobuf:"bytes,4,opt,name=deleted_by,json=deletedBy,proto3" json:"deleted_by,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	PurgeAfter    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=purge_after,json=purgeAfter,proto3" json:"purge_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrashItem) Reset() {
	*x = TrashItem{}
	mi := &file_plux_v1_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrashItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrashItem) ProtoMessage() {}

func (x *TrashItem) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrashItem.ProtoReflect.Descriptor instead.
func (*TrashItem) Descriptor() ([]byte, []int) {
	return file_plux_v1_common_proto_rawDescGZIP(), []int{10}
}

func (x *TrashItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TrashItem) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *TrashItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrashItem) GetDeletedBy() *Actor {
	if x != nil {
		return x.DeletedBy
	}
	return nil
}

func (x *TrashItem) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *TrashItem) GetPurgeAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.PurgeAfter
	}
	return nil
}

var File_plux_v1_common_proto protoreflect.FileDescriptor

const file_plux_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x14plux/v1/common.proto\x12\aplux.v1\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xae\x01\n" +
	"\x04Page\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\x127\n" +
	"\tread_mask\x18\x05 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\"S\n" +
	"\n" +
	"PageResult\x12&\n" +
	"\x0fnext_page_token\x18\x01 \x01(\tR\rnextPageToken\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x05R\ttotalSize\"/\n" +
	"\x05Range\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x05R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x05R\x03end\"X\n" +
	"\bLocation\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12$\n" +
	"\x05range\x18\x03 \x01(\v2\x0e.plux.v1.RangeR\x05range\"W\n" +
	"\aPatchOp\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\tR\x02op\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04from\x18\x03 \x01(\tR\x04from\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\"\xc6\x02\n" +
	"\n" +
	"Diagnostic\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12-\n" +
	"\bseverity\x18\x03 \x01(\x0e2\x11.plux.v1.SeverityR\bseverity\x12-\n" +
	"\blocation\x18\x04 \x01(\v2\x11.plux.v1.LocationR\blocation\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x14\n" +
	"\x05cause\x18\x06 \x01(\tR\x05cause\x12\x10\n" +
	"\x03fix\x18\a \x01(\tR\x03fix\x12&\n" +
	"\x05patch\x18\b \x03(\v2\x10.plux.v1.PatchOpR\x05patch\x12\x17\n" +
	"\adoc_url\x18\t \x01(\tR\x06docUrl\x12+\n" +
	"\arelated\x18\n" +
	" \x03(\v2\x11.plux.v1.LocationR\arelated\"E\n" +
	"\x05Actor\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x18\n" +
	"\adisplay\x18\x03 \x01(\tR\adisplay\"\xb1\x01\n" +
	"\n" +
	"LimitUsage\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04unit\x18\x02 \x01(\tR\x04unit\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x03R\x05value\x12\x1c\n" +
	"\teffective\x18\x05 \x01(\x03R\teffective\x12\x19\n" +
	"\bhard_max\x18\x06 \x01(\x03R\ahardMax\x12\x18\n" +
	"\awarning\x18\a \x01(\bR\awarning\"i\n" +
	"\bArtifact\x12\x16\n" +
	"\x06sha256\x18\x01 \x01(\tR\x06sha256\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x12\n" +
	"\x04urls\x18\x03 \x03(\tR\x04urls\x12\x1d\n" +
	"\n" +
	"media_type\x18\x04 \x01(\tR\tmediaType\"\xe3\x02\n" +
	"\n" +
	"AuditEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x04time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12$\n" +
	"\x05actor\x18\x03 \x01(\v2\x0e.plux.v1.ActorR\x05actor\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x1f\n" +
	"\vtarget_kind\x18\x05 \x01(\tR\n" +
	"targetKind\x12\x1b\n" +
	"\ttarget_id\x18\x06 \x01(\tR\btargetId\x12\x1b\n" +
	"\tsource_ip\x18\a \x01(\tR\bsourceIp\x12\x1d\n" +
	"\n" +
	"user_agent\x18\b \x01(\tR\tuserAgent\x12\x1d\n" +
	"\n" +
	"request_id\x18\t \x01(\tR\trequestId\x12\x1f\n" +
	"\vbefore_hash\x18\n" +
	" \x01(\tR\n" +
	"beforeHash\x12\x1d\n" +
	"\n" +
	"after_hash\x18\v \x01(\tR\tafterHash\"\xea\x01\n" +
	"\tTrashItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12-\n" +
	"\n" +
	"deleted_by\x18\x04 \x01(\v2\x0e.plux.v1.ActorR\tdeletedBy\x129\n" +
	"\n" +
	"deleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12;\n" +
	"\vpurge_after\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"purgeAfter*a\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSEVERITY_INFO\x10\x01\x12\x14\n" +
	"\x10SEVERITY_WARNING\x10\x02\x12\x12\n" +
	"\x0eSEVERITY_ERROR\x10\x03B=Z;github.com/nightCode42/plux3/backend/internal/pluxv1;pluxv1b\x06proto3"

var (
	file_plux_v1_common_proto_rawDescOnce sync.Once
	file_plux_v1_common_proto_rawDescData []byte
)

func file_plux_v1_common_proto_rawDescGZIP() []byte {
	file_plux_v1_common_proto_rawDescOnce.Do(func() {
		file_plux_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plux_v1_common_proto_rawDesc), len(file_plux_v1_common_proto_rawDesc)))
	})
	return file_plux_v1_common_proto_rawDescData
}

var file_plux_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_plux_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_plux_v1_common_proto_goTypes = []any{
	(Severity)(0),                 // 0: plux.v1.Severity
	(*Page)(nil),                  // 1: plux.v1.Page
	(*PageResult)(nil),            // 2: plux.v1.PageResult
	(*Range)(nil),                 // 3: plux.v1.Range
	(*Location)(nil),              // 4: plux.v1.Location
	(*PatchOp)(nil),               // 5: plux.v1.PatchOp
	(*Diagnostic)(nil),            // 6: plux.v1.Diagnostic
	(*Actor)(nil),                 // 7: plux.v1.Actor
	(*LimitUsage)(nil),            // 8: plux.v1.LimitUsage
	(*Artifact)(nil),              // 9: plux.v1.Artifact
	(*AuditEntry)(nil),            // 10: plux.v1.AuditEntry
	(*TrashItem)(nil),             // 11: plux.v1.TrashItem
	(*fieldmaskpb.FieldMask)(nil), // 12: google.protobuf.FieldMask
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
}
var file_plux_v1_common_proto_depIdxs = []int32{
	12, // 0: plux.v1.Page.read_mask:type_name -> google.protobuf.FieldMask
	3,  // 1: plux.v1.Location.range:type_name -> plux.v1.Range
	0,  // 2: plux.v1.Diagnostic.severity:type_name -> plux.v1.Severity
	4,  // 3: plux.v1.Diagnostic.location:type_name -> plux.v1.Location
	5,  // 4: plux.v1.Diagnostic.patch:type_name -> plux.v1.PatchOp
	4,  // 5: plux.v1.Diagnostic.related:type_name -> plux.v1.Location
	13, // 6: plux.v1.AuditEntry.time:type_name -> google.protobuf.Timestamp
	7,  // 7: plux.v1.AuditEntry.actor:type_name -> plux.v1.Actor
	7,  // 8: plux.v1.TrashItem.deleted_by:type_name -> plux.v1.Actor
	13, // 9: plux.v1.TrashItem.deleted_at:type_name -> google.protobuf.Timestamp
	13, // 10: plux.v1.TrashItem.purge_after:type_name -> google.protobuf.Timestamp
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_plux_v1_common_proto_init() }
func file_plux_v1_common_proto_init() {
	if File_plux_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plux_v1_common_proto_rawDesc), len(file_plux_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plux_v1_common_proto_goTypes,
		DependencyIndexes: file_plux_v1_common_proto_depIdxs,
		EnumInfos:         file_plux_v1_common_proto_enumTypes,
		MessageInfos:      file_plux_v1_common_proto_msgTypes,
	}.Build()
	File_plux_v1_common_proto = out.File
	file_plux_v1_common_proto_goTypes = nil
	file_plux_v1_common_proto_depIdxs = nil
}
