// SPDX-FileCopyrightText: 2026 Plux contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: plux/v1/identity.proto

package pluxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// subject is the OIDC subject for federated users; empty for built-in ones.
	Subject     string `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	DisplayName string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// email is returned only to the user themselves and to administrators.
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	MfaEnrolled   bool                   `protobuf:"varint,5,opt,name=mfa_enrolled,json=mfaEnrolled,proto3" json:"mfa_enrolled,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastLoginAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_login_at,json=lastLoginAt,proto3" json:"last_login_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_plux_v1_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetMfaEnrolled() bool {
	if x != nil {
		return x.MfaEnrolled
	}
	return false
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetLastLoginAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLoginAt
	}
	return nil
}

// Factor is an enrolled second factor (SEC-100).
type Factor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// kind is "totp" or "webauthn".
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Confirmed     bool                   `protobuf:"varint,4,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Factor) Reset() {
	*x = Factor{}
	mi := &file_plux_v1_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Factor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Factor) ProtoMessage() {}

func (x *Factor) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Factor.ProtoReflect.Descriptor instead.
func (*Factor) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{1}
}

func (x *Factor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Factor) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Factor) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Factor) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

func (x *Factor) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Factor) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

// Session is a browser session. Its secret never appears in a response
// body: it is set as a __Host- prefixed, HttpOnly, Secure, SameSite=Strict
// cookie, and state-changing calls must echo csrf_token (SEC-101).
type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CsrfToken     string                 `protobuf:"bytes,3,opt,name=csrf_token,json=csrfToken,proto3" json:"csrf_token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_plux_v1_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{2}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Session) GetCsrfToken() string {
	if x != nil {
		return x.CsrfToken
	}
	return ""
}

func (x *Session) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// MfaChallenge is a login waiting for a second factor.
type MfaChallenge struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// kinds lists the factor kinds the user may answer with.
	Kinds []string `protobuf:"bytes,2,rep,name=kinds,proto3" json:"kinds,omitempty"`
	// webauthn_options is the WebAuthn request as JSON, when offered.
	WebauthnOptions []byte                 `protobuf:"bytes,3,opt,name=webauthn_options,json=webauthnOptions,proto3" json:"webauthn_options,omitempty"`
	ExpiresAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MfaChallenge) Reset() {
	*x = MfaChallenge{}
	mi := &file_plux_v1_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MfaChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MfaChallenge) ProtoMessage() {}

func (x *MfaChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MfaChallenge.ProtoReflect.Descriptor instead.
func (*MfaChallenge) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{3}
}

func (x *MfaChallenge) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MfaChallenge) GetKinds() []string {
	if x != nil {
		return x.Kinds
	}
	return nil
}

func (x *MfaChallenge) GetWebauthnOptions() []byte {
	if x != nil {
		return x.WebauthnOptions
	}
	return nil
}

func (x *MfaChallenge) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type GetCurrentUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentUserRequest) Reset() {
	*x = GetCurrentUserRequest{}
	mi := &file_plux_v1_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentUserRequest) ProtoMessage() {}

func (x *GetCurrentUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentUserRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentUserRequest) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{4}
}

type GetCurrentUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	User  *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// organizations the user belongs to, with their effective roles.
	Memberships []*Member `protobuf:"bytes,2,rep,name=memberships,proto3" json:"memberships,omitempty"`
	// permissions the caller holds in the current scope (SEC-102).
	Permissions   []string `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentUserResponse) Reset() {
	*x = GetCurrentUserResponse{}
	mi := &file_plux_v1_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentUserResponse) ProtoMessage() {}

func (x *GetCurrentUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentUserResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentUserResponse) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{5}
}

func (x *GetCurrentUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetCurrentUserResponse) GetMemberships() []*Member {
	if x != nil {
		return x.Memberships
	}
	return nil
}

func (x *GetCurrentUserResponse) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type StartPasswordLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartPasswordLoginRequest) Reset() {
	*x = StartPasswordLoginRequest{}
	mi := &file_plux_v1_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartPasswordLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPasswordLoginRequest) ProtoMessage() {}

func (x *StartPasswordLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPasswordLoginRequest.ProtoReflect.Descriptor instead.
func (*StartPasswordLoginRequest) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{6}
}

func (x *StartPasswordLoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *StartPasswordLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type StartPasswordLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Challenge     *MfaChallenge          `protobuf:"bytes,2,opt,name=challenge,proto3" json:"challenge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartPasswordLoginResponse) Reset() {
	*x = StartPasswordLoginResponse{}
	mi := &file_plux_v1_identity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartPasswordLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPasswordLoginResponse) ProtoMessage() {}

func (x *StartPasswordLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPasswordLoginResponse.ProtoReflect.Descriptor instead.
func (*StartPasswordLoginResponse) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{7}
}

func (x *StartPasswordLoginResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *StartPasswordLoginResponse) GetChallenge() *MfaChallenge {
	if x != nil {
		return x.Challenge
	}
	return nil
}

type StartOidcLoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// redirect_path is a path inside Studio to return to; absolute URLs are
	// refused so the flow cannot be redirected off-site.
	RedirectPath  string `protobuf:"bytes,1,opt,name=redirect_path,json=redirectPath,proto3" json:"redirect_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartOidcLoginRequest) Reset() {
	*x = StartOidcLoginRequest{}
	mi := &file_plux_v1_identity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartOidcLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOidcLoginRequest) ProtoMessage() {}

func (x *StartOidcLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOidcLoginRequest.ProtoReflect.Descriptor instead.
func (*StartOidcLoginRequest) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{8}
}

func (x *StartOidcLoginRequest) GetRedirectPath() string {
	if x != nil {
		return x.RedirectPath
	}
	return ""
}

type StartOidcLoginResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AuthorizationUrl string                 `protobuf:"bytes,1,opt,name=authorization_url,json=authorizationUrl,proto3" json:"authorization_url,omitempty"`
	State            string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StartOidcLoginResponse) Reset() {
	*x = StartOidcLoginResponse{}
	mi := &file_plux_v1_identity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartOidcLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOidcLoginResponse) ProtoMessage() {}

func (x *StartOidcLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOidcLoginResponse.ProtoReflect.Descriptor instead.
func (*StartOidcLoginResponse) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{9}
}

func (x *StartOidcLoginResponse) GetAuthorizationUrl() string {
	if x != nil {
		return x.AuthorizationUrl
	}
	return ""
}

func (x *StartOidcLoginResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type CompleteOidcLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteOidcLoginRequest) Reset() {
	*x = CompleteOidcLoginRequest{}
	mi := &file_plux_v1_identity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteOidcLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteOidcLoginRequest) ProtoMessage() {}

func (x *CompleteOidcLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteOidcLoginRequest.ProtoReflect.Descriptor instead.
func (*CompleteOidcLoginRequest) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{10}
}

func (x *CompleteOidcLoginRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CompleteOidcLoginRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type CompleteOidcLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Challenge     *MfaChallenge          `protobuf:"bytes,2,opt,name=challenge,proto3" json:"challenge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteOidcLoginResponse) Reset() {
	*x = CompleteOidcLoginResponse{}
	mi := &file_plux_v1_identity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteOidcLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteOidcLoginResponse) ProtoMessage() {}

func (x *CompleteOidcLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteOidcLoginResponse.ProtoReflect.Descriptor instead.
func (*CompleteOidcLoginResponse) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{11}
}

func (x *CompleteOidcLoginResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *CompleteOidcLoginResponse) GetChallenge() *MfaChallenge {
	if x != nil {
		return x.Challenge
	}
	return nil
}

type CompleteMfaRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	// code answers a TOTP challenge.
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// assertion answers a WebAuthn challenge, as JSON.
	Assertion     []byte `protobuf:"bytes,3,opt,name=assertion,proto3" json:"assertion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteMfaRequest) Reset() {
	*x = CompleteMfaRequest{}
	mi := &file_plux_v1_identity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteMfaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteMfaRequest) ProtoMessage() {}

func (x *CompleteMfaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteMfaRequest.ProtoReflect.Descriptor instead.
func (*CompleteMfaRequest) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{12}
}

func (x *CompleteMfaRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *CompleteMfaRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CompleteMfaRequest) GetAssertion() []byte {
	if x != nil {
		return x.Assertion
	}
	return nil
}

type CompleteMfaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteMfaResponse) Reset() {
	*x = CompleteMfaResponse{}
	mi := &file_plux_v1_identity_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteMfaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteMfaResponse) ProtoMessage() {}

func (x *CompleteMfaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteMfaResponse.ProtoReflect.Descriptor instead.
func (*CompleteMfaResponse) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{13}
}

func (x *CompleteMfaResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_plux_v1_identity_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{14}
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_plux_v1_identity_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{15}
}

type EnrollTotpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollTotpRequest) Reset() {
	*x = EnrollTotpRequest{}
	mi := &file_plux_v1_identity_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollTotpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollTotpRequest) ProtoMessage() {}

func (x *EnrollTotpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollTotpRequest.ProtoReflect.Descriptor instead.
func (*EnrollTotpRequest) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{16}
}

func (x *EnrollTotpRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type EnrollTotpResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Factor *Factor                `protobuf:"bytes,1,opt,name=factor,proto3" json:"factor,omitempty"`
	// secret is the base32 TOTP secret; it is returned exactly once.
	Secret        string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	OtpauthUrl    string `protobuf:"bytes,3,opt,name=otpauth_url,json=otpauthUrl,proto3" json:"otpauth_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollTotpResponse) Reset() {
	*x = EnrollTotpResponse{}
	mi := &file_plux_v1_identity_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollTotpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollTotpResponse) ProtoMessage() {}

func (x *EnrollTotpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollTotpResponse.ProtoReflect.Descriptor instead.
func (*EnrollTotpResponse) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{17}
}

func (x *EnrollTotpResponse) GetFactor() *Factor {
	if x != nil {
		return x.Factor
	}
	return nil
}

func (x *EnrollTotpResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *EnrollTotpResponse) GetOtpauthUrl() string {
	if x != nil {
		return x.OtpauthUrl
	}
	return ""
}

type EnrollWebauthnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollWebauthnRequest) Reset() {
	*x = EnrollWebauthnRequest{}
	mi := &file_plux_v1_identity_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollWebauthnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollWebauthnRequest) ProtoMessage() {}

func (x *EnrollWebauthnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollWebauthnRequest.ProtoReflect.Descriptor instead.
func (*EnrollWebauthnRequest) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{18}
}

func (x *EnrollWebauthnRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type EnrollWebauthnResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Factor *Factor                `protobuf:"bytes,1,opt,name=factor,proto3" json:"factor,omitempty"`
	// creation_options is the WebAuthn credential creation request as JSON.
	CreationOptions []byte `protobuf:"bytes,2,opt,name=creation_options,json=creationOptions,proto3" json:"creation_options,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EnrollWebauthnResponse) Reset() {
	*x = EnrollWebauthnResponse{}
	mi := &file_plux_v1_identity_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollWebauthnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollWebauthnResponse) ProtoMessage() {}

func (x *EnrollWebauthnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollWebauthnResponse.ProtoReflect.Descriptor instead.
func (*EnrollWebauthnResponse) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{19}
}

func (x *EnrollWebauthnResponse) GetFactor() *Factor {
	if x != nil {
		return x.Factor
	}
	return nil
}

func (x *EnrollWebauthnResponse) GetCreationOptions() []byte {
	if x != nil {
		return x.CreationOptions
	}
	return nil
}

type ConfirmFactorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FactorId      string                 `protobuf:"bytes,1,opt,name=factor_id,json=factorId,proto3" json:"factor_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Attestation   []byte                 `protobuf:"bytes,3,opt,name=attestation,proto3" json:"attestation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmFactorRequest) Reset() {
	*x = ConfirmFactorRequest{}
	mi := &file_plux_v1_identity_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmFactorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmFactorRequest) ProtoMessage() {}

func (x *ConfirmFactorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmFactorRequest.ProtoReflect.Descriptor instead.
func (*ConfirmFactorRequest) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{20}
}

func (x *ConfirmFactorRequest) GetFactorId() string {
	if x != nil {
		return x.FactorId
	}
	return ""
}

func (x *ConfirmFactorRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ConfirmFactorRequest) GetAttestation() []byte {
	if x != nil {
		return x.Attestation
	}
	return nil
}

type ConfirmFactorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Factor        *Factor                `protobuf:"bytes,1,opt,name=factor,proto3" json:"factor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmFactorResponse) Reset() {
	*x = ConfirmFactorResponse{}
	mi := &file_plux_v1_identity_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmFactorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmFactorResponse) ProtoMessage() {}

func (x *ConfirmFactorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmFactorResponse.ProtoReflect.Descriptor instead.
func (*ConfirmFactorResponse) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{21}
}

func (x *ConfirmFactorResponse) GetFactor() *Factor {
	if x != nil {
		return x.Factor
	}
	return nil
}

type ListFactorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFactorsRequest) Reset() {
	*x = ListFactorsRequest{}
	mi := &file_plux_v1_identity_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFactorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFactorsRequest) ProtoMessage() {}

func (x *ListFactorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFactorsRequest.ProtoReflect.Descriptor instead.
func (*ListFactorsRequest) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{22}
}

type ListFactorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Factors       []*Factor              `protobuf:"bytes,1,rep,name=factors,proto3" json:"factors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFactorsResponse) Reset() {
	*x = ListFactorsResponse{}
	mi := &file_plux_v1_identity_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFactorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFactorsResponse) ProtoMessage() {}

func (x *ListFactorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFactorsResponse.ProtoReflect.Descriptor instead.
func (*ListFactorsResponse) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{23}
}

func (x *ListFactorsResponse) GetFactors() []*Factor {
	if x != nil {
		return x.Factors
	}
	return nil
}

type DeleteFactorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FactorId      string                 `protobuf:"bytes,1,opt,name=factor_id,json=factorId,proto3" json:"factor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFactorRequest) Reset() {
	*x = DeleteFactorRequest{}
	mi := &file_plux_v1_identity_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFactorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFactorRequest) ProtoMessage() {}

func (x *DeleteFactorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFactorRequest.ProtoReflect.Descriptor instead.
func (*DeleteFactorRequest) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteFactorRequest) GetFactorId() string {
	if x != nil {
		return x.FactorId
	}
	return ""
}

type DeleteFactorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFactorResponse) Reset() {
	*x = DeleteFactorResponse{}
	mi := &file_plux_v1_identity_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFactorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFactorResponse) ProtoMessage() {}

func (x *DeleteFactorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFactorResponse.ProtoReflect.Descriptor instead.
func (*DeleteFactorResponse) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{25}
}

type StartDeviceAuthorizationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client is the calling program, such as "plux-cli".
	Client        string   `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	Scopes        []string `protobuf:"bytes,2,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartDeviceAuthorizationRequest) Reset() {
	*x = StartDeviceAuthorizationRequest{}
	mi := &file_plux_v1_identity_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartDeviceAuthorizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDeviceAuthorizationRequest) ProtoMessage() {}

func (x *StartDeviceAuthorizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDeviceAuthorizationRequest.ProtoReflect.Descriptor instead.
func (*StartDeviceAuthorizationRequest) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{26}
}

func (x *StartDeviceAuthorizationRequest) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *StartDeviceAuthorizationRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type StartDeviceAuthorizationResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	DeviceCode              string                 `protobuf:"bytes,1,opt,name=device_code,json=deviceCode,proto3" json:"device_code,omitempty"`
	UserCode                string                 `protobuf:"bytes,2,opt,name=user_code,json=userCode,proto3" json:"user_code,omitempty"`
	VerificationUri         string                 `protobuf:"bytes,3,opt,name=verification_uri,json=verificationUri,proto3" json:"verification_uri,omitempty"`
	VerificationUriComplete string                 `protobuf:"bytes,4,opt,name=verification_uri_complete,json=verificationUriComplete,proto3" json:"verification_uri_complete,omitempty"`
	IntervalSeconds         int32                  `protobuf:"varint,5,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	ExpiresAt               *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *StartDeviceAuthorizationResponse) Reset() {
	*x = StartDeviceAuthorizationResponse{}
	mi := &file_plux_v1_identity_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartDeviceAuthorizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDeviceAuthorizationResponse) ProtoMessage() {}

func (x *StartDeviceAuthorizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDeviceAuthorizationResponse.ProtoReflect.Descriptor instead.
func (*StartDeviceAuthorizationResponse) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{27}
}

func (x *StartDeviceAuthorizationResponse) GetDeviceCode() string {
	if x != nil {
		return x.DeviceCode
	}
	return ""
}

func (x *StartDeviceAuthorizationResponse) GetUserCode() string {
	if x != nil {
		return x.UserCode
	}
	return ""
}

func (x *StartDeviceAuthorizationResponse) GetVerificationUri() string {
	if x != nil {
		return x.VerificationUri
	}
	return ""
}

func (x *StartDeviceAuthorizationResponse) GetVerificationUriComplete() string {
	if x != nil {
		return x.VerificationUriComplete
	}
	return ""
}

func (x *StartDeviceAuthorizationResponse) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *StartDeviceAuthorizationResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type PollDeviceAuthorizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceCode    string                 `protobuf:"bytes,1,opt,name=device_code,json=deviceCode,proto3" json:"device_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollDeviceAuthorizationRequest) Reset() {
	*x = PollDeviceAuthorizationRequest{}
	mi := &file_plux_v1_identity_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollDeviceAuthorizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollDeviceAuthorizationRequest) ProtoMessage() {}

func (x *PollDeviceAuthorizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollDeviceAuthorizationRequest.ProtoReflect.Descriptor instead.
func (*PollDeviceAuthorizationRequest) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{28}
}

func (x *PollDeviceAuthorizationRequest) GetDeviceCode() string {
	if x != nil {
		return x.DeviceCode
	}
	return ""
}

type PollDeviceAuthorizationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status is "pending", "slow_down", "approved" or "denied".
	Status string       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Token  *AccessToken `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	// secret is the token's value; returned exactly once, on approval.
	Secret        string `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollDeviceAuthorizationResponse) Reset() {
	*x = PollDeviceAuthorizationResponse{}
	mi := &file_plux_v1_identity_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollDeviceAuthorizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollDeviceAuthorizationResponse) ProtoMessage() {}

func (x *PollDeviceAuthorizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollDeviceAuthorizationResponse.ProtoReflect.Descriptor instead.
func (*PollDeviceAuthorizationResponse) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{29}
}

func (x *PollDeviceAuthorizationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PollDeviceAuthorizationResponse) GetToken() *AccessToken {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *PollDeviceAuthorizationResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type ApproveDeviceAuthorizationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserCode       string                 `protobuf:"bytes,1,opt,name=user_code,json=userCode,proto3" json:"user_code,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApproveDeviceAuthorizationRequest) Reset() {
	*x = ApproveDeviceAuthorizationRequest{}
	mi := &file_plux_v1_identity_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveDeviceAuthorizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveDeviceAuthorizationRequest) ProtoMessage() {}

func (x *ApproveDeviceAuthorizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveDeviceAuthorizationRequest.ProtoReflect.Descriptor instead.
func (*ApproveDeviceAuthorizationRequest) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{30}
}

func (x *ApproveDeviceAuthorizationRequest) GetUserCode() string {
	if x != nil {
		return x.UserCode
	}
	return ""
}

func (x *ApproveDeviceAuthorizationRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type ApproveDeviceAuthorizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveDeviceAuthorizationResponse) Reset() {
	*x = ApproveDeviceAuthorizationResponse{}
	mi := &file_plux_v1_identity_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveDeviceAuthorizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveDeviceAuthorizationResponse) ProtoMessage() {}

func (x *ApproveDeviceAuthorizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveDeviceAuthorizationResponse.ProtoReflect.Descriptor instead.
func (*ApproveDeviceAuthorizationResponse) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{31}
}

// AccessToken is a scoped, expiring, revocable credential (SRV-064).
type AccessToken struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UserId         string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,4,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Scopes         []string               `protobuf:"bytes,5,rep,name=scopes,proto3" json:"scopes,omitempty"`
	// prefix is the token's visible prefix, for identifying it in a list.
	Prefix        string                 `protobuf:"bytes,6,opt,name=prefix,proto3" json:"prefix,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	RevokedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessToken) Reset() {
	*x = AccessToken{}
	mi := &file_plux_v1_identity_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessToken) ProtoMessage() {}

func (x *AccessToken) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessToken.ProtoReflect.Descriptor instead.
func (*AccessToken) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{32}
}

func (x *AccessToken) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccessToken) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccessToken) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AccessToken) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *AccessToken) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *AccessToken) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *AccessToken) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AccessToken) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *AccessToken) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

func (x *AccessToken) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

type CreateAccessTokenRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Scopes         []string               `protobuf:"bytes,3,rep,name=scopes,proto3" json:"scopes,omitempty"`
	// ttl_seconds must be positive; tokens never last for ever.
	TtlSeconds    int64 `protobuf:"varint,4,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccessTokenRequest) Reset() {
	*x = CreateAccessTokenRequest{}
	mi := &file_plux_v1_identity_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccessTokenRequest) ProtoMessage() {}

func (x *CreateAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{33}
}

func (x *CreateAccessTokenRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAccessTokenRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateAccessTokenRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *CreateAccessTokenRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type CreateAccessTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Token *AccessToken           `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// secret is returned exactly once and never stored in clear.
	Secret        string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccessTokenResponse) Reset() {
	*x = CreateAccessTokenResponse{}
	mi := &file_plux_v1_identity_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccessTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccessTokenResponse) ProtoMessage() {}

func (x *CreateAccessTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccessTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateAccessTokenResponse) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{34}
}

func (x *CreateAccessTokenResponse) GetToken() *AccessToken {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *CreateAccessTokenResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type ListAccessTokensRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Page           *Page                  `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListAccessTokensRequest) Reset() {
	*x = ListAccessTokensRequest{}
	mi := &file_plux_v1_identity_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccessTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessTokensRequest) ProtoMessage() {}

func (x *ListAccessTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessTokensRequest.ProtoReflect.Descriptor instead.
func (*ListAccessTokensRequest) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{35}
}

func (x *ListAccessTokensRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListAccessTokensRequest) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListAccessTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*AccessToken         `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	Page          *PageResult            `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccessTokensResponse) Reset() {
	*x = ListAccessTokensResponse{}
	mi := &file_plux_v1_identity_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccessTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessTokensResponse) ProtoMessage() {}

func (x *ListAccessTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessTokensResponse.ProtoReflect.Descriptor instead.
func (*ListAccessTokensResponse) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{36}
}

func (x *ListAccessTokensResponse) GetTokens() []*AccessToken {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *ListAccessTokensResponse) GetPage() *PageResult {
	if x != nil {
		return x.Page
	}
	return nil
}

type RevokeAccessTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAccessTokenRequest) Reset() {
	*x = RevokeAccessTokenRequest{}
	mi := &file_plux_v1_identity_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAccessTokenRequest) ProtoMessage() {}

func (x *RevokeAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{37}
}

func (x *RevokeAccessTokenRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RevokeAccessTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAccessTokenResponse) Reset() {
	*x = RevokeAccessTokenResponse{}
	mi := &file_plux_v1_identity_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAccessTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAccessTokenResponse) ProtoMessage() {}

func (x *RevokeAccessTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAccessTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeAccessTokenResponse) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{38}
}

type ExchangeWorkloadIdentityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// oidc_token is the CI provider's identity token.
	OidcToken      string   `protobuf:"bytes,1,opt,name=oidc_token,json=oidcToken,proto3" json:"oidc_token,omitempty"`
	OrganizationId string   `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Scopes         []string `protobuf:"bytes,3,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExchangeWorkloadIdentityRequest) Reset() {
	*x = ExchangeWorkloadIdentityRequest{}
	mi := &file_plux_v1_identity_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeWorkloadIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeWorkloadIdentityRequest) ProtoMessage() {}

func (x *ExchangeWorkloadIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeWorkloadIdentityRequest.ProtoReflect.Descriptor instead.
func (*ExchangeWorkloadIdentityRequest) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{39}
}

func (x *ExchangeWorkloadIdentityRequest) GetOidcToken() string {
	if x != nil {
		return x.OidcToken
	}
	return ""
}

func (x *ExchangeWorkloadIdentityRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ExchangeWorkloadIdentityRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type ExchangeWorkloadIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Scopes        []string               `protobuf:"bytes,3,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeWorkloadIdentityResponse) Reset() {
	*x = ExchangeWorkloadIdentityResponse{}
	mi := &file_plux_v1_identity_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeWorkloadIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeWorkloadIdentityResponse) ProtoMessage() {}

func (x *ExchangeWorkloadIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeWorkloadIdentityResponse.ProtoReflect.Descriptor instead.
func (*ExchangeWorkloadIdentityResponse) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{40}
}

func (x *ExchangeWorkloadIdentityResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *ExchangeWorkloadIdentityResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ExchangeWorkloadIdentityResponse) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type ListAuditEntriesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Page           *Page                  `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListAuditEntriesRequest) Reset() {
	*x = ListAuditEntriesRequest{}
	mi := &file_plux_v1_identity_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditEntriesRequest) ProtoMessage() {}

func (x *ListAuditEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditEntriesRequest.ProtoReflect.Descriptor instead.
func (*ListAuditEntriesRequest) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{41}
}

func (x *ListAuditEntriesRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListAuditEntriesRequest) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListAuditEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*AuditEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Page          *PageResult            `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditEntriesResponse) Reset() {
	*x = ListAuditEntriesResponse{}
	mi := &file_plux_v1_identity_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditEntriesResponse) ProtoMessage() {}

func (x *ListAuditEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plux_v1_identity_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditEntriesResponse.ProtoReflect.Descriptor instead.
func (*ListAuditEntriesResponse) Descriptor() ([]byte, []int) {
	return file_plux_v1_identity_proto_rawDescGZIP(), []int{42}
}

func (x *ListAuditEntriesResponse) GetEntries() []*AuditEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListAuditEntriesResponse) GetPage() *PageResult {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_plux_v1_identity_proto protoreflect.FileDescriptor

const file_plux_v1_identity_proto_rawDesc = "" +
	"\n" +
	"\x16plux/v1/identity.proto\x12\aplux.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x14plux/v1/common.proto\x1a\x11plux/v1/org.proto\"\x87\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12!\n" +
	"\fmfa_enrolled\x18\x05 \x01(\bR\vmfaEnrolled\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12>\n" +
	"\rlast_login_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vlastLoginAt\"\xd9\x01\n" +
	"\x06Factor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12\x1c\n" +
	"\tconfirmed\x18\x04 \x01(\bR\tconfirmed\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\flast_used_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\"\x8c\x01\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"csrf_token\x18\x03 \x01(\tR\tcsrfToken\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x9a\x01\n" +
	"\fMfaChallenge\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05kinds\x18\x02 \x03(\tR\x05kinds\x12)\n" +
	"\x10webauthn_options\x18\x03 \x01(\fR\x0fwebauthnOptions\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x17\n" +
	"\x15GetCurrentUserRequest\"\x90\x01\n" +
	"\x16GetCurrentUserResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.plux.v1.UserR\x04user\x121\n" +
	"\vmemberships\x18\x02 \x03(\v2\x0f.plux.v1.MemberR\vmemberships\x12 \n" +
	"\vpermissions\x18\x03 \x03(\tR\vpermissions\"M\n" +
	"\x19StartPasswordLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"}\n" +
	"\x1aStartPasswordLoginResponse\x12*\n" +
	"\asession\x18\x01 \x01(\v2\x10.plux.v1.SessionR\asession\x123\n" +
	"\tchallenge\x18\x02 \x01(\v2\x15.plux.v1.MfaChallengeR\tchallenge\"<\n" +
	"\x15StartOidcLoginRequest\x12#\n" +
	"\rredirect_path\x18\x01 \x01(\tR\fredirectPath\"[\n" +
	"\x16StartOidcLoginResponse\x12+\n" +
	"\x11authorization_url\x18\x01 \x01(\tR\x10authorizationUrl\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"D\n" +
	"\x18CompleteOidcLoginRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"|\n" +
	"\x19CompleteOidcLoginResponse\x12*\n" +
	"\asession\x18\x01 \x01(\v2\x10.plux.v1.SessionR\asession\x123\n" +
	"\tchallenge\x18\x02 \x01(\v2\x15.plux.v1.MfaChallengeR\tchallenge\"i\n" +
	"\x12CompleteMfaRequest\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1c\n" +
	"\tassertion\x18\x03 \x01(\fR\tassertion\"A\n" +
	"\x13CompleteMfaResponse\x12*\n" +
	"\asession\x18\x01 \x01(\v2\x10.plux.v1.SessionR\asession\"\x0f\n" +
	"\rLogoutRequest\"\x10\n" +
	"\x0eLogoutResponse\")\n" +
	"\x11EnrollTotpRequest\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\"v\n" +
	"\x12EnrollTotpResponse\x12'\n" +
	"\x06factor\x18\x01 \x01(\v2\x0f.plux.v1.FactorR\x06factor\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12\x1f\n" +
	"\votpauth_url\x18\x03 \x01(\tR\n" +
	"otpauthUrl\"-\n" +
	"\x15EnrollWebauthnRequest\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\"l\n" +
	"\x16EnrollWebauthnResponse\x12'\n" +
	"\x06factor\x18\x01 \x01(\v2\x0f.plux.v1.FactorR\x06factor\x12)\n" +
	"\x10creation_options\x18\x02 \x01(\fR\x0fcreationOptions\"i\n" +
	"\x14ConfirmFactorRequest\x12\x1b\n" +
	"\tfactor_id\x18\x01 \x01(\tR\bfactorId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12 \n" +
	"\vattestation\x18\x03 \x01(\fR\vattestation\"@\n" +
	"\x15ConfirmFactorResponse\x12'\n" +
	"\x06factor\x18\x01 \x01(\v2\x0f.plux.v1.FactorR\x06factor\"\x14\n" +
	"\x12ListFactorsRequest\"@\n" +
	"\x13ListFactorsResponse\x12)\n" +
	"\afactors\x18\x01 \x03(\v2\x0f.plux.v1.FactorR\afactors\"2\n" +
	"\x13DeleteFactorRequest\x12\x1b\n" +
	"\tfactor_id\x18\x01 \x01(\tR\bfactorId\"\x16\n" +
	"\x14DeleteFactorResponse\"Q\n" +
	"\x1fStartDeviceAuthorizationRequest\x12\x16\n" +
	"\x06client\x18\x01 \x01(\tR\x06client\x12\x16\n" +
	"\x06scopes\x18\x02 \x03(\tR\x06scopes\"\xad\x02\n" +
	" StartDeviceAuthorizationResponse\x12\x1f\n" +
	"\vdevice_code\x18\x01 \x01(\tR\n" +
	"deviceCode\x12\x1b\n" +
	"\tuser_code\x18\x02 \x01(\tR\buserCode\x12)\n" +
	"\x10verification_uri\x18\x03 \x01(\tR\x0fverificationUri\x12:\n" +
	"\x19verification_uri_complete\x18\x04 \x01(\tR\x17verificationUriComplete\x12)\n" +
	"\x10interval_seconds\x18\x05 \x01(\x05R\x0fintervalSeconds\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"A\n" +
	"\x1ePollDeviceAuthorizationRequest\x12\x1f\n" +
	"\vdevice_code\x18\x01 \x01(\tR\n" +
	"deviceCode\"}\n" +
	"\x1fPollDeviceAuthorizationResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12*\n" +
	"\x05token\x18\x02 \x01(\v2\x14.plux.v1.AccessTokenR\x05token\x12\x16\n" +
	"\x06secret\x18\x03 \x01(\tR\x06secret\"i\n" +
	"!ApproveDeviceAuthorizationRequest\x12\x1b\n" +
	"\tuser_code\x18\x01 \x01(\tR\buserCode\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\"$\n" +
	"\"ApproveDeviceAuthorizationResponse\"\x92\x03\n" +
	"\vAccessToken\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12'\n" +
	"\x0forganization_id\x18\x04 \x01(\tR\x0eorganizationId\x12\x16\n" +
	"\x06scopes\x18\x05 \x03(\tR\x06scopes\x12\x16\n" +
	"\x06prefix\x18\x06 \x01(\tR\x06prefix\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12<\n" +
	"\flast_used_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\x129\n" +
	"\n" +
	"revoked_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\"\x90\x01\n" +
	"\x18CreateAccessTokenRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x16\n" +
	"\x06scopes\x18\x03 \x03(\tR\x06scopes\x12\x1f\n" +
	"\vttl_seconds\x18\x04 \x01(\x03R\n" +
	"ttlSeconds\"_\n" +
	"\x19CreateAccessTokenResponse\x12*\n" +
	"\x05token\x18\x01 \x01(\v2\x14.plux.v1.AccessTokenR\x05token\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\"e\n" +
	"\x17ListAccessTokensRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12!\n" +
	"\x04page\x18\x02 \x01(\v2\r.plux.v1.PageR\x04page\"q\n" +
	"\x18ListAccessTokensResponse\x12,\n" +
	"\x06tokens\x18\x01 \x03(\v2\x14.plux.v1.AccessTokenR\x06tokens\x12'\n" +
	"\x04page\x18\x02 \x01(\v2\x13.plux.v1.PageResultR\x04page\"*\n" +
	"\x18RevokeAccessTokenRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1b\n" +
	"\x19RevokeAccessTokenResponse\"\x81\x01\n" +
	"\x1fExchangeWorkloadIdentityRequest\x12\x1d\n" +
	"\n" +
	"oidc_token\x18\x01 \x01(\tR\toidcToken\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x16\n" +
	"\x06scopes\x18\x03 \x03(\tR\x06scopes\"\x8d\x01\n" +
	" ExchangeWorkloadIdentityResponse\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x16\n" +
	"\x06scopes\x18\x03 \x03(\tR\x06scopes\"e\n" +
	"\x17ListAuditEntriesRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12!\n" +
	"\x04page\x18\x02 \x01(\v2\r.plux.v1.PageR\x04page\"r\n" +
	"\x18ListAuditEntriesResponse\x12-\n" +
	"\aentries\x18\x01 \x03(\v2\x13.plux.v1.AuditEntryR\aentries\x12'\n" +
	"\x04page\x18\x02 \x01(\v2\x13.plux.v1.PageResultR\x04page2\xcf\r\n" +
	"\x0fIdentityService\x12S\n" +
	"\x0eGetCurrentUser\x12\x1e.plux.v1.GetCurrentUserRequest\x1a\x1f.plux.v1.GetCurrentUserResponse\"\x00\x12_\n" +
	"\x12StartPasswordLogin\x12\".plux.v1.StartPasswordLoginRequest\x1a#.plux.v1.StartPasswordLoginResponse\"\x00\x12S\n" +
	"\x0eStartOidcLogin\x12\x1e.plux.v1.StartOidcLoginRequest\x1a\x1f.plux.v1.StartOidcLoginResponse\"\x00\x12\\\n" +
	"\x11CompleteOidcLogin\x12!.plux.v1.CompleteOidcLoginRequest\x1a\".plux.v1.CompleteOidcLoginResponse\"\x00\x12J\n" +
	"\vCompleteMfa\x12\x1b.plux.v1.CompleteMfaRequest\x1a\x1c.plux.v1.CompleteMfaResponse\"\x00\x12;\n" +
	"\x06Logout\x12\x16.plux.v1.LogoutRequest\x1a\x17.plux.v1.LogoutResponse\"\x00\x12G\n" +
	"\n" +
	"EnrollTotp\x12\x1a.plux.v1.EnrollTotpRequest\x1a\x1b.plux.v1.EnrollTotpResponse\"\x00\x12S\n" +
	"\x0eEnrollWebauthn\x12\x1e.plux.v1.EnrollWebauthnRequest\x1a\x1f.plux.v1.EnrollWebauthnResponse\"\x00\x12P\n" +
	"\rConfirmFactor\x12\x1d.plux.v1.ConfirmFactorRequest\x1a\x1e.plux.v1.ConfirmFactorResponse\"\x00\x12J\n" +
	"\vListFactors\x12\x1b.plux.v1.ListFactorsRequest\x1a\x1c.plux.v1.ListFactorsResponse\"\x00\x12M\n" +
	"\fDeleteFactor\x12\x1c.plux.v1.DeleteFactorRequest\x1a\x1d.plux.v1.DeleteFactorResponse\"\x00\x12q\n" +
	"\x18StartDeviceAuthorization\x12(.plux.v1.StartDeviceAuthorizationRequest\x1a).plux.v1.StartDeviceAuthorizationResponse\"\x00\x12n\n" +
	"\x17PollDeviceAuthorization\x12'.plux.v1.PollDeviceAuthorizationRequest\x1a(.plux.v1.PollDeviceAuthorizationResponse\"\x00\x12w\n" +
	"\x1aApproveDeviceAuthorization\x12*.plux.v1.ApproveDeviceAuthorizationRequest\x1a+.plux.v1.ApproveDeviceAuthorizationResponse\"\x00\x12\\\n" +
	"\x11CreateAccessToken\x12!.plux.v1.CreateAccessTokenRequest\x1a\".plux.v1.CreateAccessTokenResponse\"\x00\x12Y\n" +
	"\x10ListAccessTokens\x12 .plux.v1.ListAccessTokensRequest\x1a!.plux.v1.ListAccessTokensResponse\"\x00\x12\\\n" +
	"\x11RevokeAccessToken\x12!.plux.v1.RevokeAccessTokenRequest\x1a\".plux.v1.RevokeAccessTokenResponse\"\x00\x12q\n" +
	"\x18ExchangeWorkloadIdentity\x12(.plux.v1.ExchangeWorkloadIdentityRequest\x1a).plux.v1.ExchangeWorkloadIdentityResponse\"\x00\x12Y\n" +
	"\x10ListAuditEntries\x12 .plux.v1.ListAuditEntriesRequest\x1a!.plux.v1.ListAuditEntriesResponse\"\x00B=Z;github.com/nightCode42/plux3/backend/internal/pluxv1;pluxv1b\x06proto3"

var (
	file_plux_v1_identity_proto_rawDescOnce sync.Once
	file_plux_v1_identity_proto_rawDescData []byte
)

func file_plux_v1_identity_proto_rawDescGZIP() []byte {
	file_plux_v1_identity_proto_rawDescOnce.Do(func() {
		file_plux_v1_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plux_v1_identity_proto_rawDesc), len(file_plux_v1_identity_proto_rawDesc)))
	})
	return file_plux_v1_identity_proto_rawDescData
}

var file_plux_v1_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 43)
var file_plux_v1_identity_proto_goTypes = []any{
	(*User)(nil),                               // 0: plux.v1.User
	(*Factor)(nil),                             // 1: plux.v1.Factor
	(*Session)(nil),                            // 2: plux.v1.Session
	(*MfaChallenge)(nil),                       // 3: plux.v1.MfaChallenge
	(*GetCurrentUserRequest)(nil),              // 4: plux.v1.GetCurrentUserRequest
	(*GetCurrentUserResponse)(nil),             // 5: plux.v1.GetCurrentUserResponse
	(*StartPasswordLoginRequest)(nil),          // 6: plux.v1.StartPasswordLoginRequest
	(*StartPasswordLoginResponse)(nil),         // 7: plux.v1.StartPasswordLoginResponse
	(*StartOidcLoginRequest)(nil),              // 8: plux.v1.StartOidcLoginRequest
	(*StartOidcLoginResponse)(nil),             // 9: plux.v1.StartOidcLoginResponse
	(*CompleteOidcLoginRequest)(nil),           // 10: plux.v1.CompleteOidcLoginRequest
	(*CompleteOidcLoginResponse)(nil),          // 11: plux.v1.CompleteOidcLoginResponse
	(*CompleteMfaRequest)(nil),                 // 12: plux.v1.CompleteMfaRequest
	(*CompleteMfaResponse)(nil),                // 13: plux.v1.CompleteMfaResponse
	(*LogoutRequest)(nil),                      // 14: plux.v1.LogoutRequest
	(*LogoutResponse)(nil),                     // 15: plux.v1.LogoutResponse
	(*EnrollTotpRequest)(nil),                  // 16: plux.v1.EnrollTotpRequest
	(*EnrollTotpResponse)(nil),                 // 17: plux.v1.EnrollTotpResponse
	(*EnrollWebauthnRequest)(nil),              // 18: plux.v1.EnrollWebauthnRequest
	(*EnrollWebauthnResponse)(nil),             // 19: plux.v1.EnrollWebauthnResponse
	(*ConfirmFactorRequest)(nil),               // 20: plux.v1.ConfirmFactorRequest
	(*ConfirmFactorResponse)(nil),              // 21: plux.v1.ConfirmFactorResponse
	(*ListFactorsRequest)(nil),                 // 22: plux.v1.ListFactorsRequest
	(*ListFactorsResponse)(nil),                // 23: plux.v1.ListFactorsResponse
	(*DeleteFactorRequest)(nil),                // 24: plux.v1.DeleteFactorRequest
	(*DeleteFactorResponse)(nil),               // 25: plux.v1.DeleteFactorResponse
	(*StartDeviceAuthorizationRequest)(nil),    // 26: plux.v1.StartDeviceAuthorizationRequest
	(*StartDeviceAuthorizationResponse)(nil),   // 27: plux.v1.StartDeviceAuthorizationResponse
	(*PollDeviceAuthorizationRequest)(nil),     // 28: plux.v1.PollDeviceAuthorizationRequest
	(*PollDeviceAuthorizationResponse)(nil),    // 29: plux.v1.PollDeviceAuthorizationResponse
	(*ApproveDeviceAuthorizationRequest)(nil),  // 30: plux.v1.ApproveDeviceAuthorizationRequest
	(*ApproveDeviceAuthorizationResponse)(nil), // 31: plux.v1.ApproveDeviceAuthorizationResponse
	(*AccessToken)(nil),                        // 32: plux.v1.AccessToken
	(*CreateAccessTokenRequest)(nil),           // 33: plux.v1.CreateAccessTokenRequest
	(*CreateAccessTokenResponse)(nil),          // 34: plux.v1.CreateAccessTokenResponse
	(*ListAccessTokensRequest)(nil),            // 35: plux.v1.ListAccessTokensRequest
	(*ListAccessTokensResponse)(nil),           // 36: plux.v1.ListAccessTokensResponse
	(*RevokeAccessTokenRequest)(nil),           // 37: plux.v1.RevokeAccessTokenRequest
	(*RevokeAccessTokenResponse)(nil),          // 38: plux.v1.RevokeAccessTokenResponse
	(*ExchangeWorkloadIdentityRequest)(nil),    // 39: plux.v1.ExchangeWorkloadIdentityRequest
	(*ExchangeWorkloadIdentityResponse)(nil),   // 40: plux.v1.ExchangeWorkloadIdentityResponse
	(*ListAuditEntriesRequest)(nil),            // 41: plux.v1.ListAuditEntriesRequest
	(*ListAuditEntriesResponse)(nil),           // 42: plux.v1.ListAuditEntriesResponse
	(*timestamppb.Timestamp)(nil),              // 43: google.protobuf.Timestamp
	(*Member)(nil),                             // 44: plux.v1.Member
	(*Page)(nil),                               // 45: plux.v1.Page
	(*PageResult)(nil),                         // 46: plux.v1.PageResult
	(*AuditEntry)(nil),                         // 47: plux.v1.AuditEntry
}
var file_plux_v1_identity_proto_depIdxs = []int32{
	43, // 0: plux.v1.User.created_at:type_name -> google.protobuf.Timestamp
	43, // 1: plux.v1.User.last_login_at:type_name -> google.protobuf.Timestamp
	43, // 2: plux.v1.Factor.created_at:type_name -> google.protobuf.Timestamp
	43, // 3: plux.v1.Factor.last_used_at:type_name -> google.protobuf.Timestamp
	43, // 4: plux.v1.Session.expires_at:type_name -> google.protobuf.Timestamp
	43, // 5: plux.v1.MfaChallenge.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 6: plux.v1.GetCurrentUserResponse.user:type_name -> plux.v1.User
	44, // 7: plux.v1.GetCurrentUserResponse.memberships:type_name -> plux.v1.Member
	2,  // 8: plux.v1.StartPasswordLoginResponse.session:type_name -> plux.v1.Session
	3,  // 9: plux.v1.StartPasswordLoginResponse.challenge:type_name -> plux.v1.MfaChallenge
	2,  // 10: plux.v1.CompleteOidcLoginResponse.session:type_name -> plux.v1.Session
	3,  // 11: plux.v1.CompleteOidcLoginResponse.challenge:type_name -> plux.v1.MfaChallenge
	2,  // 12: plux.v1.CompleteMfaResponse.session:type_name -> plux.v1.Session
	1,  // 13: plux.v1.EnrollTotpResponse.factor:type_name -> plux.v1.Factor
	1,  // 14: plux.v1.EnrollWebauthnResponse.factor:type_name -> plux.v1.Factor
	1,  // 15: plux.v1.ConfirmFactorResponse.factor:type_name -> plux.v1.Factor
	1,  // 16: plux.v1.ListFactorsResponse.factors:type_name -> plux.v1.Factor
	43, // 17: plux.v1.StartDeviceAuthorizationResponse.expires_at:type_name -> google.protobuf.Timestamp
	32, // 18: plux.v1.PollDeviceAuthorizationResponse.token:type_name -> plux.v1.AccessToken
	43, // 19: plux.v1.AccessToken.created_at:type_name -> google.protobuf.Timestamp
	43, // 20: plux.v1.AccessToken.expires_at:type_name -> google.protobuf.Timestamp
	43, // 21: plux.v1.AccessToken.last_used_at:type_name -> google.protobuf.Timestamp
	43, // 22: plux.v1.AccessToken.revoked_at:type_name -> google.protobuf.Timestamp
	32, // 23: plux.v1.CreateAccessTokenResponse.token:type_name -> plux.v1.AccessToken
	45, // 24: plux.v1.ListAccessTokensRequest.page:type_name -> plux.v1.Page
	32, // 25: plux.v1.ListAccessTokensResponse.tokens:type_name -> plux.v1.AccessToken
	46, // 26: plux.v1.ListAccessTokensResponse.page:type_name -> plux.v1.PageResult
	43, // 27: plux.v1.ExchangeWorkloadIdentityResponse.expires_at:type_name -> google.protobuf.Timestamp
	45, // 28: plux.v1.ListAuditEntriesRequest.page:type_name -> plux.v1.Page
	47, // 29: plux.v1.ListAuditEntriesResponse.entries:type_name -> plux.v1.AuditEntry
	46, // 30: plux.v1.ListAuditEntriesResponse.page:type_name -> plux.v1.PageResult
	4,  // 31: plux.v1.IdentityService.GetCurrentUser:input_type -> plux.v1.GetCurrentUserRequest
	6,  // 32: plux.v1.IdentityService.StartPasswordLogin:input_type -> plux.v1.StartPasswordLoginRequest
	8,  // 33: plux.v1.IdentityService.StartOidcLogin:input_type -> plux.v1.StartOidcLoginRequest
	10, // 34: plux.v1.IdentityService.CompleteOidcLogin:input_type -> plux.v1.CompleteOidcLoginRequest
	12, // 35: plux.v1.IdentityService.CompleteMfa:input_type -> plux.v1.CompleteMfaRequest
	14, // 36: plux.v1.IdentityService.Logout:input_type -> plux.v1.LogoutRequest
	16, // 37: plux.v1.IdentityService.EnrollTotp:input_type -> plux.v1.EnrollTotpRequest
	18, // 38: plux.v1.IdentityService.EnrollWebauthn:input_type -> plux.v1.EnrollWebauthnRequest
	20, // 39: plux.v1.IdentityService.ConfirmFactor:input_type -> plux.v1.ConfirmFactorRequest
	22, // 40: plux.v1.IdentityService.ListFactors:input_type -> plux.v1.ListFactorsRequest
	24, // 41: plux.v1.IdentityService.DeleteFactor:input_type -> plux.v1.DeleteFactorRequest
	26, // 42: plux.v1.IdentityService.StartDeviceAuthorization:input_type -> plux.v1.StartDeviceAuthorizationRequest
	28, // 43: plux.v1.IdentityService.PollDeviceAuthorization:input_type -> plux.v1.PollDeviceAuthorizationRequest
	30, // 44: plux.v1.IdentityService.ApproveDeviceAuthorization:input_type -> plux.v1.ApproveDeviceAuthorizationRequest
	33, // 45: plux.v1.IdentityService.CreateAccessToken:input_type -> plux.v1.CreateAccessTokenRequest
	35, // 46: plux.v1.IdentityService.ListAccessTokens:input_type -> plux.v1.ListAccessTokensRequest
	37, // 47: plux.v1.IdentityService.RevokeAccessToken:input_type -> plux.v1.RevokeAccessTokenRequest
	39, // 48: plux.v1.IdentityService.ExchangeWorkloadIdentity:input_type -> plux.v1.ExchangeWorkloadIdentityRequest
	41, // 49: plux.v1.IdentityService.ListAuditEntries:input_type -> plux.v1.ListAuditEntriesRequest
	5,  // 50: plux.v1.IdentityService.GetCurrentUser:output_type -> plux.v1.GetCurrentUserResponse
	7,  // 51: plux.v1.IdentityService.StartPasswordLogin:output_type -> plux.v1.StartPasswordLoginResponse
	9,  // 52: plux.v1.IdentityService.StartOidcLogin:output_type -> plux.v1.StartOidcLoginResponse
	11, // 53: plux.v1.IdentityService.CompleteOidcLogin:output_type -> plux.v1.CompleteOidcLoginResponse
	13, // 54: plux.v1.IdentityService.CompleteMfa:output_type -> plux.v1.CompleteMfaResponse
	15, // 55: plux.v1.IdentityService.Logout:output_type -> plux.v1.LogoutResponse
	17, // 56: plux.v1.IdentityService.EnrollTotp:output_type -> plux.v1.EnrollTotpResponse
	19, // 57: plux.v1.IdentityService.EnrollWebauthn:output_type -> plux.v1.EnrollWebauthnResponse
	21, // 58: plux.v1.IdentityService.ConfirmFactor:output_type -> plux.v1.ConfirmFactorResponse
	23, // 59: plux.v1.IdentityService.ListFactors:output_type -> plux.v1.ListFactorsResponse
	25, // 60: plux.v1.IdentityService.DeleteFactor:output_type -> plux.v1.DeleteFactorResponse
	27, // 61: plux.v1.IdentityService.StartDeviceAuthorization:output_type -> plux.v1.StartDeviceAuthorizationResponse
	29, // 62: plux.v1.IdentityService.PollDeviceAuthorization:output_type -> plux.v1.PollDeviceAuthorizationResponse
	31, // 63: plux.v1.IdentityService.ApproveDeviceAuthorization:output_type -> plux.v1.ApproveDeviceAuthorizationResponse
	34, // 64: plux.v1.IdentityService.CreateAccessToken:output_type -> plux.v1.CreateAccessTokenResponse
	36, // 65: plux.v1.IdentityService.ListAccessTokens:output_type -> plux.v1.ListAccessTokensResponse
	38, // 66: plux.v1.IdentityService.RevokeAccessToken:output_type -> plux.v1.RevokeAccessTokenResponse
	40, // 67: plux.v1.IdentityService.ExchangeWorkloadIdentity:output_type -> plux.v1.ExchangeWorkloadIdentityResponse
	42, // 68: plux.v1.IdentityService.ListAuditEntries:output_type -> plux.v1.ListAuditEntriesResponse
	50, // [50:69] is the sub-list for method output_type
	31, // [31:50] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_plux_v1_identity_proto_init() }
func file_plux_v1_identity_proto_init() {
	if File_plux_v1_identity_proto != nil {
		return
	}
	file_plux_v1_common_proto_init()
	file_plux_v1_org_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plux_v1_identity_proto_rawDesc), len(file_plux_v1_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   43,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plux_v1_identity_proto_goTypes,
		DependencyIndexes: file_plux_v1_identity_proto_depIdxs,
		MessageInfos:      file_plux_v1_identity_proto_msgTypes,
	}.Build()
	File_plux_v1_identity_proto = out.File
	file_plux_v1_identity_proto_goTypes = nil
	file_plux_v1_identity_proto_depIdxs = nil
}
