// SPDX-FileCopyrightText: 2026 Plux contributors
// SPDX-License-Identifier: Apache-2.0

// Package limits is the Go view of the limits registry, schema/limits.json
// (LIM-001, spec §30.4).
//
// Every size and count the compiler, the server and the bundle reader check
// comes from here; nothing is hard-coded. The registry table is generated by
// schemagen; this file holds the types and the resolution rules. A lower
// scope can only tighten a limit set above it (LIM-002), and warnings start
// at an explicit threshold or at 80% of the limit (LIM-003).
//
// Definitions and Set values are immutable and safe for concurrent use.
package limits

import (
	"fmt"
	"maps"
	"sort"
)

// Key names a limit, e.g. "page.nodes".
type Key string

// Unit is the unit of a limit's values.
type Unit uint8

// Units of the registry.
const (
	UnitBytes Unit = iota + 1
	UnitCount
	UnitMicroseconds
	UnitMilliseconds
	UnitOperations
	UnitCodepoints
)

// Scope is a bit set of the levels at which a limit can be set.
type Scope uint8

// Scopes, from the widest to the narrowest.
const (
	ScopeInstallation Scope = 1 << iota
	ScopeOrganization
	ScopeApp
	ScopePlugin
)

// Enforcer is a bit set of the components that enforce a limit.
type Enforcer uint8

// Components that enforce limits.
const (
	EnforcerCompiler Enforcer = 1 << iota
	EnforcerServer
	EnforcerRuntime
	EnforcerStudio
)

// Definition is one entry of the registry.
type Definition struct {
	// Key identifies the limit.
	Key Key
	// Unit is the unit of Default, Warning and Max.
	Unit Unit
	// Default is the installation default.
	Default int64
	// Warning is the explicit warning threshold; zero means 80% of the limit.
	Warning int64
	// Max is the hard maximum no scope can exceed.
	Max int64
	// Scopes are the levels at which the limit can be set.
	Scopes Scope
	// EnforcedBy lists the components that check the limit.
	EnforcedBy Enforcer
	// Phase is the phase in which the limit becomes binding.
	Phase string
	// Description explains what is limited.
	Description string
}

// Definitions returns every definition in key order.
func Definitions() []Definition { return append([]Definition(nil), registry[:]...) }

// Lookup returns the definition of a key.
func Lookup(k Key) (Definition, bool) {
	i := sort.Search(len(registry), func(i int) bool { return registry[i].Key >= k })
	if i < len(registry) && registry[i].Key == k {
		return registry[i], true
	}
	return Definition{}, false
}

// Set holds the effective value of every limit at one scope. The zero value
// is not usable; start from Defaults.
type Set struct {
	values map[Key]int64
}

// Defaults returns the installation defaults of every limit.
func Defaults() Set {
	values := make(map[Key]int64, len(registry))
	for _, d := range registry {
		values[d.Key] = d.Default
	}
	return Set{values: values}
}

// IsZero reports whether the set is the unusable zero value rather than
// one built from Defaults.
func (s Set) IsZero() bool { return s.values == nil }

// Get returns the effective value of a limit. Asking for an unregistered key
// is a programming error and panics, so it cannot go unnoticed in tests.
func (s Set) Get(k Key) int64 {
	v, ok := s.values[k]
	if !ok {
		panic(fmt.Sprintf("limits: unregistered key %q", k))
	}
	return v
}

// Warning returns the threshold at which a value of the limit is reported:
// the explicit threshold, scaled to a tightened limit, or 80% of the limit.
func (s Set) Warning(k Key) int64 {
	def, _ := Lookup(k)
	v := s.Get(k)
	if def.Warning == 0 {
		return v * 8 / 10
	}
	return min(def.Warning, v)
}

// Tighten returns a copy of s with the limit lowered to v at the given scope.
// A value above the current one, above the hard maximum, below one, or at a
// scope the limit does not allow is rejected (LIM-002).
func (s Set) Tighten(k Key, scope Scope, v int64) (Set, error) {
	def, ok := Lookup(k)
	if !ok {
		return s, fmt.Errorf("limits.Tighten: unknown key %q", k)
	}
	if def.Scopes&scope == 0 {
		return s, fmt.Errorf("limits.Tighten: %s cannot be set at this scope", k)
	}
	if v < 1 || v > def.Max || v > s.values[k] {
		return s, fmt.Errorf("limits.Tighten: %s = %d must be between 1 and the current %d", k, v, s.values[k])
	}
	c := Set{values: maps.Clone(s.values)}
	c.values[k] = v
	return c, nil
}
