// SPDX-FileCopyrightText: 2026 Plux contributors
// SPDX-License-Identifier: Apache-2.0

package trace

import (
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/nightCode42/plux3/tools/internal/spec"
)

// Entry is one requirement with its evidence.
type Entry struct {
	// Requirement is the requirement as written in the specification.
	Requirement spec.Requirement `json:"requirement"`
	// Evidence lists every place that verifies it.
	Evidence []Evidence `json:"evidence"`
}

// Report is the traceability report for the whole specification.
type Report struct {
	// Entries holds every requirement that is not withdrawn, in document order.
	Entries []Entry `json:"entries"`
	// Unknown lists evidence that cites identifiers the specification does not define.
	Unknown []Evidence `json:"unknown"`
	// Withdrawn lists evidence that cites withdrawn requirements.
	Withdrawn []Evidence `json:"withdrawn"`
}

// Build combines the specification with the evidence found in the repository.
func Build(doc *spec.Document, evidence []Evidence) Report {
	byID := map[string][]Evidence{}
	for _, e := range evidence {
		byID[e.ID] = append(byID[e.ID], e)
	}
	defined := doc.ByID()
	var r Report
	for _, req := range doc.Requirements {
		if req.Status == spec.StatusWithdrawn {
			r.Withdrawn = append(r.Withdrawn, byID[req.ID]...)
			continue
		}
		r.Entries = append(r.Entries, Entry{Requirement: req, Evidence: byID[req.ID]})
	}
	for _, e := range evidence {
		if _, ok := defined[e.ID]; !ok {
			r.Unknown = append(r.Unknown, e)
		}
	}
	return r
}

// Violations returns the defects that make the report fail in strict mode:
// a DONE MUST requirement without evidence (QA-070), and evidence that cites
// an unknown or withdrawn requirement (QA-071).
func (r Report) Violations() []string {
	var out []string
	for _, e := range r.Entries {
		req := e.Requirement
		if req.Status == spec.StatusDone && req.Priority == "MUST" && len(e.Evidence) == 0 {
			out = append(out, fmt.Sprintf("%s is DONE but no test or CI check verifies it", req.ID))
		}
	}
	for _, e := range r.Unknown {
		out = append(out, fmt.Sprintf("%s:%d cites %s, which the specification does not define", e.Path, e.Line, e.ID))
	}
	for _, e := range r.Withdrawn {
		out = append(out, fmt.Sprintf("%s:%d cites %s, which is WITHDRAWN", e.Path, e.Line, e.ID))
	}
	return out
}

// WriteMarkdown writes a human-readable report: totals by status and phase,
// then every requirement that has evidence or is in progress.
func (r Report) WriteMarkdown(w io.Writer) error {
	var b strings.Builder
	b.WriteString("# Requirements traceability\n\n")
	b.WriteString("Generated by `reqtrace report` from `docs/requirements.md` and the evidence in the repository (QA-070).\n\n")
	writeTotals(&b, r)
	writeEvidenceTable(&b, r)
	if v := r.Violations(); len(v) > 0 {
		b.WriteString("\n## Violations\n\n")
		for _, line := range v {
			b.WriteString("- " + line + "\n")
		}
	}
	_, err := io.WriteString(w, b.String())
	if err != nil {
		return fmt.Errorf("trace.WriteMarkdown: %w", err)
	}
	return nil
}

// writeTotals writes the status counts per phase.
func writeTotals(b *strings.Builder, r Report) {
	counts := map[string]map[string]int{}
	var phases []string
	for _, e := range r.Entries {
		p := e.Requirement.Phase
		if counts[p] == nil {
			counts[p] = map[string]int{}
			phases = append(phases, p)
		}
		counts[p][e.Requirement.Status]++
	}
	sort.Slice(phases, func(i, j int) bool { return phaseNumber(phases[i]) < phaseNumber(phases[j]) })
	b.WriteString("| Phase | SPEC | WIP | DONE | With evidence |\n|---|---|---|---|---|\n")
	for _, p := range phases {
		fmt.Fprintf(b, "| %s | %d | %d | %d | %d |\n", p,
			counts[p][spec.StatusSpec], counts[p][spec.StatusWIP], counts[p][spec.StatusDone], withEvidence(r, p))
	}
}

// writeEvidenceTable lists requirements that are in progress, done, or
// already have evidence.
func writeEvidenceTable(b *strings.Builder, r Report) {
	b.WriteString("\n| Requirement | Phase | Priority | Status | Evidence |\n|---|---|---|---|---|\n")
	for _, e := range r.Entries {
		req := e.Requirement
		if req.Status == spec.StatusSpec && len(e.Evidence) == 0 {
			continue
		}
		refs := make([]string, 0, len(e.Evidence))
		for _, ev := range e.Evidence {
			refs = append(refs, fmt.Sprintf("`%s:%d` (%s)", ev.Path, ev.Line, ev.Kind))
		}
		evidence := strings.Join(refs, "<br>")
		if evidence == "" {
			evidence = "—"
		}
		fmt.Fprintf(b, "| `%s` | %s | %s | %s | %s |\n", req.ID, req.Phase, req.Priority, req.Status, evidence)
	}
}

// withEvidence counts the requirements of a phase that have any evidence.
func withEvidence(r Report, phase string) int {
	n := 0
	for _, e := range r.Entries {
		if e.Requirement.Phase == phase && len(e.Evidence) > 0 {
			n++
		}
	}
	return n
}

// phaseNumber converts "P12" to 12 for ordering; malformed tags sort last.
func phaseNumber(phase string) int {
	var n int
	if _, err := fmt.Sscanf(phase, "P%d", &n); err != nil {
		return 1 << 30
	}
	return n
}
