// Generated by plux codegen from the app "bank". Do not edit: run plux codegen
// again after the app document changes (HST-030).
//
// ignore_for_file: type=lint, unused_element

import 'package:flutter/widgets.dart' as w;
import 'package:plux_flutter/plux_flutter.dart' as plux;

/// A typed route of the app: open it, show it inline, or list it as a
/// page (NAV-003, NAV-004, NAV-006).
final class PluxScreen<R> {
  const PluxScreen._(this.name, this.params, this._result);

  /// The route name.
  final String name;

  /// The parameters, in their JSON form.
  final Map<String, Object?> params;

  final R? Function(Object? json) _result;

  /// Opens the page and completes with its typed result, or null.
  Future<R?> push(w.BuildContext context) async =>
      _result(await plux.Plux.open<Object?>(context, name, params: params));

  /// The page inline, in a native widget tree.
  plux.PluxView view({
    w.Key? key,
    void Function(plux.PluxViewEvent event)? onEvent,
    plux.PluxViewSizing sizing = plux.PluxViewSizing.intrinsic,
  }) => plux.PluxView(
    name,
    key: key,
    inputs: params,
    onEvent: onEvent,
    sizing: sizing,
  );

  /// The page for a declarative pages list.
  plux.PluxPage<Object?> page({w.LocalKey? key}) =>
      plux.Plux.pageFor<Object?>(name, params: params, key: key);
}

/// The app's pages by route name (NAV-003, HST-030).
abstract final class PluxScreens {
  /// The page `dashboard`.
  static PluxScreen<void> dashboard() =>
      PluxScreen<void>._('dashboard', {}, (_) {});

  /// The page `kyc`.
  static PluxScreen<void> kyc() =>
      PluxScreen<void>._('kyc', {}, (_) {});

  /// The page `login`.
  static PluxScreen<void> login() =>
      PluxScreen<void>._('login', {}, (_) {});

  /// The page `result`.
  static PluxScreen<void> result({required int amountCents, required int balanceCents, required String message, required bool ok}) =>
      PluxScreen<void>._('result', {'amountCents': amountCents, 'balanceCents': balanceCents, 'message': message, 'ok': ok}, (_) {});

  /// The page `transfer`.
  static PluxScreen<void> transfer({required int balanceCents}) =>
      PluxScreen<void>._('transfer', {'balanceCents': balanceCents}, (_) {});
}

/// The type `Account`.
final class Account {
  /// Creates a value.
  const Account({required this.balanceCents, required this.currency, required this.iban, required this.id, required this.name});

  /// The value of JSON form [json].
  factory Account.fromJson(Map<String, Object?> json) => Account(balanceCents: json['balanceCents'] as int, currency: json['currency'] as String, iban: json['iban'] as String, id: json['id'] as String, name: json['name'] as String);

  /// The field `balanceCents`.
  final int balanceCents;

  /// The field `currency`.
  final String currency;

  /// The field `iban`.
  final String iban;

  /// The field `id`.
  final String id;

  /// The field `name`.
  final String name;

  /// The JSON form.
  Map<String, Object?> toJson() => {'balanceCents': balanceCents, 'currency': currency, 'iban': iban, 'id': id, 'name': name};
}

/// The type `LoginInput`.
final class LoginInput {
  /// Creates a value.
  const LoginInput({required this.password, required this.username});

  /// The value of JSON form [json].
  factory LoginInput.fromJson(Map<String, Object?> json) => LoginInput(password: json['password'] as String, username: json['username'] as String);

  /// The field `password`.
  final String password;

  /// The field `username`.
  final String username;

  /// The JSON form.
  Map<String, Object?> toJson() => {'password': password, 'username': username};
}

/// The type `LoginResult`.
final class LoginResult {
  /// Creates a value.
  const LoginResult({required this.expiresIn, required this.token});

  /// The value of JSON form [json].
  factory LoginResult.fromJson(Map<String, Object?> json) => LoginResult(expiresIn: json['expiresIn'] as int, token: json['token'] as String);

  /// The field `expiresIn`.
  final int expiresIn;

  /// The field `token`.
  final String token;

  /// The JSON form.
  Map<String, Object?> toJson() => {'expiresIn': expiresIn, 'token': token};
}

/// The type `Notification`.
final class Notification {
  /// Creates a value.
  const Notification({required this.accountId, required this.amountCents, required this.balanceCents, required this.toIban, required this.transferId});

  /// The value of JSON form [json].
  factory Notification.fromJson(Map<String, Object?> json) => Notification(accountId: json['accountId'] as String, amountCents: json['amountCents'] as int, balanceCents: json['balanceCents'] as int, toIban: json['toIban'] as String, transferId: json['transferId'] as String);

  /// The field `accountId`.
  final String accountId;

  /// The field `amountCents`.
  final int amountCents;

  /// The field `balanceCents`.
  final int balanceCents;

  /// The field `toIban`.
  final String toIban;

  /// The field `transferId`.
  final String transferId;

  /// The JSON form.
  Map<String, Object?> toJson() => {'accountId': accountId, 'amountCents': amountCents, 'balanceCents': balanceCents, 'toIban': toIban, 'transferId': transferId};
}

/// The type `Transaction`.
final class Transaction {
  /// Creates a value.
  const Transaction({required this.amountCents, required this.description, required this.id, required this.postedAt});

  /// The value of JSON form [json].
  factory Transaction.fromJson(Map<String, Object?> json) => Transaction(amountCents: json['amountCents'] as int, description: json['description'] as String, id: json['id'] as String, postedAt: json['postedAt'] as String);

  /// The field `amountCents`.
  final int amountCents;

  /// The field `description`.
  final String description;

  /// The field `id`.
  final String id;

  /// The field `postedAt`.
  final String postedAt;

  /// The JSON form.
  Map<String, Object?> toJson() => {'amountCents': amountCents, 'description': description, 'id': id, 'postedAt': postedAt};
}

/// The type `TransferInput`.
final class TransferInput {
  /// Creates a value.
  const TransferInput({required this.amountCents, required this.fromAccountId, required this.reference, required this.toIban});

  /// The value of JSON form [json].
  factory TransferInput.fromJson(Map<String, Object?> json) => TransferInput(amountCents: json['amountCents'] as int, fromAccountId: json['fromAccountId'] as String, reference: json['reference'] as String, toIban: json['toIban'] as String);

  /// The field `amountCents`.
  final int amountCents;

  /// The field `fromAccountId`.
  final String fromAccountId;

  /// The field `reference`.
  final String reference;

  /// The field `toIban`.
  final String toIban;

  /// The JSON form.
  Map<String, Object?> toJson() => {'amountCents': amountCents, 'fromAccountId': fromAccountId, 'reference': reference, 'toIban': toIban};
}

/// The type `TransferResult`.
final class TransferResult {
  /// Creates a value.
  const TransferResult({required this.balanceCents, required this.id, required this.status});

  /// The value of JSON form [json].
  factory TransferResult.fromJson(Map<String, Object?> json) => TransferResult(balanceCents: json['balanceCents'] as int, id: json['id'] as String, status: json['status'] as String);

  /// The field `balanceCents`.
  final int balanceCents;

  /// The field `id`.
  final String id;

  /// The field `status`.
  final String status;

  /// The JSON form.
  Map<String, Object?> toJson() => {'balanceCents': balanceCents, 'id': id, 'status': status};
}
