// SPDX-FileCopyrightText: 2026 Plux contributors
// SPDX-License-Identifier: Apache-2.0

// Package codegen writes the typed Dart API of a Plux app, the file
// `plux codegen` writes into a host app as lib/plux/plux.g.dart (HST-030):
// route builders with typed parameters and results, exported components
// with typed props, host event classes, exposed state accessors and
// feature flag accessors, so that misuse is a compile error in the host.
//
// It reads a project the compiler checked without errors. The output is
// deterministic: every list is sorted, and nothing of the environment or
// the clock reaches it (CMP-002).
//
// make gen writes the starter app's API from the starter fixture with the
// CLI, as a host app would (go-gen-check verifies the committed file).
package codegen

//go:generate go run ../../cmd/plux codegen --host ../../../apps/starter ../../../schema/testdata/documents/starter

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/nightCode42/plux3/backend/internal/schema"
)

// Dart is the generated library for project p.
func Dart(p *schema.Project) ([]byte, error) {
	if p == nil || p.App.Doc == nil {
		return nil, fmt.Errorf("the project has no app document")
	}
	g := &gen{p: p, app: p.App.Doc, types: map[string]map[string]*decl{}, helpers: map[string]bool{}}
	g.collectTypes()
	var body bytes.Buffer
	for _, step := range []func(*bytes.Buffer) error{g.screens, g.components, g.events, g.state, g.flags, g.declaredTypes} {
		if err := step(&body); err != nil {
			return nil, err
		}
	}
	var out bytes.Buffer
	fmt.Fprintf(&out, `// Generated by plux codegen from the app %q. Do not edit: run plux codegen
// again after the app document changes (HST-030).
//
// ignore_for_file: type=lint, unused_element

import 'package:flutter/widgets.dart' as w;
import 'package:plux_flutter/plux_flutter.dart' as plux;
`, g.app.Key)
	out.Write(body.Bytes())
	g.writeHelpers(&out)
	return out.Bytes(), nil
}

// decl is a declared object or enum type and the Dart class it becomes.
type decl struct {
	schema.TypeDecl
	class string
	scope string // "" for the app, else the plugin key
}

type gen struct {
	p       *schema.Project
	app     *schema.AppDocument
	types   map[string]map[string]*decl // scope → name → type
	all     []*decl
	helpers map[string]bool
}

// collectTypes indexes the app's and the plugins' declared types. A
// plugin type whose name another scope also declares is prefixed with its
// plugin's key, so every class name is unique.
func (g *gen) collectTypes() {
	count := map[string]int{}
	add := func(scope string, ts []schema.TypeDecl) {
		g.types[scope] = map[string]*decl{}
		for _, t := range ts {
			d := &decl{TypeDecl: t, class: t.Name, scope: scope}
			g.types[scope][t.Name] = d
			g.all = append(g.all, d)
			count[t.Name]++
		}
	}
	add("", g.app.Types)
	for _, pl := range g.p.Plugins {
		if pl.Doc != nil {
			add(pl.Doc.Key, pl.Doc.Types)
		}
	}
	generated := map[string]bool{
		"PluxScreen": true, "PluxScreens": true, "PluxComponents": true,
		"PluxHostEvents": true, "PluxAppState": true, "PluxTypedState": true, "PluxFlags": true,
	}
	for _, e := range g.app.HostEvents {
		generated[upper(e.Name)+"Event"] = true
	}
	for _, d := range g.all {
		if d.scope != "" && count[d.Name] > 1 {
			d.class = upper(d.scope) + d.Name
		}
		if generated[d.class] {
			d.class += "Type"
		}
	}
	sort.Slice(g.all, func(i, j int) bool { return g.all[i].class < g.all[j].class })
}

// lookup finds the declared type name in scope, then in the app.
func (g *gen) lookup(scope, name string) (*decl, error) {
	if d := g.types[scope][name]; d != nil {
		return d, nil
	}
	if d := g.types[""][name]; d != nil {
		return d, nil
	}
	return nil, fmt.Errorf("type %s is not declared", name)
}

// dart is the Dart type of t in scope.
func (g *gen) dart(t *typ, scope string) (string, error) {
	var s string
	switch t.kind {
	case "list", "map":
		e, err := g.dart(t.elem, scope)
		if err != nil {
			return "", err
		}
		if t.kind == "list" {
			s = "List<" + e + ">"
		} else {
			s = "Map<String, " + e + ">"
		}
	case "named":
		d, err := g.lookup(scope, t.name)
		if err != nil {
			return "", err
		}
		s = d.class
	default:
		s = scalars[t.kind]
	}
	if t.nullable {
		s += "?"
	}
	return s, nil
}

// enc is the Dart expression for the JSON form of v, a value of type t
// (document-model.md §3); depth names nested loop variables.
func (g *gen) enc(t *typ, v, scope string, depth int) (string, error) {
	if t.nullable {
		inner, err := g.enc(t.nonNull(), "e", scope, depth+1)
		if err != nil || inner == "e" {
			return v, err
		}
		g.helpers["nullable"] = true
		return fmt.Sprintf("_nullable(%s, (e) => %s)", v, inner), nil
	}
	e := fmt.Sprintf("e%d", depth)
	switch t.kind {
	case "list":
		inner, err := g.enc(t.elem, e, scope, depth+1)
		if err != nil || inner == e {
			return v, err
		}
		return fmt.Sprintf("[for (final %s in %s) %s]", e, v, inner), nil
	case "map":
		inner, err := g.enc(t.elem, e+".value", scope, depth+1)
		if err != nil || inner == e+".value" {
			return v, err
		}
		return fmt.Sprintf("{for (final %s in %s.entries) %s.key: %s}", e, v, e, inner), nil
	case "named":
		d, err := g.lookup(scope, t.name)
		if err != nil {
			return "", err
		}
		if len(d.Enum) > 0 {
			return v + ".json", nil
		}
		return v + ".toJson()", nil
	case "date":
		g.helpers["date"] = true
		return "_dateJson(" + v + ")", nil
	case "dateTime":
		return v + ".toUtc().toIso8601String()", nil
	case "duration":
		return v + ".inMilliseconds", nil
	case "color":
		g.helpers["color"] = true
		return "_colorJson(" + v + ")", nil
	case "money":
		return fmt.Sprintf("{'amount': %s.amount, 'currency': %s.currency}", v, v), nil
	}
	return v, nil
}

// dec is the Dart expression for the value of type t whose JSON form is
// j, an `Object?`.
func (g *gen) dec(t *typ, j, scope string, depth int) (string, error) {
	if t.nullable {
		inner, err := g.dec(t.nonNull(), "e", scope, depth+1)
		if err != nil {
			return "", err
		}
		g.helpers["nullable"] = true
		return fmt.Sprintf("_nullable(%s, (e) => %s)", j, inner), nil
	}
	e := fmt.Sprintf("e%d", depth)
	switch t.kind {
	case "list":
		inner, err := g.dec(t.elem, e, scope, depth+1)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("[for (final %s in %s as List<Object?>) %s]", e, j, inner), nil
	case "map":
		inner, err := g.dec(t.elem, e+".value", scope, depth+1)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("{for (final %s in (%s as Map<String, Object?>).entries) %s.key: %s}", e, j, e, inner), nil
	case "named":
		d, err := g.lookup(scope, t.name)
		if err != nil {
			return "", err
		}
		if len(d.Enum) > 0 {
			return fmt.Sprintf("%s.fromJson(%s as String)", d.class, j), nil
		}
		return fmt.Sprintf("%s.fromJson(%s as Map<String, Object?>)", d.class, j), nil
	case "int":
		return j + " as int", nil
	case "double":
		return "(" + j + " as num).toDouble()", nil
	case "bool":
		return j + " as bool", nil
	case "date", "dateTime":
		return "DateTime.parse(" + j + " as String)", nil
	case "duration":
		return "Duration(milliseconds: " + j + " as int)", nil
	case "color":
		g.helpers["color"] = true
		return "_colorFromJson(" + j + " as String)", nil
	case "money":
		g.helpers["money"] = true
		return "_moneyFromJson(" + j + ")", nil
	}
	return j + " as String", nil
}

// param is one typed input of a builder: a page parameter or a prop.
type param struct {
	name, typ string
	required  bool
	hasDef    bool
	desc      string
}

// arguments writes a builder's named parameters and the expression of
// its inputs map.
func (g *gen) arguments(ps []param, scope string, taken ...string) (args []string, inputs string, err error) {
	sort.SliceStable(ps, func(i, j int) bool { return ps[i].name < ps[j].name })
	var entries []string
	for _, p := range ps {
		t, err := parseType(p.typ)
		if err != nil {
			return nil, "", err
		}
		d, err := g.dart(t.nonNull(), scope)
		if err != nil {
			return nil, "", err
		}
		name := member(p.name, taken...)
		if p.required && !p.hasDef && !t.nullable {
			args = append(args, "required "+d+" "+name)
			v, err := g.enc(t, name, scope, 0)
			if err != nil {
				return nil, "", err
			}
			entries = append(entries, fmt.Sprintf("'%s': %s", p.name, v))
			continue
		}
		args = append(args, d+"? "+name)
		v, err := g.enc(&typ{kind: t.kind, name: t.name, elem: t.elem, nullable: true}, name, scope, 0)
		if err != nil {
			return nil, "", err
		}
		entries = append(entries, fmt.Sprintf("'%s': ?%s", p.name, v))
	}
	return args, "{" + strings.Join(entries, ", ") + "}", nil
}

// page is a plugin page with a route.
type page struct {
	doc   *schema.PageDocument
	scope string
}

// screens writes PluxScreen and PluxScreens: one builder per routed page,
// by route name (NAV-003).
func (g *gen) screens(b *bytes.Buffer) error {
	var pages []page
	for _, pl := range g.p.Plugins {
		for _, pg := range pl.Pages {
			if pg.Doc != nil && pg.Doc.Route != "" && pl.Doc != nil {
				pages = append(pages, page{pg.Doc, pl.Doc.Key})
			}
		}
	}
	sort.Slice(pages, func(i, j int) bool { return pages[i].doc.Route < pages[j].doc.Route })
	b.WriteString(screenClass)
	b.WriteString("\n/// The app's pages by route name (NAV-003, HST-030).\nabstract final class PluxScreens {\n")
	for i, pg := range pages {
		line, err := g.screen(pg)
		if err != nil {
			return fmt.Errorf("page %s: %w", pg.doc.Route, err)
		}
		b.WriteString(sep(i) + line)
	}
	b.WriteString("}\n")
	return nil
}

// screen is the builder of one routed page.
func (g *gen) screen(pg page) (string, error) {
	var ps []param
	for _, p := range pg.doc.Params {
		ps = append(ps, param{name: p.Name, typ: p.Type, required: p.Required != nil && *p.Required, hasDef: len(p.Default) > 0, desc: p.Description})
	}
	args, inputs, err := g.arguments(ps, pg.scope)
	if err != nil {
		return "", err
	}
	result, decode := "void", "(_) {}"
	if pg.doc.Result != "" {
		t, err := parseType(pg.doc.Result)
		if err != nil {
			return "", err
		}
		if result, err = g.dart(t.nonNull(), pg.scope); err != nil {
			return "", err
		}
		body, err := g.dec(t.nonNull(), "j", pg.scope, 0)
		if err != nil {
			return "", err
		}
		g.helpers["nullable"] = true
		decode = "(j) => _nullable(j, (j) => " + body + ")"
	}
	doc := "The page `" + pg.doc.Route + "`."
	if pg.doc.Description != "" {
		doc = pg.doc.Description
	}
	return fmt.Sprintf("  /// %s\n  static PluxScreen<%s> %s(%s) =>\n      PluxScreen<%s>._('%s', %s, %s);\n",
		oneLine(doc), result, camel(pg.doc.Route), braces(args), result, pg.doc.Route, inputs, decode), nil
}

// components writes PluxComponents: a view builder per exported component,
// with typed props (NAV-004, ADR-0023).
func (g *gen) components(b *bytes.Buffer) error {
	type comp struct {
		doc   *schema.ComponentDocument
		scope string
	}
	var cs []comp
	for _, pl := range g.p.Plugins {
		for _, c := range pl.Components {
			if c.Doc != nil && c.Doc.Exported != nil && *c.Doc.Exported && pl.Doc != nil {
				cs = append(cs, comp{c.Doc, pl.Doc.Key})
			}
		}
	}
	if len(cs) == 0 {
		return nil
	}
	sort.Slice(cs, func(i, j int) bool { return cs[i].doc.Key < cs[j].doc.Key })
	b.WriteString("\n/// The components plugins export, shown inline by name (NAV-004).\nabstract final class PluxComponents {\n")
	for i, c := range cs {
		var ps []param
		for _, p := range c.doc.Props {
			ps = append(ps, param{name: p.Name, typ: p.Type, required: p.Required != nil && *p.Required, hasDef: len(p.Default) > 0})
		}
		args, inputs, err := g.arguments(ps, c.scope, "key", "onEvent", "sizing")
		if err != nil {
			return fmt.Errorf("component %s: %w", c.doc.Key, err)
		}
		args = append(args, "w.Key? key", "void Function(plux.PluxViewEvent event)? onEvent",
			"plux.PluxViewSizing sizing = plux.PluxViewSizing.intrinsic")
		doc := "The component `" + c.doc.Key + "`."
		if c.doc.Description != "" {
			doc = c.doc.Description
		}
		fmt.Fprintf(b, "%s  /// %s\n  static plux.PluxView %s(%s) => plux.PluxView(\n    '%s',\n    key: key,\n    inputs: %s,\n    onEvent: onEvent,\n    sizing: sizing,\n  );\n", sep(i),
			oneLine(doc), camel(c.doc.Key), braces(args), c.doc.Key, inputs)
	}
	b.WriteString("}\n")
	return nil
}

// events writes a class per declared host event and PluxHostEvents: the
// typed streams of the events plugins send, and a typed sender for each
// event the host sends into Plux (HST-013).
func (g *gen) events(b *bytes.Buffer) error {
	evs := append([]schema.HostEventDecl(nil), g.app.HostEvents...)
	if len(evs) == 0 {
		return nil
	}
	sort.Slice(evs, func(i, j int) bool { return evs[i].Name < evs[j].Name })
	for _, e := range evs {
		doc := "The host event `" + e.Name + "`."
		if e.Description != "" {
			doc = e.Description
		}
		if err := g.record(b, upper(e.Name)+"Event", doc, e.Fields, "", toPlux(e)); err != nil {
			return fmt.Errorf("host event %s: %w", e.Name, err)
		}
	}
	b.WriteString("\n/// The typed host events: those plugins emit with `emitHostEvent`, and\n/// those the host sends into Plux (HST-013).\nabstract final class PluxHostEvents {\n")
	i := 0
	for _, e := range evs {
		class := upper(e.Name) + "Event"
		if toHost(e) {
			fmt.Fprintf(b, "%s  /// The `%s` events.\n  static Stream<%s> get %s =>\n      plux.Plux.eventsNamed('%s').map((e) => %s.fromJson(e.payload));\n",
				sep(i), e.Name, class, member(e.Name), e.Name, class)
			i++
		}
		if toPlux(e) {
			fmt.Fprintf(b, "%s  /// Sends a `%s` event into Plux; completes with whether it was\n  /// accepted.\n  static Future<bool> send%s(%s event) =>\n      plux.Plux.sendEvent('%s', event.toJson());\n",
				sep(i), e.Name, upper(e.Name), class, e.Name)
			i++
		}
	}
	b.WriteString("}\n")
	return nil
}

// toHost reports whether plugins send an event to the host.
func toHost(e schema.HostEventDecl) bool {
	return e.Direction != schema.HostEventDirectionToPlux
}

// toPlux reports whether the host sends an event into Plux.
func toPlux(e schema.HostEventDecl) bool {
	return e.Direction == schema.HostEventDirectionToPlux || e.Direction == schema.HostEventDirectionBoth
}

// state writes PluxAppState: a typed handle per exposed app state entry
// (STA-030).
func (g *gen) state(b *bytes.Buffer) error {
	var es []schema.StateEntry
	for _, e := range g.app.State {
		if e.Exposed != nil && *e.Exposed {
			es = append(es, e)
		}
	}
	if len(es) == 0 {
		return nil
	}
	sort.Slice(es, func(i, j int) bool { return es[i].Name < es[j].Name })
	b.WriteString(stateClass)
	b.WriteString("\n/// The app state entries the host may read, write and watch (STA-030).\nabstract final class PluxAppState {\n")
	for i, e := range es {
		t, err := parseType(e.Type)
		if err != nil {
			return fmt.Errorf("state %s: %w", e.Name, err)
		}
		d, err := g.dart(t, "")
		if err != nil {
			return fmt.Errorf("state %s: %w", e.Name, err)
		}
		dec, err := g.dec(t, "j", "", 0)
		if err != nil {
			return fmt.Errorf("state %s: %w", e.Name, err)
		}
		enc, err := g.enc(t, "v", "", 0)
		if err != nil {
			return fmt.Errorf("state %s: %w", e.Name, err)
		}
		doc := "The app state entry `" + e.Name + "`."
		if e.Description != "" {
			doc = e.Description
		}
		fmt.Fprintf(b, "%s  /// %s\n  static final %s = PluxTypedState<%s>._(\n    '%s',\n    (j) => %s,\n    (v) => %s,\n  );\n",
			sep(i), oneLine(doc), member(e.Name), d, e.Name, dec, enc)
	}
	b.WriteString("}\n")
	return nil
}

// flags writes PluxFlags: a typed getter per feature flag, its default
// until a release is active (ABT-006).
func (g *gen) flags(b *bytes.Buffer) error {
	fs := append([]schema.FlagDecl(nil), g.app.Flags...)
	if len(fs) == 0 {
		return nil
	}
	sort.Slice(fs, func(i, j int) bool { return fs[i].Name < fs[j].Name })
	b.WriteString("\n/// The app's feature flags (ABT-006).\nabstract final class PluxFlags {\n")
	for i, f := range fs {
		d := scalars[string(f.Type)]
		def, err := literal(f.Default, string(f.Type))
		if err != nil {
			return fmt.Errorf("flag %s: %w", f.Name, err)
		}
		doc := "The feature flag `" + f.Name + "`."
		if f.Description != "" {
			doc = f.Description
		}
		fmt.Fprintf(b, "%s  /// %s\n  static %s get %s => plux.Plux.flag<%s>('%s') ?? %s;\n", sep(i), oneLine(doc), d, member(f.Name), d, f.Name, def)
	}
	b.WriteString("}\n")
	return nil
}

// literal is the Dart literal of a flag's default.
func literal(raw json.RawMessage, t string) (string, error) {
	var v any
	if err := json.Unmarshal(raw, &v); err != nil {
		return "", fmt.Errorf("default: %w", err)
	}
	switch x := v.(type) {
	case bool:
		return fmt.Sprint(x), nil
	case float64:
		if t == "double" && x == float64(int64(x)) {
			return fmt.Sprintf("%d.0", int64(x)), nil
		}
		return fmt.Sprint(x), nil
	case string:
		return DartString(x), nil
	}
	return "", fmt.Errorf("default %s is not a %s", raw, t)
}

// declaredTypes writes a class per declared object type and an enum per
// declared enum type.
func (g *gen) declaredTypes(b *bytes.Buffer) error {
	for _, d := range g.all {
		doc := "The type `" + d.Name + "`."
		if d.Description != "" {
			doc = d.Description
		}
		if len(d.Enum) > 0 {
			fmt.Fprintf(b, "\n/// %s\nenum %s {\n", oneLine(doc), d.class)
			for i, m := range d.Enum {
				sep := ","
				if i == len(d.Enum)-1 {
					sep = ";"
				}
				fmt.Fprintf(b, "  %s('%s')%s\n", member(m, "values", "index", "name", "json", "fromJson"), m, sep)
			}
			fmt.Fprintf(b, "\n  const %s(this.json);\n\n  /// The member of JSON form [json].\n  factory %s.fromJson(String json) =>\n      values.firstWhere((e) => e.json == json);\n\n  /// The JSON form.\n  final String json;\n}\n", d.class, d.class)
			continue
		}
		if err := g.record(b, d.class, doc, d.Fields, d.scope, true); err != nil {
			return fmt.Errorf("type %s: %w", d.Name, err)
		}
	}
	return nil
}

// record writes an immutable class of fields with fromJson, and toJson
// when withToJson.
func (g *gen) record(b *bytes.Buffer, class, doc string, fields []schema.Field, scope string, withToJson bool) error {
	fs := append([]schema.Field(nil), fields...)
	sort.Slice(fs, func(i, j int) bool { return fs[i].Name < fs[j].Name })
	var ctor, decs, decls, encs []string
	for _, f := range fs {
		t, err := parseType(f.Type)
		if err != nil {
			return err
		}
		d, err := g.dart(t, scope)
		if err != nil {
			return err
		}
		name := member(f.Name, "toJson", "fromJson")
		if t.nullable {
			ctor = append(ctor, "this."+name)
		} else {
			ctor = append(ctor, "required this."+name)
		}
		dec, err := g.dec(t, fmt.Sprintf("json['%s']", f.Name), scope, 0)
		if err != nil {
			return err
		}
		decs = append(decs, name+": "+dec)
		fdoc := "The field `" + f.Name + "`."
		if f.Description != "" {
			fdoc = f.Description
		}
		decls = append(decls, fmt.Sprintf("  /// %s\n  final %s %s;\n", oneLine(fdoc), d, name))
		enc, err := g.enc(t, name, scope, 0)
		if err != nil {
			return err
		}
		encs = append(encs, fmt.Sprintf("'%s': %s", f.Name, enc))
	}
	fmt.Fprintf(b, "\n/// %s\nfinal class %s {\n  /// Creates a value.\n  const %s(%s);\n\n", oneLine(doc), class, class, braces(ctor))
	fmt.Fprintf(b, "  /// The value of JSON form [json].\n  factory %s.fromJson(Map<String, Object?> json) => %s(%s);\n", class, class, strings.Join(decs, ", "))
	if len(decls) > 0 {
		b.WriteString("\n")
	}
	b.WriteString(strings.Join(decls, "\n"))
	if withToJson {
		if len(decls) > 0 {
			b.WriteString("\n")
		}
		fmt.Fprintf(b, "  /// The JSON form.\n  Map<String, Object?> toJson() => {%s};\n", strings.Join(encs, ", "))
	}
	b.WriteString("}\n")
	return nil
}

// writeHelpers writes the private conversions the library uses.
func (g *gen) writeHelpers(b *bytes.Buffer) {
	if g.helpers["nullable"] {
		b.WriteString("\nR? _nullable<T extends Object, R>(T? v, R Function(T v) f) => v == null ? null : f(v);\n")
	}
	if g.helpers["date"] {
		b.WriteString("\nString _dateJson(DateTime d) =>\n    '${d.year.toString().padLeft(4, '0')}-${d.month.toString().padLeft(2, '0')}-${d.day.toString().padLeft(2, '0')}';\n")
	}
	if g.helpers["color"] {
		b.WriteString(`
String _colorJson(w.Color c) {
  final argb = c.toARGB32();
  final rgba = ((argb & 0xffffff) << 8) | ((argb >> 24) & 0xff);
  return '#${rgba.toRadixString(16).padLeft(8, '0').toUpperCase()}';
}

w.Color _colorFromJson(String s) {
  final rgba = int.parse(s.substring(1), radix: 16);
  return w.Color(((rgba & 0xff) << 24) | (rgba >> 8));
}
`)
	}
	if g.helpers["money"] {
		b.WriteString("\n({String amount, String currency}) _moneyFromJson(Object? j) {\n  final m = j as Map<String, Object?>;\n  return (amount: m['amount'] as String, currency: m['currency'] as String);\n}\n")
	}
}

// sep is the blank line between members, before every one but the first.
func sep(i int) string {
	if i == 0 {
		return ""
	}
	return "\n"
}

// braces is a named parameter list, or nothing for none.
func braces(args []string) string {
	if len(args) == 0 {
		return ""
	}
	return "{" + strings.Join(args, ", ") + "}"
}

// oneLine is a description on one comment line.
func oneLine(s string) string {
	return strings.Join(strings.Fields(s), " ")
}

const screenClass = `
/// A typed route of the app: open it, show it inline, or list it as a
/// page (NAV-003, NAV-004, NAV-006).
final class PluxScreen<R> {
  const PluxScreen._(this.name, this.params, this._result);

  /// The route name.
  final String name;

  /// The parameters, in their JSON form.
  final Map<String, Object?> params;

  final R? Function(Object? json) _result;

  /// Opens the page and completes with its typed result, or null.
  Future<R?> push(w.BuildContext context) async =>
      _result(await plux.Plux.open<Object?>(context, name, params: params));

  /// The page inline, in a native widget tree.
  plux.PluxView view({
    w.Key? key,
    void Function(plux.PluxViewEvent event)? onEvent,
    plux.PluxViewSizing sizing = plux.PluxViewSizing.intrinsic,
  }) => plux.PluxView(
    name,
    key: key,
    inputs: params,
    onEvent: onEvent,
    sizing: sizing,
  );

  /// The page for a declarative pages list.
  plux.PluxPage<Object?> page({w.LocalKey? key}) =>
      plux.Plux.pageFor<Object?>(name, params: params, key: key);
}
`

const stateClass = `
/// A typed handle on an exposed app state entry (STA-030).
final class PluxTypedState<T> {
  const PluxTypedState._(this.name, this._decode, this._encode);

  /// The entry's name.
  final String name;

  final T Function(Object? json) _decode;
  final Object? Function(T value) _encode;

  plux.PluxState<Object?> get _state => plux.Plux.state<Object?>(name);

  /// The current value; null before a release is active.
  T? get value {
    final v = _state.value;
    return v == null ? null : _decode(v);
  }

  /// Writes [value]; completes with whether it was accepted.
  Future<bool> set(T value) => _state.set(_encode(value));

  /// One value per change.
  Stream<T?> watch() =>
      _state.watch().map((v) => v == null ? null : _decode(v));
}
`
