// SPDX-FileCopyrightText: 2026 Plux contributors
// SPDX-License-Identifier: Apache-2.0

// Package registry is the Go view of the widget and action registries:
// the widget descriptors, value types and enums under schema/widgets/ and
// the action descriptors under schema/actions/ (WGT-002, BND-011,
// ADR-0010).
//
// The tables are generated by schemagen from the registry files, which it
// checks first; this file holds the types and lookups. The compiler
// validates nodes and action steps against these descriptors and encodes
// them by their permanent IDs. No component keeps a hand-written list.
//
// Descriptors are shared, read-only data: callers must not modify the
// values or slices they receive.
package registry

import (
	"slices"
	"strings"
)

// Platform is a bit set of the platforms a widget supports.
type Platform uint8

// Platforms.
const (
	PlatformAndroid Platform = 1 << iota
	PlatformIOS
)

// Role is the accessibility role of a widget (A11Y-002).
type Role uint8

// Accessibility roles.
const (
	RoleNone Role = iota
	RoleButton
	RoleCheckbox
	RoleRadio
	RoleSwitch
	RoleSlider
	RoleTextField
	RoleImage
	RoleText
	RoleHeader
	RoleList
	RoleProgress
)

// Widget is a widget descriptor (WGT-001).
type Widget struct {
	// Type is the widget type name used in documents.
	Type string
	// ID is the permanent ID the bundle encodes (BND-011).
	ID uint32
	// Layer is 1 for core primitives and 2 for Plux components.
	Layer uint8
	// Phase is the phase in which the widget is implemented.
	Phase string
	// Revision is the current descriptor revision (WGT-004).
	Revision uint16
	// Runtimes[r-1] is the first runtime version implementing revision r.
	Runtimes []string
	// Category, Icon and Description are Studio metadata.
	Category    string
	Icon        string
	Description string
	// Platforms lists the supported platforms.
	Platforms Platform
	// Cost is the estimated build cost in microseconds on the mid-tier
	// reference device (CMP-040).
	Cost uint32
	// Role and Interactive are the accessibility requirements.
	Role        Role
	Interactive bool
	// TypeParameters are bound per node, such as the item type of a list.
	TypeParameters []string
	// Props, Events and Slots are sorted by ID.
	Props  []Prop
	Events []Event
	Slots  []Slot
	// Children is set when the widget takes a list of children.
	Children *Children
	// Deprecated is set when the widget is deprecated.
	Deprecated *Deprecation
}

// Prop is a widget prop.
type Prop struct {
	Name string
	ID   uint32
	// Type is a type expression of SCH-010, a value type or an enum.
	Type     string
	Required bool
	// Default is the default literal as JSON; empty when there is none.
	// Props equal to it are omitted from bundles (CMP-020).
	Default     string
	Constraints Constraints
	// Revision is the descriptor revision that added the prop.
	Revision   uint16
	Deprecated *Deprecation
	// Bindable is false when the prop accepts only literals.
	Bindable    bool
	Description string
}

// Constraints restrict literal values; a zero value restricts nothing.
type Constraints struct {
	Min, Max             Bound
	MinLength, MaxLength Bound
	// Pattern is a regular expression strings must match; empty for none.
	Pattern string
}

// Bound is an optional numeric bound.
type Bound struct {
	Value float64
	Set   bool
}

// Event is a widget event.
type Event struct {
	Name string
	ID   uint32
	// Payload is the type of `event` in handlers; empty for none.
	Payload     string
	Revision    uint16
	Deprecated  *Deprecation
	Description string
}

// Slot is a named slot.
type Slot struct {
	Name string
	ID   uint32
	// List is true when the slot holds a list of nodes.
	List     bool
	Required bool
	// Template is true when the slot is built per item, with `item` and
	// `index` in scope.
	Template    bool
	Revision    uint16
	Deprecated  *Deprecation
	Description string
}

// Children declares that a widget takes a list of children. Max is 0 when
// the number is unbounded.
type Children struct {
	Min, Max int
}

// Deprecation marks a member or entry as deprecated from a revision on.
type Deprecation struct {
	Revision uint16
	Message  string
}

// ValueType is a structured prop value such as EdgeInsets.
type ValueType struct {
	Name     string
	ID       uint32
	Revision uint16
	Runtimes []string
	// Fields are sorted by ID.
	Fields []Field
	// Constants are named values; a literal may be a constant's name.
	Constants   []Constant
	Description string
}

// Field is a field of a value type.
type Field struct {
	Name        string
	ID          uint32
	Type        string
	Required    bool
	Default     string
	Revision    uint16
	Deprecated  *Deprecation
	Description string
}

// Constant is a named value of a value type, as an object literal in JSON.
type Constant struct {
	Name  string
	Value string
}

// Enum is an enumeration.
type Enum struct {
	Name     string
	ID       uint32
	Revision uint16
	Runtimes []string
	// Values are sorted by ID.
	Values      []EnumValue
	Description string
}

// EnumValue is a value of an enum.
type EnumValue struct {
	Name        string
	ID          uint32
	Revision    uint16
	Deprecated  *Deprecation
	Description string
}

// Action is a built-in action (spec Appendix D).
type Action struct {
	Name     string
	ID       uint32
	Phase    string
	Category string
	// TypeParameters are bound from the step's context.
	TypeParameters []string
	// Inputs are sorted by ID.
	Inputs []Input
	// Output is the output type; empty for none.
	Output string
	// Branches are named edges besides next, onSuccess and onError;
	// BranchesFrom names a list<string> input whose values name more.
	Branches     []string
	BranchesFrom string
	Effects      []string
	Description  string
}

// Input is a typed input of an action.
type Input struct {
	Name     string
	ID       uint32
	Type     string
	Required bool
	Default  string
	// Ref is what a string input names, such as "state"; empty otherwise.
	Ref         string
	Description string
}

// Widgets returns every widget descriptor, sorted by type name.
func Widgets() []Widget { return slices.Clone(widgets[:]) }

// ValueTypes returns every value type, sorted by name.
func ValueTypes() []ValueType { return slices.Clone(valueTypes[:]) }

// Enums returns every enum, sorted by name.
func Enums() []Enum { return slices.Clone(enums[:]) }

// Actions returns every action, sorted by name.
func Actions() []Action { return slices.Clone(actions[:]) }

// LookupWidget returns the descriptor of a widget type.
func LookupWidget(name string) (Widget, bool) {
	return lookup(widgets[:], name, func(w *Widget) string { return w.Type })
}

// LookupValueType returns a value type by name.
func LookupValueType(name string) (ValueType, bool) {
	return lookup(valueTypes[:], name, func(t *ValueType) string { return t.Name })
}

// LookupEnum returns an enum by name.
func LookupEnum(name string) (Enum, bool) {
	return lookup(enums[:], name, func(e *Enum) string { return e.Name })
}

// LookupAction returns an action by name.
func LookupAction(name string) (Action, bool) {
	return lookup(actions[:], name, func(a *Action) string { return a.Name })
}

// Prop returns the prop with the given name.
func (w Widget) Prop(name string) (Prop, bool) {
	i := slices.IndexFunc(w.Props, func(p Prop) bool { return p.Name == name })
	if i < 0 {
		return Prop{}, false
	}
	return w.Props[i], true
}

// Event returns the event with the given name.
func (w Widget) Event(name string) (Event, bool) {
	i := slices.IndexFunc(w.Events, func(e Event) bool { return e.Name == name })
	if i < 0 {
		return Event{}, false
	}
	return w.Events[i], true
}

// Slot returns the slot with the given name.
func (w Widget) Slot(name string) (Slot, bool) {
	i := slices.IndexFunc(w.Slots, func(s Slot) bool { return s.Name == name })
	if i < 0 {
		return Slot{}, false
	}
	return w.Slots[i], true
}

// Runtime returns the first runtime version implementing revision r, or
// "" when r is not a revision of the widget.
func (w Widget) Runtime(r uint16) string {
	if r == 0 || int(r) > len(w.Runtimes) {
		return ""
	}
	return w.Runtimes[r-1]
}

// Value returns the enum value with the given name.
func (e Enum) Value(name string) (EnumValue, bool) {
	i := slices.IndexFunc(e.Values, func(v EnumValue) bool { return v.Name == name })
	if i < 0 {
		return EnumValue{}, false
	}
	return e.Values[i], true
}

// Field returns the field with the given name.
func (t ValueType) Field(name string) (Field, bool) {
	i := slices.IndexFunc(t.Fields, func(f Field) bool { return f.Name == name })
	if i < 0 {
		return Field{}, false
	}
	return t.Fields[i], true
}

// Input returns the input with the given name.
func (a Action) Input(name string) (Input, bool) {
	i := slices.IndexFunc(a.Inputs, func(in Input) bool { return in.Name == name })
	if i < 0 {
		return Input{}, false
	}
	return a.Inputs[i], true
}

// lookup finds name in table, which is sorted by key.
func lookup[T any](table []T, name string, key func(*T) string) (T, bool) {
	i, found := slices.BinarySearchFunc(table, name, func(e T, n string) int { return strings.Compare(key(&e), n) })
	if !found {
		var zero T
		return zero, false
	}
	return table[i], true
}
