// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assets.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeAsset = `-- name: CompleteAsset :one
UPDATE assets
   SET processing = $2, width = $3, height = $4, variants = $5, diagnostics = $6
 WHERE id = $1
RETURNING id, asset_id, organization_id, app_id, file, media_type, sha256, size, width, height, processing, variants, diagnostics, uploaded_by_kind, uploaded_by_id, uploaded_by, created_at, deleted_at
`

type CompleteAssetParams struct {
	ID          pgtype.UUID
	Processing  string
	Width       int32
	Height      int32
	Variants    []byte
	Diagnostics []byte
}

func (q *Queries) CompleteAsset(ctx context.Context, arg CompleteAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, completeAsset,
		arg.ID,
		arg.Processing,
		arg.Width,
		arg.Height,
		arg.Variants,
		arg.Diagnostics,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.OrganizationID,
		&i.AppID,
		&i.File,
		&i.MediaType,
		&i.Sha256,
		&i.Size,
		&i.Width,
		&i.Height,
		&i.Processing,
		&i.Variants,
		&i.Diagnostics,
		&i.UploadedByKind,
		&i.UploadedByID,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const countPendingAssets = `-- name: CountPendingAssets :one
SELECT count(*) FROM assets WHERE app_id = $1 AND deleted_at IS NULL AND processing = 'pending'
`

// The app's assets whose variants are not made yet (CMP-030).
func (q *Queries) CountPendingAssets(ctx context.Context, appID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingAssets, appID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findProcessedAsset = `-- name: FindProcessedAsset :one
SELECT id, asset_id, organization_id, app_id, file, media_type, sha256, size, width, height, processing, variants, diagnostics, uploaded_by_kind, uploaded_by_id, uploaded_by, created_at, deleted_at FROM assets
 WHERE organization_id = $1 AND sha256 = $2 AND processing = 'ready' AND variants <> '[]'::jsonb AND id <> $3
 ORDER BY created_at
 LIMIT 1
`

type FindProcessedAssetParams struct {
	OrganizationID pgtype.UUID
	Sha256         []byte
	ID             pgtype.UUID
}

// Another asset with the same content whose variants are made, so an
// upload of the same file is not transcoded twice. Every file an upload
// asks variants of gets at least one, so a ready one with none (an SVG
// uploaded before the server compiled SVGs) is not a copy to reuse.
func (q *Queries) FindProcessedAsset(ctx context.Context, arg FindProcessedAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, findProcessedAsset, arg.OrganizationID, arg.Sha256, arg.ID)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.OrganizationID,
		&i.AppID,
		&i.File,
		&i.MediaType,
		&i.Sha256,
		&i.Size,
		&i.Width,
		&i.Height,
		&i.Processing,
		&i.Variants,
		&i.Diagnostics,
		&i.UploadedByKind,
		&i.UploadedByID,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAsset = `-- name: GetAsset :one
SELECT id, asset_id, organization_id, app_id, file, media_type, sha256, size, width, height, processing, variants, diagnostics, uploaded_by_kind, uploaded_by_id, uploaded_by, created_at, deleted_at FROM assets WHERE asset_id = $1 AND deleted_at IS NULL ORDER BY created_at LIMIT 1
`

func (q *Queries) GetAsset(ctx context.Context, assetID pgtype.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, getAsset, assetID)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.OrganizationID,
		&i.AppID,
		&i.File,
		&i.MediaType,
		&i.Sha256,
		&i.Size,
		&i.Width,
		&i.Height,
		&i.Processing,
		&i.Variants,
		&i.Diagnostics,
		&i.UploadedByKind,
		&i.UploadedByID,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAssetByFile = `-- name: GetAssetByFile :one
SELECT id, asset_id, organization_id, app_id, file, media_type, sha256, size, width, height, processing, variants, diagnostics, uploaded_by_kind, uploaded_by_id, uploaded_by, created_at, deleted_at FROM assets WHERE app_id = $1 AND file = $2 AND deleted_at IS NULL
`

type GetAssetByFileParams struct {
	AppID pgtype.UUID
	File  string
}

func (q *Queries) GetAssetByFile(ctx context.Context, arg GetAssetByFileParams) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetByFile, arg.AppID, arg.File)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.OrganizationID,
		&i.AppID,
		&i.File,
		&i.MediaType,
		&i.Sha256,
		&i.Size,
		&i.Width,
		&i.Height,
		&i.Processing,
		&i.Variants,
		&i.Diagnostics,
		&i.UploadedByKind,
		&i.UploadedByID,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAssetForUpdate = `-- name: GetAssetForUpdate :one
SELECT id, asset_id, organization_id, app_id, file, media_type, sha256, size, width, height, processing, variants, diagnostics, uploaded_by_kind, uploaded_by_id, uploaded_by, created_at, deleted_at FROM assets WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetAssetForUpdate(ctx context.Context, id pgtype.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetForUpdate, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.OrganizationID,
		&i.AppID,
		&i.File,
		&i.MediaType,
		&i.Sha256,
		&i.Size,
		&i.Width,
		&i.Height,
		&i.Processing,
		&i.Variants,
		&i.Diagnostics,
		&i.UploadedByKind,
		&i.UploadedByID,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAssetIncludingDeleted = `-- name: GetAssetIncludingDeleted :one
SELECT id, asset_id, organization_id, app_id, file, media_type, sha256, size, width, height, processing, variants, diagnostics, uploaded_by_kind, uploaded_by_id, uploaded_by, created_at, deleted_at FROM assets WHERE id = $1
`

func (q *Queries) GetAssetIncludingDeleted(ctx context.Context, id pgtype.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetIncludingDeleted, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.OrganizationID,
		&i.AppID,
		&i.File,
		&i.MediaType,
		&i.Sha256,
		&i.Size,
		&i.Width,
		&i.Height,
		&i.Processing,
		&i.Variants,
		&i.Diagnostics,
		&i.UploadedByKind,
		&i.UploadedByID,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertAsset = `-- name: InsertAsset :one
INSERT INTO assets (id, asset_id, organization_id, app_id, file, media_type, sha256, size, width, height, processing,
                    uploaded_by_kind, uploaded_by_id, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, asset_id, organization_id, app_id, file, media_type, sha256, size, width, height, processing, variants, diagnostics, uploaded_by_kind, uploaded_by_id, uploaded_by, created_at, deleted_at
`

type InsertAssetParams struct {
	ID             pgtype.UUID
	AssetID        pgtype.UUID
	OrganizationID pgtype.UUID
	AppID          pgtype.UUID
	File           string
	MediaType      string
	Sha256         []byte
	Size           int64
	Width          int32
	Height         int32
	Processing     string
	UploadedByKind string
	UploadedByID   string
	UploadedBy     string
}

func (q *Queries) InsertAsset(ctx context.Context, arg InsertAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, insertAsset,
		arg.ID,
		arg.AssetID,
		arg.OrganizationID,
		arg.AppID,
		arg.File,
		arg.MediaType,
		arg.Sha256,
		arg.Size,
		arg.Width,
		arg.Height,
		arg.Processing,
		arg.UploadedByKind,
		arg.UploadedByID,
		arg.UploadedBy,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.OrganizationID,
		&i.AppID,
		&i.File,
		&i.MediaType,
		&i.Sha256,
		&i.Size,
		&i.Width,
		&i.Height,
		&i.Processing,
		&i.Variants,
		&i.Diagnostics,
		&i.UploadedByKind,
		&i.UploadedByID,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAllAssets = `-- name: ListAllAssets :many
SELECT id, asset_id, organization_id, app_id, file, media_type, sha256, size, width, height, processing, variants, diagnostics, uploaded_by_kind, uploaded_by_id, uploaded_by, created_at, deleted_at FROM assets WHERE app_id = $1 AND deleted_at IS NULL ORDER BY file
`

func (q *Queries) ListAllAssets(ctx context.Context, appID pgtype.UUID) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAllAssets, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.OrganizationID,
			&i.AppID,
			&i.File,
			&i.MediaType,
			&i.Sha256,
			&i.Size,
			&i.Width,
			&i.Height,
			&i.Processing,
			&i.Variants,
			&i.Diagnostics,
			&i.UploadedByKind,
			&i.UploadedByID,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssets = `-- name: ListAssets :many
SELECT id, asset_id, organization_id, app_id, file, media_type, sha256, size, width, height, processing, variants, diagnostics, uploaded_by_kind, uploaded_by_id, uploaded_by, created_at, deleted_at FROM assets
 WHERE app_id = $1 AND deleted_at IS NULL AND file > $2::text
 ORDER BY file
 LIMIT $3
`

type ListAssetsParams struct {
	AppID     pgtype.UUID
	AfterFile string
	PageSize  int32
}

func (q *Queries) ListAssets(ctx context.Context, arg ListAssetsParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssets, arg.AppID, arg.AfterFile, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.OrganizationID,
			&i.AppID,
			&i.File,
			&i.MediaType,
			&i.Sha256,
			&i.Size,
			&i.Width,
			&i.Height,
			&i.Processing,
			&i.Variants,
			&i.Diagnostics,
			&i.UploadedByKind,
			&i.UploadedByID,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueUncompiledSVGs = `-- name: RequeueUncompiledSVGs :many
UPDATE assets SET processing = 'pending'
 WHERE media_type = 'image/svg+xml' AND processing = 'ready' AND variants = '[]'::jsonb AND deleted_at IS NULL
RETURNING id
`

// Current SVG assets that are ready without their vector_graphics
// variant: uploaded before the server compiled SVGs (CMP-031).
func (q *Queries) RequeueUncompiledSVGs(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, requeueUncompiledSVGs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retireAssetFile = `-- name: RetireAssetFile :execrows
UPDATE assets SET deleted_at = now() WHERE app_id = $1 AND file = $2 AND deleted_at IS NULL
`

type RetireAssetFileParams struct {
	AppID pgtype.UUID
	File  string
}

func (q *Queries) RetireAssetFile(ctx context.Context, arg RetireAssetFileParams) (int64, error) {
	result, err := q.db.Exec(ctx, retireAssetFile, arg.AppID, arg.File)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
