// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccessToken struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	Name           string
	Prefix         string
	SecretHash     []byte
	Scopes         []string
	Source         string
	Subject        string
	CreatedAt      pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
	LastUsedAt     pgtype.Timestamptz
	RevokedAt      pgtype.Timestamptz
}

type App struct {
	ID               pgtype.UUID
	OrganizationID   pgtype.UUID
	Key              string
	Name             string
	DefaultPluginKey string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

type AppAccess struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	AppID          pgtype.UUID
	TeamID         pgtype.UUID
	UserID         pgtype.UUID
	Role           string
	GrantedAt      pgtype.Timestamptz
}

type AuditLog struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Sequence       int64
	OccurredAt     pgtype.Timestamptz
	ActorKind      string
	ActorID        string
	ActorDisplay   string
	Action         string
	TargetKind     string
	TargetID       string
	SourceIp       string
	UserAgent      string
	RequestID      string
	BeforeHash     string
	AfterHash      string
	PreviousHash   string
	EntryHash      string
}

type Channel struct {
	ID              pgtype.UUID
	OrganizationID  pgtype.UUID
	EnvironmentID   pgtype.UUID
	Key             string
	ReleaseSequence int64
	UpdatedAt       pgtype.Timestamptz
}

type DeviceAuthorization struct {
	ID                     pgtype.UUID
	DeviceCode             []byte
	UserCode               string
	Client                 string
	Scopes                 []string
	State                  string
	LastPolledAt           pgtype.Timestamptz
	ApprovedBy             pgtype.UUID
	ApprovedOrganizationID pgtype.UUID
	TokenID                pgtype.UUID
	CreatedAt              pgtype.Timestamptz
	ExpiresAt              pgtype.Timestamptz
}

type Environment struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	AppID          pgtype.UUID
	Key            string
	Name           string
	Production     bool
	SigningKeyRef  string
	CreatedAt      pgtype.Timestamptz
}

type EnvironmentSecret struct {
	OrganizationID pgtype.UUID
	EnvironmentID  pgtype.UUID
	Key            string
	Ciphertext     []byte
	WrappedKey     []byte
	KeyID          string
	Hint           string
	UpdatedBy      pgtype.UUID
	UpdatedAt      pgtype.Timestamptz
}

type EnvironmentVariable struct {
	OrganizationID pgtype.UUID
	EnvironmentID  pgtype.UUID
	Key            string
	Value          string
	UpdatedAt      pgtype.Timestamptz
}

type IdempotencyKey struct {
	Subject     string
	Key         string
	Procedure   string
	RequestHash []byte
	Response    []byte
	State       string
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
}

type InstallationSecret struct {
	Name      string
	Sealed    []byte
	CreatedAt pgtype.Timestamptz
}

type LimitOverride struct {
	OrganizationID pgtype.UUID
	Scope          string
	ScopeID        pgtype.UUID
	LimitKey       string
	Value          int64
	UpdatedAt      pgtype.Timestamptz
}

type Membership struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	TeamID         pgtype.UUID
	Role           string
	AddedAt        pgtype.Timestamptz
}

type MfaChallenge struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	SecretHash []byte
	Attempts   int32
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
}

type MfaFactor struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Kind        string
	Label       string
	Secret      []byte
	LastCounter int64
	ConfirmedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	LastUsedAt  pgtype.Timestamptz
}

// The tenant boundary. Not itself tenant data: a row is the tenant (GOV-001).
type Organization struct {
	ID        pgtype.UUID
	Key       string
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Session struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	SecretHash []byte
	CsrfToken  string
	MfaAt      pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

type Team struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Key            string
	Name           string
	CreatedAt      pgtype.Timestamptz
}

type Trash struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Kind           string
	TargetID       pgtype.UUID
	AppID          pgtype.UUID
	Name           string
	DeletedBy      pgtype.UUID
	DeletedAt      pgtype.Timestamptz
	PurgeAfter     pgtype.Timestamptz
	RestoredAt     pgtype.Timestamptz
}

type User struct {
	ID                  pgtype.UUID
	Email               string
	DisplayName         string
	PasswordHash        string
	InstallationAdmin   bool
	InvitationHash      []byte
	InvitationExpiresAt pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	LastLoginAt         pgtype.Timestamptz
	DisabledAt          pgtype.Timestamptz
}

type WorkloadIdentity struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Issuer         string
	Audience       string
	SubjectPattern string
	Scopes         []string
	CreatedBy      pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}
