// SPDX-FileCopyrightText: 2026 Plux contributors
// SPDX-License-Identifier: Apache-2.0

package plxerr

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strings"
)

// Paths of the published catalogue, relative to the repository root.
const (
	CatalogueMarkdownPath = "docs/reference/errors.md"
	CatalogueJSONPath     = "schema/errors.json"
	CatalogueDartPath     = "packages/plux_flutter/lib/src/errors/codes.g.dart"
)

// RenderMarkdown renders the registry as the published catalogue
// docs/reference/errors.md (DX-003). The output depends only on the registry.
func RenderMarkdown() []byte {
	var b bytes.Buffer
	b.WriteString("<!-- Code generated by backend/internal/plxerr (go generate). DO NOT EDIT. -->\n\n")
	b.WriteString("# Error Code Catalogue\n\n")
	b.WriteString("Every error and diagnostic in Plux has a stable code, a reason that programs can branch on, a default severity, the likely cause and a suggested fix (`DX-003`, [ADR-0018](../adr/0018-unified-error-model.md)). ")
	b.WriteString("Codes are permanent: a retired code stays listed as deprecated and is never reused.\n\n")
	b.WriteString("This page is generated from the registry in `backend/internal/plxerr`; the machine-readable form is `schema/errors.json`.\n")
	defs := Definitions()
	for _, area := range Areas() {
		var inArea []Definition
		for _, d := range defs {
			if d.Code >= area.First && d.Code <= area.Last {
				inArea = append(inArea, d)
			}
		}
		if len(inArea) == 0 {
			continue
		}
		fmt.Fprintf(&b, "\n## %s (%s–%04d)\n", area.Name, area.First, uint16(area.Last))
		for _, d := range inArea {
			fmt.Fprintf(&b, "\n### %s\n\n", d.Code)
			fmt.Fprintf(&b, "`%s` · %s · %s", d.Reason, d.Severity, d.Title)
			if d.Deprecated {
				b.WriteString(" · **deprecated**")
			}
			fmt.Fprintf(&b, "\n\n**Cause.** %s\n\n**Fix.** %s\n", d.Cause, d.Fix)
		}
	}
	return b.Bytes()
}

// catalogue is the JSON form of the registry.
type catalogue struct {
	Areas []catalogueArea `json:"areas"`
	Codes []Definition    `json:"codes"`
}

// catalogueArea is the JSON form of an Area.
type catalogueArea struct {
	Name  string `json:"name"`
	First Code   `json:"first"`
	Last  Code   `json:"last"`
}

// RenderJSON renders the registry as schema/errors.json, the source for the
// Dart and TypeScript error types.
func RenderJSON() ([]byte, error) {
	c := catalogue{Codes: Definitions()}
	for _, a := range Areas() {
		c.Areas = append(c.Areas, catalogueArea(a))
	}
	out, err := json.MarshalIndent(c, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("plxerr.RenderJSON: %w", err)
	}
	return append(out, '\n'), nil
}

// RenderDart renders the registry as the Dart enum the runtime reports
// errors with, so that device and server name every failure with the same
// code and reason (ADR-0018). The output depends only on the registry.
func RenderDart() []byte {
	var b bytes.Buffer
	b.WriteString("// SPDX-FileCopyrightText: 2026 Plux contributors\n// SPDX-License-Identifier: Apache-2.0\n\n")
	b.WriteString("// Code generated by backend/internal/plxerr (go generate). DO NOT EDIT.\n\n")
	b.WriteString("/// The error codes of the Plux error catalogue (ADR-0018,\n/// docs/reference/errors.md).\nlibrary;\n\n")
	b.WriteString("/// A registered error code: the stable `PLX-NNNN` number, its reason and\n/// its title.\nenum PluxErrorCode {\n")
	for _, d := range Definitions() {
		fmt.Fprintf(&b, "  /// %s.\n", d.Title)
		if d.Deprecated {
			b.WriteString("  @Deprecated('retired code, kept so that it is never reused')\n")
		}
		fmt.Fprintf(&b, "  %s(%d, '%s', '%s'),\n\n", dartName(string(d.Reason)), uint16(d.Code), d.Reason, strings.ReplaceAll(d.Title, "'", "\\'"))
	}
	b.Truncate(b.Len() - 3)
	b.WriteString(";\n\n  const PluxErrorCode(this.code, this.reason, this.title);\n\n")
	b.WriteString("  /// The number.\n  final int code;\n\n")
	b.WriteString("  /// The stable UPPER_SNAKE_CASE reason.\n  final String reason;\n\n")
	b.WriteString("  /// The problem in a few words.\n  final String title;\n\n")
	b.WriteString("  /// The code as written in reports, for example `PLX-3011`.\n")
	b.WriteString("  String get id => 'PLX-${code.toString().padLeft(4, '0')}';\n}\n")
	return b.Bytes()
}

// dartName turns an UPPER_SNAKE_CASE reason into a lowerCamelCase name.
func dartName(reason string) string {
	parts := strings.Split(strings.ToLower(reason), "_")
	for i := 1; i < len(parts); i++ {
		if parts[i] != "" {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}
