// SPDX-FileCopyrightText: 2026 Plux contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: plux/v1/app.proto

package pluxv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	pluxv1 "github.com/nightCode42/plux3/backend/internal/pluxv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AppServiceName is the fully-qualified name of the AppService service.
	AppServiceName = "plux.v1.AppService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AppServiceCreateAppProcedure is the fully-qualified name of the AppService's CreateApp RPC.
	AppServiceCreateAppProcedure = "/plux.v1.AppService/CreateApp"
	// AppServiceGetAppProcedure is the fully-qualified name of the AppService's GetApp RPC.
	AppServiceGetAppProcedure = "/plux.v1.AppService/GetApp"
	// AppServiceListAppsProcedure is the fully-qualified name of the AppService's ListApps RPC.
	AppServiceListAppsProcedure = "/plux.v1.AppService/ListApps"
	// AppServiceUpdateAppProcedure is the fully-qualified name of the AppService's UpdateApp RPC.
	AppServiceUpdateAppProcedure = "/plux.v1.AppService/UpdateApp"
	// AppServiceDeleteAppProcedure is the fully-qualified name of the AppService's DeleteApp RPC.
	AppServiceDeleteAppProcedure = "/plux.v1.AppService/DeleteApp"
	// AppServiceCreateEnvironmentProcedure is the fully-qualified name of the AppService's
	// CreateEnvironment RPC.
	AppServiceCreateEnvironmentProcedure = "/plux.v1.AppService/CreateEnvironment"
	// AppServiceListEnvironmentsProcedure is the fully-qualified name of the AppService's
	// ListEnvironments RPC.
	AppServiceListEnvironmentsProcedure = "/plux.v1.AppService/ListEnvironments"
	// AppServiceUpdateEnvironmentProcedure is the fully-qualified name of the AppService's
	// UpdateEnvironment RPC.
	AppServiceUpdateEnvironmentProcedure = "/plux.v1.AppService/UpdateEnvironment"
	// AppServiceDeleteEnvironmentProcedure is the fully-qualified name of the AppService's
	// DeleteEnvironment RPC.
	AppServiceDeleteEnvironmentProcedure = "/plux.v1.AppService/DeleteEnvironment"
	// AppServiceSetVariableProcedure is the fully-qualified name of the AppService's SetVariable RPC.
	AppServiceSetVariableProcedure = "/plux.v1.AppService/SetVariable"
	// AppServiceListVariablesProcedure is the fully-qualified name of the AppService's ListVariables
	// RPC.
	AppServiceListVariablesProcedure = "/plux.v1.AppService/ListVariables"
	// AppServiceSetSecretProcedure is the fully-qualified name of the AppService's SetSecret RPC.
	AppServiceSetSecretProcedure = "/plux.v1.AppService/SetSecret"
	// AppServiceListSecretsProcedure is the fully-qualified name of the AppService's ListSecrets RPC.
	AppServiceListSecretsProcedure = "/plux.v1.AppService/ListSecrets"
	// AppServiceDeleteSecretProcedure is the fully-qualified name of the AppService's DeleteSecret RPC.
	AppServiceDeleteSecretProcedure = "/plux.v1.AppService/DeleteSecret"
	// AppServiceCreateChannelProcedure is the fully-qualified name of the AppService's CreateChannel
	// RPC.
	AppServiceCreateChannelProcedure = "/plux.v1.AppService/CreateChannel"
	// AppServiceListChannelsProcedure is the fully-qualified name of the AppService's ListChannels RPC.
	AppServiceListChannelsProcedure = "/plux.v1.AppService/ListChannels"
	// AppServiceDeleteChannelProcedure is the fully-qualified name of the AppService's DeleteChannel
	// RPC.
	AppServiceDeleteChannelProcedure = "/plux.v1.AppService/DeleteChannel"
	// AppServiceListTrashProcedure is the fully-qualified name of the AppService's ListTrash RPC.
	AppServiceListTrashProcedure = "/plux.v1.AppService/ListTrash"
	// AppServiceRestoreFromTrashProcedure is the fully-qualified name of the AppService's
	// RestoreFromTrash RPC.
	AppServiceRestoreFromTrashProcedure = "/plux.v1.AppService/RestoreFromTrash"
	// AppServicePurgeFromTrashProcedure is the fully-qualified name of the AppService's PurgeFromTrash
	// RPC.
	AppServicePurgeFromTrashProcedure = "/plux.v1.AppService/PurgeFromTrash"
	// AppServiceListAppLimitsProcedure is the fully-qualified name of the AppService's ListAppLimits
	// RPC.
	AppServiceListAppLimitsProcedure = "/plux.v1.AppService/ListAppLimits"
	// AppServiceSetAppLimitProcedure is the fully-qualified name of the AppService's SetAppLimit RPC.
	AppServiceSetAppLimitProcedure = "/plux.v1.AppService/SetAppLimit"
)

// AppServiceClient is a client for the plux.v1.AppService service.
type AppServiceClient interface {
	CreateApp(context.Context, *connect.Request[pluxv1.CreateAppRequest]) (*connect.Response[pluxv1.CreateAppResponse], error)
	GetApp(context.Context, *connect.Request[pluxv1.GetAppRequest]) (*connect.Response[pluxv1.GetAppResponse], error)
	ListApps(context.Context, *connect.Request[pluxv1.ListAppsRequest]) (*connect.Response[pluxv1.ListAppsResponse], error)
	UpdateApp(context.Context, *connect.Request[pluxv1.UpdateAppRequest]) (*connect.Response[pluxv1.UpdateAppResponse], error)
	DeleteApp(context.Context, *connect.Request[pluxv1.DeleteAppRequest]) (*connect.Response[pluxv1.DeleteAppResponse], error)
	CreateEnvironment(context.Context, *connect.Request[pluxv1.CreateEnvironmentRequest]) (*connect.Response[pluxv1.CreateEnvironmentResponse], error)
	ListEnvironments(context.Context, *connect.Request[pluxv1.ListEnvironmentsRequest]) (*connect.Response[pluxv1.ListEnvironmentsResponse], error)
	UpdateEnvironment(context.Context, *connect.Request[pluxv1.UpdateEnvironmentRequest]) (*connect.Response[pluxv1.UpdateEnvironmentResponse], error)
	DeleteEnvironment(context.Context, *connect.Request[pluxv1.DeleteEnvironmentRequest]) (*connect.Response[pluxv1.DeleteEnvironmentResponse], error)
	SetVariable(context.Context, *connect.Request[pluxv1.SetVariableRequest]) (*connect.Response[pluxv1.SetVariableResponse], error)
	ListVariables(context.Context, *connect.Request[pluxv1.ListVariablesRequest]) (*connect.Response[pluxv1.ListVariablesResponse], error)
	// SetSecret stores a secret with envelope encryption under the KMS key.
	// A secret's value is never returned after creation (SEC-106).
	SetSecret(context.Context, *connect.Request[pluxv1.SetSecretRequest]) (*connect.Response[pluxv1.SetSecretResponse], error)
	ListSecrets(context.Context, *connect.Request[pluxv1.ListSecretsRequest]) (*connect.Response[pluxv1.ListSecretsResponse], error)
	DeleteSecret(context.Context, *connect.Request[pluxv1.DeleteSecretRequest]) (*connect.Response[pluxv1.DeleteSecretResponse], error)
	CreateChannel(context.Context, *connect.Request[pluxv1.CreateChannelRequest]) (*connect.Response[pluxv1.CreateChannelResponse], error)
	ListChannels(context.Context, *connect.Request[pluxv1.ListChannelsRequest]) (*connect.Response[pluxv1.ListChannelsResponse], error)
	DeleteChannel(context.Context, *connect.Request[pluxv1.DeleteChannelRequest]) (*connect.Response[pluxv1.DeleteChannelResponse], error)
	ListTrash(context.Context, *connect.Request[pluxv1.ListTrashRequest]) (*connect.Response[pluxv1.ListTrashResponse], error)
	RestoreFromTrash(context.Context, *connect.Request[pluxv1.RestoreFromTrashRequest]) (*connect.Response[pluxv1.RestoreFromTrashResponse], error)
	PurgeFromTrash(context.Context, *connect.Request[pluxv1.PurgeFromTrashRequest]) (*connect.Response[pluxv1.PurgeFromTrashResponse], error)
	ListAppLimits(context.Context, *connect.Request[pluxv1.ListAppLimitsRequest]) (*connect.Response[pluxv1.ListAppLimitsResponse], error)
	SetAppLimit(context.Context, *connect.Request[pluxv1.SetAppLimitRequest]) (*connect.Response[pluxv1.SetAppLimitResponse], error)
}

// NewAppServiceClient constructs a client for the plux.v1.AppService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAppServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AppServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	appServiceMethods := pluxv1.File_plux_v1_app_proto.Services().ByName("AppService").Methods()
	return &appServiceClient{
		createApp: connect.NewClient[pluxv1.CreateAppRequest, pluxv1.CreateAppResponse](
			httpClient,
			baseURL+AppServiceCreateAppProcedure,
			connect.WithSchema(appServiceMethods.ByName("CreateApp")),
			connect.WithClientOptions(opts...),
		),
		getApp: connect.NewClient[pluxv1.GetAppRequest, pluxv1.GetAppResponse](
			httpClient,
			baseURL+AppServiceGetAppProcedure,
			connect.WithSchema(appServiceMethods.ByName("GetApp")),
			connect.WithClientOptions(opts...),
		),
		listApps: connect.NewClient[pluxv1.ListAppsRequest, pluxv1.ListAppsResponse](
			httpClient,
			baseURL+AppServiceListAppsProcedure,
			connect.WithSchema(appServiceMethods.ByName("ListApps")),
			connect.WithClientOptions(opts...),
		),
		updateApp: connect.NewClient[pluxv1.UpdateAppRequest, pluxv1.UpdateAppResponse](
			httpClient,
			baseURL+AppServiceUpdateAppProcedure,
			connect.WithSchema(appServiceMethods.ByName("UpdateApp")),
			connect.WithClientOptions(opts...),
		),
		deleteApp: connect.NewClient[pluxv1.DeleteAppRequest, pluxv1.DeleteAppResponse](
			httpClient,
			baseURL+AppServiceDeleteAppProcedure,
			connect.WithSchema(appServiceMethods.ByName("DeleteApp")),
			connect.WithClientOptions(opts...),
		),
		createEnvironment: connect.NewClient[pluxv1.CreateEnvironmentRequest, pluxv1.CreateEnvironmentResponse](
			httpClient,
			baseURL+AppServiceCreateEnvironmentProcedure,
			connect.WithSchema(appServiceMethods.ByName("CreateEnvironment")),
			connect.WithClientOptions(opts...),
		),
		listEnvironments: connect.NewClient[pluxv1.ListEnvironmentsRequest, pluxv1.ListEnvironmentsResponse](
			httpClient,
			baseURL+AppServiceListEnvironmentsProcedure,
			connect.WithSchema(appServiceMethods.ByName("ListEnvironments")),
			connect.WithClientOptions(opts...),
		),
		updateEnvironment: connect.NewClient[pluxv1.UpdateEnvironmentRequest, pluxv1.UpdateEnvironmentResponse](
			httpClient,
			baseURL+AppServiceUpdateEnvironmentProcedure,
			connect.WithSchema(appServiceMethods.ByName("UpdateEnvironment")),
			connect.WithClientOptions(opts...),
		),
		deleteEnvironment: connect.NewClient[pluxv1.DeleteEnvironmentRequest, pluxv1.DeleteEnvironmentResponse](
			httpClient,
			baseURL+AppServiceDeleteEnvironmentProcedure,
			connect.WithSchema(appServiceMethods.ByName("DeleteEnvironment")),
			connect.WithClientOptions(opts...),
		),
		setVariable: connect.NewClient[pluxv1.SetVariableRequest, pluxv1.SetVariableResponse](
			httpClient,
			baseURL+AppServiceSetVariableProcedure,
			connect.WithSchema(appServiceMethods.ByName("SetVariable")),
			connect.WithClientOptions(opts...),
		),
		listVariables: connect.NewClient[pluxv1.ListVariablesRequest, pluxv1.ListVariablesResponse](
			httpClient,
			baseURL+AppServiceListVariablesProcedure,
			connect.WithSchema(appServiceMethods.ByName("ListVariables")),
			connect.WithClientOptions(opts...),
		),
		setSecret: connect.NewClient[pluxv1.SetSecretRequest, pluxv1.SetSecretResponse](
			httpClient,
			baseURL+AppServiceSetSecretProcedure,
			connect.WithSchema(appServiceMethods.ByName("SetSecret")),
			connect.WithClientOptions(opts...),
		),
		listSecrets: connect.NewClient[pluxv1.ListSecretsRequest, pluxv1.ListSecretsResponse](
			httpClient,
			baseURL+AppServiceListSecretsProcedure,
			connect.WithSchema(appServiceMethods.ByName("ListSecrets")),
			connect.WithClientOptions(opts...),
		),
		deleteSecret: connect.NewClient[pluxv1.DeleteSecretRequest, pluxv1.DeleteSecretResponse](
			httpClient,
			baseURL+AppServiceDeleteSecretProcedure,
			connect.WithSchema(appServiceMethods.ByName("DeleteSecret")),
			connect.WithClientOptions(opts...),
		),
		createChannel: connect.NewClient[pluxv1.CreateChannelRequest, pluxv1.CreateChannelResponse](
			httpClient,
			baseURL+AppServiceCreateChannelProcedure,
			connect.WithSchema(appServiceMethods.ByName("CreateChannel")),
			connect.WithClientOptions(opts...),
		),
		listChannels: connect.NewClient[pluxv1.ListChannelsRequest, pluxv1.ListChannelsResponse](
			httpClient,
			baseURL+AppServiceListChannelsProcedure,
			connect.WithSchema(appServiceMethods.ByName("ListChannels")),
			connect.WithClientOptions(opts...),
		),
		deleteChannel: connect.NewClient[pluxv1.DeleteChannelRequest, pluxv1.DeleteChannelResponse](
			httpClient,
			baseURL+AppServiceDeleteChannelProcedure,
			connect.WithSchema(appServiceMethods.ByName("DeleteChannel")),
			connect.WithClientOptions(opts...),
		),
		listTrash: connect.NewClient[pluxv1.ListTrashRequest, pluxv1.ListTrashResponse](
			httpClient,
			baseURL+AppServiceListTrashProcedure,
			connect.WithSchema(appServiceMethods.ByName("ListTrash")),
			connect.WithClientOptions(opts...),
		),
		restoreFromTrash: connect.NewClient[pluxv1.RestoreFromTrashRequest, pluxv1.RestoreFromTrashResponse](
			httpClient,
			baseURL+AppServiceRestoreFromTrashProcedure,
			connect.WithSchema(appServiceMethods.ByName("RestoreFromTrash")),
			connect.WithClientOptions(opts...),
		),
		purgeFromTrash: connect.NewClient[pluxv1.PurgeFromTrashRequest, pluxv1.PurgeFromTrashResponse](
			httpClient,
			baseURL+AppServicePurgeFromTrashProcedure,
			connect.WithSchema(appServiceMethods.ByName("PurgeFromTrash")),
			connect.WithClientOptions(opts...),
		),
		listAppLimits: connect.NewClient[pluxv1.ListAppLimitsRequest, pluxv1.ListAppLimitsResponse](
			httpClient,
			baseURL+AppServiceListAppLimitsProcedure,
			connect.WithSchema(appServiceMethods.ByName("ListAppLimits")),
			connect.WithClientOptions(opts...),
		),
		setAppLimit: connect.NewClient[pluxv1.SetAppLimitRequest, pluxv1.SetAppLimitResponse](
			httpClient,
			baseURL+AppServiceSetAppLimitProcedure,
			connect.WithSchema(appServiceMethods.ByName("SetAppLimit")),
			connect.WithClientOptions(opts...),
		),
	}
}

// appServiceClient implements AppServiceClient.
type appServiceClient struct {
	createApp         *connect.Client[pluxv1.CreateAppRequest, pluxv1.CreateAppResponse]
	getApp            *connect.Client[pluxv1.GetAppRequest, pluxv1.GetAppResponse]
	listApps          *connect.Client[pluxv1.ListAppsRequest, pluxv1.ListAppsResponse]
	updateApp         *connect.Client[pluxv1.UpdateAppRequest, pluxv1.UpdateAppResponse]
	deleteApp         *connect.Client[pluxv1.DeleteAppRequest, pluxv1.DeleteAppResponse]
	createEnvironment *connect.Client[pluxv1.CreateEnvironmentRequest, pluxv1.CreateEnvironmentResponse]
	listEnvironments  *connect.Client[pluxv1.ListEnvironmentsRequest, pluxv1.ListEnvironmentsResponse]
	updateEnvironment *connect.Client[pluxv1.UpdateEnvironmentRequest, pluxv1.UpdateEnvironmentResponse]
	deleteEnvironment *connect.Client[pluxv1.DeleteEnvironmentRequest, pluxv1.DeleteEnvironmentResponse]
	setVariable       *connect.Client[pluxv1.SetVariableRequest, pluxv1.SetVariableResponse]
	listVariables     *connect.Client[pluxv1.ListVariablesRequest, pluxv1.ListVariablesResponse]
	setSecret         *connect.Client[pluxv1.SetSecretRequest, pluxv1.SetSecretResponse]
	listSecrets       *connect.Client[pluxv1.ListSecretsRequest, pluxv1.ListSecretsResponse]
	deleteSecret      *connect.Client[pluxv1.DeleteSecretRequest, pluxv1.DeleteSecretResponse]
	createChannel     *connect.Client[pluxv1.CreateChannelRequest, pluxv1.CreateChannelResponse]
	listChannels      *connect.Client[pluxv1.ListChannelsRequest, pluxv1.ListChannelsResponse]
	deleteChannel     *connect.Client[pluxv1.DeleteChannelRequest, pluxv1.DeleteChannelResponse]
	listTrash         *connect.Client[pluxv1.ListTrashRequest, pluxv1.ListTrashResponse]
	restoreFromTrash  *connect.Client[pluxv1.RestoreFromTrashRequest, pluxv1.RestoreFromTrashResponse]
	purgeFromTrash    *connect.Client[pluxv1.PurgeFromTrashRequest, pluxv1.PurgeFromTrashResponse]
	listAppLimits     *connect.Client[pluxv1.ListAppLimitsRequest, pluxv1.ListAppLimitsResponse]
	setAppLimit       *connect.Client[pluxv1.SetAppLimitRequest, pluxv1.SetAppLimitResponse]
}

// CreateApp calls plux.v1.AppService.CreateApp.
func (c *appServiceClient) CreateApp(ctx context.Context, req *connect.Request[pluxv1.CreateAppRequest]) (*connect.Response[pluxv1.CreateAppResponse], error) {
	return c.createApp.CallUnary(ctx, req)
}

// GetApp calls plux.v1.AppService.GetApp.
func (c *appServiceClient) GetApp(ctx context.Context, req *connect.Request[pluxv1.GetAppRequest]) (*connect.Response[pluxv1.GetAppResponse], error) {
	return c.getApp.CallUnary(ctx, req)
}

// ListApps calls plux.v1.AppService.ListApps.
func (c *appServiceClient) ListApps(ctx context.Context, req *connect.Request[pluxv1.ListAppsRequest]) (*connect.Response[pluxv1.ListAppsResponse], error) {
	return c.listApps.CallUnary(ctx, req)
}

// UpdateApp calls plux.v1.AppService.UpdateApp.
func (c *appServiceClient) UpdateApp(ctx context.Context, req *connect.Request[pluxv1.UpdateAppRequest]) (*connect.Response[pluxv1.UpdateAppResponse], error) {
	return c.updateApp.CallUnary(ctx, req)
}

// DeleteApp calls plux.v1.AppService.DeleteApp.
func (c *appServiceClient) DeleteApp(ctx context.Context, req *connect.Request[pluxv1.DeleteAppRequest]) (*connect.Response[pluxv1.DeleteAppResponse], error) {
	return c.deleteApp.CallUnary(ctx, req)
}

// CreateEnvironment calls plux.v1.AppService.CreateEnvironment.
func (c *appServiceClient) CreateEnvironment(ctx context.Context, req *connect.Request[pluxv1.CreateEnvironmentRequest]) (*connect.Response[pluxv1.CreateEnvironmentResponse], error) {
	return c.createEnvironment.CallUnary(ctx, req)
}

// ListEnvironments calls plux.v1.AppService.ListEnvironments.
func (c *appServiceClient) ListEnvironments(ctx context.Context, req *connect.Request[pluxv1.ListEnvironmentsRequest]) (*connect.Response[pluxv1.ListEnvironmentsResponse], error) {
	return c.listEnvironments.CallUnary(ctx, req)
}

// UpdateEnvironment calls plux.v1.AppService.UpdateEnvironment.
func (c *appServiceClient) UpdateEnvironment(ctx context.Context, req *connect.Request[pluxv1.UpdateEnvironmentRequest]) (*connect.Response[pluxv1.UpdateEnvironmentResponse], error) {
	return c.updateEnvironment.CallUnary(ctx, req)
}

// DeleteEnvironment calls plux.v1.AppService.DeleteEnvironment.
func (c *appServiceClient) DeleteEnvironment(ctx context.Context, req *connect.Request[pluxv1.DeleteEnvironmentRequest]) (*connect.Response[pluxv1.DeleteEnvironmentResponse], error) {
	return c.deleteEnvironment.CallUnary(ctx, req)
}

// SetVariable calls plux.v1.AppService.SetVariable.
func (c *appServiceClient) SetVariable(ctx context.Context, req *connect.Request[pluxv1.SetVariableRequest]) (*connect.Response[pluxv1.SetVariableResponse], error) {
	return c.setVariable.CallUnary(ctx, req)
}

// ListVariables calls plux.v1.AppService.ListVariables.
func (c *appServiceClient) ListVariables(ctx context.Context, req *connect.Request[pluxv1.ListVariablesRequest]) (*connect.Response[pluxv1.ListVariablesResponse], error) {
	return c.listVariables.CallUnary(ctx, req)
}

// SetSecret calls plux.v1.AppService.SetSecret.
func (c *appServiceClient) SetSecret(ctx context.Context, req *connect.Request[pluxv1.SetSecretRequest]) (*connect.Response[pluxv1.SetSecretResponse], error) {
	return c.setSecret.CallUnary(ctx, req)
}

// ListSecrets calls plux.v1.AppService.ListSecrets.
func (c *appServiceClient) ListSecrets(ctx context.Context, req *connect.Request[pluxv1.ListSecretsRequest]) (*connect.Response[pluxv1.ListSecretsResponse], error) {
	return c.listSecrets.CallUnary(ctx, req)
}

// DeleteSecret calls plux.v1.AppService.DeleteSecret.
func (c *appServiceClient) DeleteSecret(ctx context.Context, req *connect.Request[pluxv1.DeleteSecretRequest]) (*connect.Response[pluxv1.DeleteSecretResponse], error) {
	return c.deleteSecret.CallUnary(ctx, req)
}

// CreateChannel calls plux.v1.AppService.CreateChannel.
func (c *appServiceClient) CreateChannel(ctx context.Context, req *connect.Request[pluxv1.CreateChannelRequest]) (*connect.Response[pluxv1.CreateChannelResponse], error) {
	return c.createChannel.CallUnary(ctx, req)
}

// ListChannels calls plux.v1.AppService.ListChannels.
func (c *appServiceClient) ListChannels(ctx context.Context, req *connect.Request[pluxv1.ListChannelsRequest]) (*connect.Response[pluxv1.ListChannelsResponse], error) {
	return c.listChannels.CallUnary(ctx, req)
}

// DeleteChannel calls plux.v1.AppService.DeleteChannel.
func (c *appServiceClient) DeleteChannel(ctx context.Context, req *connect.Request[pluxv1.DeleteChannelRequest]) (*connect.Response[pluxv1.DeleteChannelResponse], error) {
	return c.deleteChannel.CallUnary(ctx, req)
}

// ListTrash calls plux.v1.AppService.ListTrash.
func (c *appServiceClient) ListTrash(ctx context.Context, req *connect.Request[pluxv1.ListTrashRequest]) (*connect.Response[pluxv1.ListTrashResponse], error) {
	return c.listTrash.CallUnary(ctx, req)
}

// RestoreFromTrash calls plux.v1.AppService.RestoreFromTrash.
func (c *appServiceClient) RestoreFromTrash(ctx context.Context, req *connect.Request[pluxv1.RestoreFromTrashRequest]) (*connect.Response[pluxv1.RestoreFromTrashResponse], error) {
	return c.restoreFromTrash.CallUnary(ctx, req)
}

// PurgeFromTrash calls plux.v1.AppService.PurgeFromTrash.
func (c *appServiceClient) PurgeFromTrash(ctx context.Context, req *connect.Request[pluxv1.PurgeFromTrashRequest]) (*connect.Response[pluxv1.PurgeFromTrashResponse], error) {
	return c.purgeFromTrash.CallUnary(ctx, req)
}

// ListAppLimits calls plux.v1.AppService.ListAppLimits.
func (c *appServiceClient) ListAppLimits(ctx context.Context, req *connect.Request[pluxv1.ListAppLimitsRequest]) (*connect.Response[pluxv1.ListAppLimitsResponse], error) {
	return c.listAppLimits.CallUnary(ctx, req)
}

// SetAppLimit calls plux.v1.AppService.SetAppLimit.
func (c *appServiceClient) SetAppLimit(ctx context.Context, req *connect.Request[pluxv1.SetAppLimitRequest]) (*connect.Response[pluxv1.SetAppLimitResponse], error) {
	return c.setAppLimit.CallUnary(ctx, req)
}

// AppServiceHandler is an implementation of the plux.v1.AppService service.
type AppServiceHandler interface {
	CreateApp(context.Context, *connect.Request[pluxv1.CreateAppRequest]) (*connect.Response[pluxv1.CreateAppResponse], error)
	GetApp(context.Context, *connect.Request[pluxv1.GetAppRequest]) (*connect.Response[pluxv1.GetAppResponse], error)
	ListApps(context.Context, *connect.Request[pluxv1.ListAppsRequest]) (*connect.Response[pluxv1.ListAppsResponse], error)
	UpdateApp(context.Context, *connect.Request[pluxv1.UpdateAppRequest]) (*connect.Response[pluxv1.UpdateAppResponse], error)
	DeleteApp(context.Context, *connect.Request[pluxv1.DeleteAppRequest]) (*connect.Response[pluxv1.DeleteAppResponse], error)
	CreateEnvironment(context.Context, *connect.Request[pluxv1.CreateEnvironmentRequest]) (*connect.Response[pluxv1.CreateEnvironmentResponse], error)
	ListEnvironments(context.Context, *connect.Request[pluxv1.ListEnvironmentsRequest]) (*connect.Response[pluxv1.ListEnvironmentsResponse], error)
	UpdateEnvironment(context.Context, *connect.Request[pluxv1.UpdateEnvironmentRequest]) (*connect.Response[pluxv1.UpdateEnvironmentResponse], error)
	DeleteEnvironment(context.Context, *connect.Request[pluxv1.DeleteEnvironmentRequest]) (*connect.Response[pluxv1.DeleteEnvironmentResponse], error)
	SetVariable(context.Context, *connect.Request[pluxv1.SetVariableRequest]) (*connect.Response[pluxv1.SetVariableResponse], error)
	ListVariables(context.Context, *connect.Request[pluxv1.ListVariablesRequest]) (*connect.Response[pluxv1.ListVariablesResponse], error)
	// SetSecret stores a secret with envelope encryption under the KMS key.
	// A secret's value is never returned after creation (SEC-106).
	SetSecret(context.Context, *connect.Request[pluxv1.SetSecretRequest]) (*connect.Response[pluxv1.SetSecretResponse], error)
	ListSecrets(context.Context, *connect.Request[pluxv1.ListSecretsRequest]) (*connect.Response[pluxv1.ListSecretsResponse], error)
	DeleteSecret(context.Context, *connect.Request[pluxv1.DeleteSecretRequest]) (*connect.Response[pluxv1.DeleteSecretResponse], error)
	CreateChannel(context.Context, *connect.Request[pluxv1.CreateChannelRequest]) (*connect.Response[pluxv1.CreateChannelResponse], error)
	ListChannels(context.Context, *connect.Request[pluxv1.ListChannelsRequest]) (*connect.Response[pluxv1.ListChannelsResponse], error)
	DeleteChannel(context.Context, *connect.Request[pluxv1.DeleteChannelRequest]) (*connect.Response[pluxv1.DeleteChannelResponse], error)
	ListTrash(context.Context, *connect.Request[pluxv1.ListTrashRequest]) (*connect.Response[pluxv1.ListTrashResponse], error)
	RestoreFromTrash(context.Context, *connect.Request[pluxv1.RestoreFromTrashRequest]) (*connect.Response[pluxv1.RestoreFromTrashResponse], error)
	PurgeFromTrash(context.Context, *connect.Request[pluxv1.PurgeFromTrashRequest]) (*connect.Response[pluxv1.PurgeFromTrashResponse], error)
	ListAppLimits(context.Context, *connect.Request[pluxv1.ListAppLimitsRequest]) (*connect.Response[pluxv1.ListAppLimitsResponse], error)
	SetAppLimit(context.Context, *connect.Request[pluxv1.SetAppLimitRequest]) (*connect.Response[pluxv1.SetAppLimitResponse], error)
}

// NewAppServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAppServiceHandler(svc AppServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	appServiceMethods := pluxv1.File_plux_v1_app_proto.Services().ByName("AppService").Methods()
	appServiceCreateAppHandler := connect.NewUnaryHandler(
		AppServiceCreateAppProcedure,
		svc.CreateApp,
		connect.WithSchema(appServiceMethods.ByName("CreateApp")),
		connect.WithHandlerOptions(opts...),
	)
	appServiceGetAppHandler := connect.NewUnaryHandler(
		AppServiceGetAppProcedure,
		svc.GetApp,
		connect.WithSchema(appServiceMethods.ByName("GetApp")),
		connect.WithHandlerOptions(opts...),
	)
	appServiceListAppsHandler := connect.NewUnaryHandler(
		AppServiceListAppsProcedure,
		svc.ListApps,
		connect.WithSchema(appServiceMethods.ByName("ListApps")),
		connect.WithHandlerOptions(opts...),
	)
	appServiceUpdateAppHandler := connect.NewUnaryHandler(
		AppServiceUpdateAppProcedure,
		svc.UpdateApp,
		connect.WithSchema(appServiceMethods.ByName("UpdateApp")),
		connect.WithHandlerOptions(opts...),
	)
	appServiceDeleteAppHandler := connect.NewUnaryHandler(
		AppServiceDeleteAppProcedure,
		svc.DeleteApp,
		connect.WithSchema(appServiceMethods.ByName("DeleteApp")),
		connect.WithHandlerOptions(opts...),
	)
	appServiceCreateEnvironmentHandler := connect.NewUnaryHandler(
		AppServiceCreateEnvironmentProcedure,
		svc.CreateEnvironment,
		connect.WithSchema(appServiceMethods.ByName("CreateEnvironment")),
		connect.WithHandlerOptions(opts...),
	)
	appServiceListEnvironmentsHandler := connect.NewUnaryHandler(
		AppServiceListEnvironmentsProcedure,
		svc.ListEnvironments,
		connect.WithSchema(appServiceMethods.ByName("ListEnvironments")),
		connect.WithHandlerOptions(opts...),
	)
	appServiceUpdateEnvironmentHandler := connect.NewUnaryHandler(
		AppServiceUpdateEnvironmentProcedure,
		svc.UpdateEnvironment,
		connect.WithSchema(appServiceMethods.ByName("UpdateEnvironment")),
		connect.WithHandlerOptions(opts...),
	)
	appServiceDeleteEnvironmentHandler := connect.NewUnaryHandler(
		AppServiceDeleteEnvironmentProcedure,
		svc.DeleteEnvironment,
		connect.WithSchema(appServiceMethods.ByName("DeleteEnvironment")),
		connect.WithHandlerOptions(opts...),
	)
	appServiceSetVariableHandler := connect.NewUnaryHandler(
		AppServiceSetVariableProcedure,
		svc.SetVariable,
		connect.WithSchema(appServiceMethods.ByName("SetVariable")),
		connect.WithHandlerOptions(opts...),
	)
	appServiceListVariablesHandler := connect.NewUnaryHandler(
		AppServiceListVariablesProcedure,
		svc.ListVariables,
		connect.WithSchema(appServiceMethods.ByName("ListVariables")),
		connect.WithHandlerOptions(opts...),
	)
	appServiceSetSecretHandler := connect.NewUnaryHandler(
		AppServiceSetSecretProcedure,
		svc.SetSecret,
		connect.WithSchema(appServiceMethods.ByName("SetSecret")),
		connect.WithHandlerOptions(opts...),
	)
	appServiceListSecretsHandler := connect.NewUnaryHandler(
		AppServiceListSecretsProcedure,
		svc.ListSecrets,
		connect.WithSchema(appServiceMethods.ByName("ListSecrets")),
		connect.WithHandlerOptions(opts...),
	)
	appServiceDeleteSecretHandler := connect.NewUnaryHandler(
		AppServiceDeleteSecretProcedure,
		svc.DeleteSecret,
		connect.WithSchema(appServiceMethods.ByName("DeleteSecret")),
		connect.WithHandlerOptions(opts...),
	)
	appServiceCreateChannelHandler := connect.NewUnaryHandler(
		AppServiceCreateChannelProcedure,
		svc.CreateChannel,
		connect.WithSchema(appServiceMethods.ByName("CreateChannel")),
		connect.WithHandlerOptions(opts...),
	)
	appServiceListChannelsHandler := connect.NewUnaryHandler(
		AppServiceListChannelsProcedure,
		svc.ListChannels,
		connect.WithSchema(appServiceMethods.ByName("ListChannels")),
		connect.WithHandlerOptions(opts...),
	)
	appServiceDeleteChannelHandler := connect.NewUnaryHandler(
		AppServiceDeleteChannelProcedure,
		svc.DeleteChannel,
		connect.WithSchema(appServiceMethods.ByName("DeleteChannel")),
		connect.WithHandlerOptions(opts...),
	)
	appServiceListTrashHandler := connect.NewUnaryHandler(
		AppServiceListTrashProcedure,
		svc.ListTrash,
		connect.WithSchema(appServiceMethods.ByName("ListTrash")),
		connect.WithHandlerOptions(opts...),
	)
	appServiceRestoreFromTrashHandler := connect.NewUnaryHandler(
		AppServiceRestoreFromTrashProcedure,
		svc.RestoreFromTrash,
		connect.WithSchema(appServiceMethods.ByName("RestoreFromTrash")),
		connect.WithHandlerOptions(opts...),
	)
	appServicePurgeFromTrashHandler := connect.NewUnaryHandler(
		AppServicePurgeFromTrashProcedure,
		svc.PurgeFromTrash,
		connect.WithSchema(appServiceMethods.ByName("PurgeFromTrash")),
		connect.WithHandlerOptions(opts...),
	)
	appServiceListAppLimitsHandler := connect.NewUnaryHandler(
		AppServiceListAppLimitsProcedure,
		svc.ListAppLimits,
		connect.WithSchema(appServiceMethods.ByName("ListAppLimits")),
		connect.WithHandlerOptions(opts...),
	)
	appServiceSetAppLimitHandler := connect.NewUnaryHandler(
		AppServiceSetAppLimitProcedure,
		svc.SetAppLimit,
		connect.WithSchema(appServiceMethods.ByName("SetAppLimit")),
		connect.WithHandlerOptions(opts...),
	)
	return "/plux.v1.AppService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AppServiceCreateAppProcedure:
			appServiceCreateAppHandler.ServeHTTP(w, r)
		case AppServiceGetAppProcedure:
			appServiceGetAppHandler.ServeHTTP(w, r)
		case AppServiceListAppsProcedure:
			appServiceListAppsHandler.ServeHTTP(w, r)
		case AppServiceUpdateAppProcedure:
			appServiceUpdateAppHandler.ServeHTTP(w, r)
		case AppServiceDeleteAppProcedure:
			appServiceDeleteAppHandler.ServeHTTP(w, r)
		case AppServiceCreateEnvironmentProcedure:
			appServiceCreateEnvironmentHandler.ServeHTTP(w, r)
		case AppServiceListEnvironmentsProcedure:
			appServiceListEnvironmentsHandler.ServeHTTP(w, r)
		case AppServiceUpdateEnvironmentProcedure:
			appServiceUpdateEnvironmentHandler.ServeHTTP(w, r)
		case AppServiceDeleteEnvironmentProcedure:
			appServiceDeleteEnvironmentHandler.ServeHTTP(w, r)
		case AppServiceSetVariableProcedure:
			appServiceSetVariableHandler.ServeHTTP(w, r)
		case AppServiceListVariablesProcedure:
			appServiceListVariablesHandler.ServeHTTP(w, r)
		case AppServiceSetSecretProcedure:
			appServiceSetSecretHandler.ServeHTTP(w, r)
		case AppServiceListSecretsProcedure:
			appServiceListSecretsHandler.ServeHTTP(w, r)
		case AppServiceDeleteSecretProcedure:
			appServiceDeleteSecretHandler.ServeHTTP(w, r)
		case AppServiceCreateChannelProcedure:
			appServiceCreateChannelHandler.ServeHTTP(w, r)
		case AppServiceListChannelsProcedure:
			appServiceListChannelsHandler.ServeHTTP(w, r)
		case AppServiceDeleteChannelProcedure:
			appServiceDeleteChannelHandler.ServeHTTP(w, r)
		case AppServiceListTrashProcedure:
			appServiceListTrashHandler.ServeHTTP(w, r)
		case AppServiceRestoreFromTrashProcedure:
			appServiceRestoreFromTrashHandler.ServeHTTP(w, r)
		case AppServicePurgeFromTrashProcedure:
			appServicePurgeFromTrashHandler.ServeHTTP(w, r)
		case AppServiceListAppLimitsProcedure:
			appServiceListAppLimitsHandler.ServeHTTP(w, r)
		case AppServiceSetAppLimitProcedure:
			appServiceSetAppLimitHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAppServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAppServiceHandler struct{}

func (UnimplementedAppServiceHandler) CreateApp(context.Context, *connect.Request[pluxv1.CreateAppRequest]) (*connect.Response[pluxv1.CreateAppResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.AppService.CreateApp is not implemented"))
}

func (UnimplementedAppServiceHandler) GetApp(context.Context, *connect.Request[pluxv1.GetAppRequest]) (*connect.Response[pluxv1.GetAppResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.AppService.GetApp is not implemented"))
}

func (UnimplementedAppServiceHandler) ListApps(context.Context, *connect.Request[pluxv1.ListAppsRequest]) (*connect.Response[pluxv1.ListAppsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.AppService.ListApps is not implemented"))
}

func (UnimplementedAppServiceHandler) UpdateApp(context.Context, *connect.Request[pluxv1.UpdateAppRequest]) (*connect.Response[pluxv1.UpdateAppResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.AppService.UpdateApp is not implemented"))
}

func (UnimplementedAppServiceHandler) DeleteApp(context.Context, *connect.Request[pluxv1.DeleteAppRequest]) (*connect.Response[pluxv1.DeleteAppResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.AppService.DeleteApp is not implemented"))
}

func (UnimplementedAppServiceHandler) CreateEnvironment(context.Context, *connect.Request[pluxv1.CreateEnvironmentRequest]) (*connect.Response[pluxv1.CreateEnvironmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.AppService.CreateEnvironment is not implemented"))
}

func (UnimplementedAppServiceHandler) ListEnvironments(context.Context, *connect.Request[pluxv1.ListEnvironmentsRequest]) (*connect.Response[pluxv1.ListEnvironmentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.AppService.ListEnvironments is not implemented"))
}

func (UnimplementedAppServiceHandler) UpdateEnvironment(context.Context, *connect.Request[pluxv1.UpdateEnvironmentRequest]) (*connect.Response[pluxv1.UpdateEnvironmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.AppService.UpdateEnvironment is not implemented"))
}

func (UnimplementedAppServiceHandler) DeleteEnvironment(context.Context, *connect.Request[pluxv1.DeleteEnvironmentRequest]) (*connect.Response[pluxv1.DeleteEnvironmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.AppService.DeleteEnvironment is not implemented"))
}

func (UnimplementedAppServiceHandler) SetVariable(context.Context, *connect.Request[pluxv1.SetVariableRequest]) (*connect.Response[pluxv1.SetVariableResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.AppService.SetVariable is not implemented"))
}

func (UnimplementedAppServiceHandler) ListVariables(context.Context, *connect.Request[pluxv1.ListVariablesRequest]) (*connect.Response[pluxv1.ListVariablesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.AppService.ListVariables is not implemented"))
}

func (UnimplementedAppServiceHandler) SetSecret(context.Context, *connect.Request[pluxv1.SetSecretRequest]) (*connect.Response[pluxv1.SetSecretResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.AppService.SetSecret is not implemented"))
}

func (UnimplementedAppServiceHandler) ListSecrets(context.Context, *connect.Request[pluxv1.ListSecretsRequest]) (*connect.Response[pluxv1.ListSecretsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.AppService.ListSecrets is not implemented"))
}

func (UnimplementedAppServiceHandler) DeleteSecret(context.Context, *connect.Request[pluxv1.DeleteSecretRequest]) (*connect.Response[pluxv1.DeleteSecretResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.AppService.DeleteSecret is not implemented"))
}

func (UnimplementedAppServiceHandler) CreateChannel(context.Context, *connect.Request[pluxv1.CreateChannelRequest]) (*connect.Response[pluxv1.CreateChannelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.AppService.CreateChannel is not implemented"))
}

func (UnimplementedAppServiceHandler) ListChannels(context.Context, *connect.Request[pluxv1.ListChannelsRequest]) (*connect.Response[pluxv1.ListChannelsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.AppService.ListChannels is not implemented"))
}

func (UnimplementedAppServiceHandler) DeleteChannel(context.Context, *connect.Request[pluxv1.DeleteChannelRequest]) (*connect.Response[pluxv1.DeleteChannelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.AppService.DeleteChannel is not implemented"))
}

func (UnimplementedAppServiceHandler) ListTrash(context.Context, *connect.Request[pluxv1.ListTrashRequest]) (*connect.Response[pluxv1.ListTrashResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.AppService.ListTrash is not implemented"))
}

func (UnimplementedAppServiceHandler) RestoreFromTrash(context.Context, *connect.Request[pluxv1.RestoreFromTrashRequest]) (*connect.Response[pluxv1.RestoreFromTrashResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.AppService.RestoreFromTrash is not implemented"))
}

func (UnimplementedAppServiceHandler) PurgeFromTrash(context.Context, *connect.Request[pluxv1.PurgeFromTrashRequest]) (*connect.Response[pluxv1.PurgeFromTrashResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.AppService.PurgeFromTrash is not implemented"))
}

func (UnimplementedAppServiceHandler) ListAppLimits(context.Context, *connect.Request[pluxv1.ListAppLimitsRequest]) (*connect.Response[pluxv1.ListAppLimitsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.AppService.ListAppLimits is not implemented"))
}

func (UnimplementedAppServiceHandler) SetAppLimit(context.Context, *connect.Request[pluxv1.SetAppLimitRequest]) (*connect.Response[pluxv1.SetAppLimitResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.AppService.SetAppLimit is not implemented"))
}
