// SPDX-FileCopyrightText: 2026 Plux contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: plux/v1/gateway.proto

package pluxv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	pluxv1 "github.com/nightCode42/plux3/backend/internal/pluxv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// GatewayServiceName is the fully-qualified name of the GatewayService service.
	GatewayServiceName = "plux.v1.GatewayService"
	// ScaServiceName is the fully-qualified name of the ScaService service.
	ScaServiceName = "plux.v1.ScaService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// GatewayServiceCallProcedure is the fully-qualified name of the GatewayService's Call RPC.
	GatewayServiceCallProcedure = "/plux.v1.GatewayService/Call"
	// ScaServiceCreateTransactionChallengeProcedure is the fully-qualified name of the ScaService's
	// CreateTransactionChallenge RPC.
	ScaServiceCreateTransactionChallengeProcedure = "/plux.v1.ScaService/CreateTransactionChallenge"
)

// GatewayServiceClient is a client for the plux.v1.GatewayService service.
type GatewayServiceClient interface {
	// Call forwards one request to a configured upstream and returns its
	// response. The device never sees the upstream's credentials, and the
	// server refuses an operation the environment has not allowed
	// (SEC-030).
	Call(context.Context, *connect.Request[pluxv1.CallRequest]) (*connect.Response[pluxv1.CallResponse], error)
}

// NewGatewayServiceClient constructs a client for the plux.v1.GatewayService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGatewayServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GatewayServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	gatewayServiceMethods := pluxv1.File_plux_v1_gateway_proto.Services().ByName("GatewayService").Methods()
	return &gatewayServiceClient{
		call: connect.NewClient[pluxv1.CallRequest, pluxv1.CallResponse](
			httpClient,
			baseURL+GatewayServiceCallProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("Call")),
			connect.WithClientOptions(opts...),
		),
	}
}

// gatewayServiceClient implements GatewayServiceClient.
type gatewayServiceClient struct {
	call *connect.Client[pluxv1.CallRequest, pluxv1.CallResponse]
}

// Call calls plux.v1.GatewayService.Call.
func (c *gatewayServiceClient) Call(ctx context.Context, req *connect.Request[pluxv1.CallRequest]) (*connect.Response[pluxv1.CallResponse], error) {
	return c.call.CallUnary(ctx, req)
}

// GatewayServiceHandler is an implementation of the plux.v1.GatewayService service.
type GatewayServiceHandler interface {
	// Call forwards one request to a configured upstream and returns its
	// response. The device never sees the upstream's credentials, and the
	// server refuses an operation the environment has not allowed
	// (SEC-030).
	Call(context.Context, *connect.Request[pluxv1.CallRequest]) (*connect.Response[pluxv1.CallResponse], error)
}

// NewGatewayServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGatewayServiceHandler(svc GatewayServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	gatewayServiceMethods := pluxv1.File_plux_v1_gateway_proto.Services().ByName("GatewayService").Methods()
	gatewayServiceCallHandler := connect.NewUnaryHandler(
		GatewayServiceCallProcedure,
		svc.Call,
		connect.WithSchema(gatewayServiceMethods.ByName("Call")),
		connect.WithHandlerOptions(opts...),
	)
	return "/plux.v1.GatewayService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GatewayServiceCallProcedure:
			gatewayServiceCallHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGatewayServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGatewayServiceHandler struct{}

func (UnimplementedGatewayServiceHandler) Call(context.Context, *connect.Request[pluxv1.CallRequest]) (*connect.Response[pluxv1.CallResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.GatewayService.Call is not implemented"))
}

// ScaServiceClient is a client for the plux.v1.ScaService service.
type ScaServiceClient interface {
	// CreateTransactionChallenge returns a single-use challenge bound to one
	// transaction summary, which the device shows the user before signing
	// (SEC-027, SEC-028).
	CreateTransactionChallenge(context.Context, *connect.Request[pluxv1.CreateTransactionChallengeRequest]) (*connect.Response[pluxv1.CreateTransactionChallengeResponse], error)
}

// NewScaServiceClient constructs a client for the plux.v1.ScaService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewScaServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ScaServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	scaServiceMethods := pluxv1.File_plux_v1_gateway_proto.Services().ByName("ScaService").Methods()
	return &scaServiceClient{
		createTransactionChallenge: connect.NewClient[pluxv1.CreateTransactionChallengeRequest, pluxv1.CreateTransactionChallengeResponse](
			httpClient,
			baseURL+ScaServiceCreateTransactionChallengeProcedure,
			connect.WithSchema(scaServiceMethods.ByName("CreateTransactionChallenge")),
			connect.WithClientOptions(opts...),
		),
	}
}

// scaServiceClient implements ScaServiceClient.
type scaServiceClient struct {
	createTransactionChallenge *connect.Client[pluxv1.CreateTransactionChallengeRequest, pluxv1.CreateTransactionChallengeResponse]
}

// CreateTransactionChallenge calls plux.v1.ScaService.CreateTransactionChallenge.
func (c *scaServiceClient) CreateTransactionChallenge(ctx context.Context, req *connect.Request[pluxv1.CreateTransactionChallengeRequest]) (*connect.Response[pluxv1.CreateTransactionChallengeResponse], error) {
	return c.createTransactionChallenge.CallUnary(ctx, req)
}

// ScaServiceHandler is an implementation of the plux.v1.ScaService service.
type ScaServiceHandler interface {
	// CreateTransactionChallenge returns a single-use challenge bound to one
	// transaction summary, which the device shows the user before signing
	// (SEC-027, SEC-028).
	CreateTransactionChallenge(context.Context, *connect.Request[pluxv1.CreateTransactionChallengeRequest]) (*connect.Response[pluxv1.CreateTransactionChallengeResponse], error)
}

// NewScaServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewScaServiceHandler(svc ScaServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	scaServiceMethods := pluxv1.File_plux_v1_gateway_proto.Services().ByName("ScaService").Methods()
	scaServiceCreateTransactionChallengeHandler := connect.NewUnaryHandler(
		ScaServiceCreateTransactionChallengeProcedure,
		svc.CreateTransactionChallenge,
		connect.WithSchema(scaServiceMethods.ByName("CreateTransactionChallenge")),
		connect.WithHandlerOptions(opts...),
	)
	return "/plux.v1.ScaService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ScaServiceCreateTransactionChallengeProcedure:
			scaServiceCreateTransactionChallengeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedScaServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedScaServiceHandler struct{}

func (UnimplementedScaServiceHandler) CreateTransactionChallenge(context.Context, *connect.Request[pluxv1.CreateTransactionChallengeRequest]) (*connect.Response[pluxv1.CreateTransactionChallengeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.ScaService.CreateTransactionChallenge is not implemented"))
}
