// SPDX-FileCopyrightText: 2026 Plux contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: plux/v1/manifest.proto

package pluxv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	pluxv1 "github.com/nightCode42/plux3/backend/internal/pluxv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ManifestServiceName is the fully-qualified name of the ManifestService service.
	ManifestServiceName = "plux.v1.ManifestService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ManifestServiceGetManifestProcedure is the fully-qualified name of the ManifestService's
	// GetManifest RPC.
	ManifestServiceGetManifestProcedure = "/plux.v1.ManifestService/GetManifest"
	// ManifestServiceGetSyncPlanProcedure is the fully-qualified name of the ManifestService's
	// GetSyncPlan RPC.
	ManifestServiceGetSyncPlanProcedure = "/plux.v1.ManifestService/GetSyncPlan"
	// ManifestServiceGetRootKeysProcedure is the fully-qualified name of the ManifestService's
	// GetRootKeys RPC.
	ManifestServiceGetRootKeysProcedure = "/plux.v1.ManifestService/GetRootKeys"
)

// ManifestServiceClient is a client for the plux.v1.ManifestService service.
type ManifestServiceClient interface {
	// GetManifest returns the manifest for an app, environment and channel,
	// tailored only by rules evaluated server-side: the same inputs always
	// produce the same manifest (REL-033).
	GetManifest(context.Context, *connect.Request[pluxv1.GetManifestRequest]) (*connect.Response[pluxv1.GetManifestResponse], error)
	// GetSyncPlan takes what the device has installed and returns the exact
	// deltas or full bundles to fetch (REL-032).
	GetSyncPlan(context.Context, *connect.Request[pluxv1.GetSyncPlanRequest]) (*connect.Response[pluxv1.GetSyncPlanResponse], error)
	// GetRootKeys returns the public keys host projects embed (SEC-051).
	GetRootKeys(context.Context, *connect.Request[pluxv1.GetRootKeysRequest]) (*connect.Response[pluxv1.GetRootKeysResponse], error)
}

// NewManifestServiceClient constructs a client for the plux.v1.ManifestService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewManifestServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ManifestServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	manifestServiceMethods := pluxv1.File_plux_v1_manifest_proto.Services().ByName("ManifestService").Methods()
	return &manifestServiceClient{
		getManifest: connect.NewClient[pluxv1.GetManifestRequest, pluxv1.GetManifestResponse](
			httpClient,
			baseURL+ManifestServiceGetManifestProcedure,
			connect.WithSchema(manifestServiceMethods.ByName("GetManifest")),
			connect.WithClientOptions(opts...),
		),
		getSyncPlan: connect.NewClient[pluxv1.GetSyncPlanRequest, pluxv1.GetSyncPlanResponse](
			httpClient,
			baseURL+ManifestServiceGetSyncPlanProcedure,
			connect.WithSchema(manifestServiceMethods.ByName("GetSyncPlan")),
			connect.WithClientOptions(opts...),
		),
		getRootKeys: connect.NewClient[pluxv1.GetRootKeysRequest, pluxv1.GetRootKeysResponse](
			httpClient,
			baseURL+ManifestServiceGetRootKeysProcedure,
			connect.WithSchema(manifestServiceMethods.ByName("GetRootKeys")),
			connect.WithClientOptions(opts...),
		),
	}
}

// manifestServiceClient implements ManifestServiceClient.
type manifestServiceClient struct {
	getManifest *connect.Client[pluxv1.GetManifestRequest, pluxv1.GetManifestResponse]
	getSyncPlan *connect.Client[pluxv1.GetSyncPlanRequest, pluxv1.GetSyncPlanResponse]
	getRootKeys *connect.Client[pluxv1.GetRootKeysRequest, pluxv1.GetRootKeysResponse]
}

// GetManifest calls plux.v1.ManifestService.GetManifest.
func (c *manifestServiceClient) GetManifest(ctx context.Context, req *connect.Request[pluxv1.GetManifestRequest]) (*connect.Response[pluxv1.GetManifestResponse], error) {
	return c.getManifest.CallUnary(ctx, req)
}

// GetSyncPlan calls plux.v1.ManifestService.GetSyncPlan.
func (c *manifestServiceClient) GetSyncPlan(ctx context.Context, req *connect.Request[pluxv1.GetSyncPlanRequest]) (*connect.Response[pluxv1.GetSyncPlanResponse], error) {
	return c.getSyncPlan.CallUnary(ctx, req)
}

// GetRootKeys calls plux.v1.ManifestService.GetRootKeys.
func (c *manifestServiceClient) GetRootKeys(ctx context.Context, req *connect.Request[pluxv1.GetRootKeysRequest]) (*connect.Response[pluxv1.GetRootKeysResponse], error) {
	return c.getRootKeys.CallUnary(ctx, req)
}

// ManifestServiceHandler is an implementation of the plux.v1.ManifestService service.
type ManifestServiceHandler interface {
	// GetManifest returns the manifest for an app, environment and channel,
	// tailored only by rules evaluated server-side: the same inputs always
	// produce the same manifest (REL-033).
	GetManifest(context.Context, *connect.Request[pluxv1.GetManifestRequest]) (*connect.Response[pluxv1.GetManifestResponse], error)
	// GetSyncPlan takes what the device has installed and returns the exact
	// deltas or full bundles to fetch (REL-032).
	GetSyncPlan(context.Context, *connect.Request[pluxv1.GetSyncPlanRequest]) (*connect.Response[pluxv1.GetSyncPlanResponse], error)
	// GetRootKeys returns the public keys host projects embed (SEC-051).
	GetRootKeys(context.Context, *connect.Request[pluxv1.GetRootKeysRequest]) (*connect.Response[pluxv1.GetRootKeysResponse], error)
}

// NewManifestServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewManifestServiceHandler(svc ManifestServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	manifestServiceMethods := pluxv1.File_plux_v1_manifest_proto.Services().ByName("ManifestService").Methods()
	manifestServiceGetManifestHandler := connect.NewUnaryHandler(
		ManifestServiceGetManifestProcedure,
		svc.GetManifest,
		connect.WithSchema(manifestServiceMethods.ByName("GetManifest")),
		connect.WithHandlerOptions(opts...),
	)
	manifestServiceGetSyncPlanHandler := connect.NewUnaryHandler(
		ManifestServiceGetSyncPlanProcedure,
		svc.GetSyncPlan,
		connect.WithSchema(manifestServiceMethods.ByName("GetSyncPlan")),
		connect.WithHandlerOptions(opts...),
	)
	manifestServiceGetRootKeysHandler := connect.NewUnaryHandler(
		ManifestServiceGetRootKeysProcedure,
		svc.GetRootKeys,
		connect.WithSchema(manifestServiceMethods.ByName("GetRootKeys")),
		connect.WithHandlerOptions(opts...),
	)
	return "/plux.v1.ManifestService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ManifestServiceGetManifestProcedure:
			manifestServiceGetManifestHandler.ServeHTTP(w, r)
		case ManifestServiceGetSyncPlanProcedure:
			manifestServiceGetSyncPlanHandler.ServeHTTP(w, r)
		case ManifestServiceGetRootKeysProcedure:
			manifestServiceGetRootKeysHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedManifestServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedManifestServiceHandler struct{}

func (UnimplementedManifestServiceHandler) GetManifest(context.Context, *connect.Request[pluxv1.GetManifestRequest]) (*connect.Response[pluxv1.GetManifestResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.ManifestService.GetManifest is not implemented"))
}

func (UnimplementedManifestServiceHandler) GetSyncPlan(context.Context, *connect.Request[pluxv1.GetSyncPlanRequest]) (*connect.Response[pluxv1.GetSyncPlanResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.ManifestService.GetSyncPlan is not implemented"))
}

func (UnimplementedManifestServiceHandler) GetRootKeys(context.Context, *connect.Request[pluxv1.GetRootKeysRequest]) (*connect.Response[pluxv1.GetRootKeysResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.ManifestService.GetRootKeys is not implemented"))
}
