// SPDX-FileCopyrightText: 2026 Plux contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: plux/v1/publish.proto

package pluxv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	pluxv1 "github.com/nightCode42/plux3/backend/internal/pluxv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PublishServiceName is the fully-qualified name of the PublishService service.
	PublishServiceName = "plux.v1.PublishService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PublishServicePublishProcedure is the fully-qualified name of the PublishService's Publish RPC.
	PublishServicePublishProcedure = "/plux.v1.PublishService/Publish"
	// PublishServiceWatchPublishProcedure is the fully-qualified name of the PublishService's
	// WatchPublish RPC.
	PublishServiceWatchPublishProcedure = "/plux.v1.PublishService/WatchPublish"
	// PublishServiceGetPublishJobProcedure is the fully-qualified name of the PublishService's
	// GetPublishJob RPC.
	PublishServiceGetPublishJobProcedure = "/plux.v1.PublishService/GetPublishJob"
	// PublishServiceListPublishJobsProcedure is the fully-qualified name of the PublishService's
	// ListPublishJobs RPC.
	PublishServiceListPublishJobsProcedure = "/plux.v1.PublishService/ListPublishJobs"
	// PublishServiceCancelPublishJobProcedure is the fully-qualified name of the PublishService's
	// CancelPublishJob RPC.
	PublishServiceCancelPublishJobProcedure = "/plux.v1.PublishService/CancelPublishJob"
)

// PublishServiceClient is a client for the plux.v1.PublishService service.
type PublishServiceClient interface {
	// Publish starts or re-attaches to a publish job. Repeating a call with
	// the same idempotency key within 24 hours returns the original job
	// (SRV-005).
	Publish(context.Context, *connect.Request[pluxv1.PublishRequest]) (*connect.Response[pluxv1.PublishResponse], error)
	// WatchPublish streams a job's progress until it finishes.
	WatchPublish(context.Context, *connect.Request[pluxv1.WatchPublishRequest]) (*connect.ServerStreamForClient[pluxv1.WatchPublishResponse], error)
	GetPublishJob(context.Context, *connect.Request[pluxv1.GetPublishJobRequest]) (*connect.Response[pluxv1.GetPublishJobResponse], error)
	ListPublishJobs(context.Context, *connect.Request[pluxv1.ListPublishJobsRequest]) (*connect.Response[pluxv1.ListPublishJobsResponse], error)
	CancelPublishJob(context.Context, *connect.Request[pluxv1.CancelPublishJobRequest]) (*connect.Response[pluxv1.CancelPublishJobResponse], error)
}

// NewPublishServiceClient constructs a client for the plux.v1.PublishService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPublishServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PublishServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	publishServiceMethods := pluxv1.File_plux_v1_publish_proto.Services().ByName("PublishService").Methods()
	return &publishServiceClient{
		publish: connect.NewClient[pluxv1.PublishRequest, pluxv1.PublishResponse](
			httpClient,
			baseURL+PublishServicePublishProcedure,
			connect.WithSchema(publishServiceMethods.ByName("Publish")),
			connect.WithClientOptions(opts...),
		),
		watchPublish: connect.NewClient[pluxv1.WatchPublishRequest, pluxv1.WatchPublishResponse](
			httpClient,
			baseURL+PublishServiceWatchPublishProcedure,
			connect.WithSchema(publishServiceMethods.ByName("WatchPublish")),
			connect.WithClientOptions(opts...),
		),
		getPublishJob: connect.NewClient[pluxv1.GetPublishJobRequest, pluxv1.GetPublishJobResponse](
			httpClient,
			baseURL+PublishServiceGetPublishJobProcedure,
			connect.WithSchema(publishServiceMethods.ByName("GetPublishJob")),
			connect.WithClientOptions(opts...),
		),
		listPublishJobs: connect.NewClient[pluxv1.ListPublishJobsRequest, pluxv1.ListPublishJobsResponse](
			httpClient,
			baseURL+PublishServiceListPublishJobsProcedure,
			connect.WithSchema(publishServiceMethods.ByName("ListPublishJobs")),
			connect.WithClientOptions(opts...),
		),
		cancelPublishJob: connect.NewClient[pluxv1.CancelPublishJobRequest, pluxv1.CancelPublishJobResponse](
			httpClient,
			baseURL+PublishServiceCancelPublishJobProcedure,
			connect.WithSchema(publishServiceMethods.ByName("CancelPublishJob")),
			connect.WithClientOptions(opts...),
		),
	}
}

// publishServiceClient implements PublishServiceClient.
type publishServiceClient struct {
	publish          *connect.Client[pluxv1.PublishRequest, pluxv1.PublishResponse]
	watchPublish     *connect.Client[pluxv1.WatchPublishRequest, pluxv1.WatchPublishResponse]
	getPublishJob    *connect.Client[pluxv1.GetPublishJobRequest, pluxv1.GetPublishJobResponse]
	listPublishJobs  *connect.Client[pluxv1.ListPublishJobsRequest, pluxv1.ListPublishJobsResponse]
	cancelPublishJob *connect.Client[pluxv1.CancelPublishJobRequest, pluxv1.CancelPublishJobResponse]
}

// Publish calls plux.v1.PublishService.Publish.
func (c *publishServiceClient) Publish(ctx context.Context, req *connect.Request[pluxv1.PublishRequest]) (*connect.Response[pluxv1.PublishResponse], error) {
	return c.publish.CallUnary(ctx, req)
}

// WatchPublish calls plux.v1.PublishService.WatchPublish.
func (c *publishServiceClient) WatchPublish(ctx context.Context, req *connect.Request[pluxv1.WatchPublishRequest]) (*connect.ServerStreamForClient[pluxv1.WatchPublishResponse], error) {
	return c.watchPublish.CallServerStream(ctx, req)
}

// GetPublishJob calls plux.v1.PublishService.GetPublishJob.
func (c *publishServiceClient) GetPublishJob(ctx context.Context, req *connect.Request[pluxv1.GetPublishJobRequest]) (*connect.Response[pluxv1.GetPublishJobResponse], error) {
	return c.getPublishJob.CallUnary(ctx, req)
}

// ListPublishJobs calls plux.v1.PublishService.ListPublishJobs.
func (c *publishServiceClient) ListPublishJobs(ctx context.Context, req *connect.Request[pluxv1.ListPublishJobsRequest]) (*connect.Response[pluxv1.ListPublishJobsResponse], error) {
	return c.listPublishJobs.CallUnary(ctx, req)
}

// CancelPublishJob calls plux.v1.PublishService.CancelPublishJob.
func (c *publishServiceClient) CancelPublishJob(ctx context.Context, req *connect.Request[pluxv1.CancelPublishJobRequest]) (*connect.Response[pluxv1.CancelPublishJobResponse], error) {
	return c.cancelPublishJob.CallUnary(ctx, req)
}

// PublishServiceHandler is an implementation of the plux.v1.PublishService service.
type PublishServiceHandler interface {
	// Publish starts or re-attaches to a publish job. Repeating a call with
	// the same idempotency key within 24 hours returns the original job
	// (SRV-005).
	Publish(context.Context, *connect.Request[pluxv1.PublishRequest]) (*connect.Response[pluxv1.PublishResponse], error)
	// WatchPublish streams a job's progress until it finishes.
	WatchPublish(context.Context, *connect.Request[pluxv1.WatchPublishRequest], *connect.ServerStream[pluxv1.WatchPublishResponse]) error
	GetPublishJob(context.Context, *connect.Request[pluxv1.GetPublishJobRequest]) (*connect.Response[pluxv1.GetPublishJobResponse], error)
	ListPublishJobs(context.Context, *connect.Request[pluxv1.ListPublishJobsRequest]) (*connect.Response[pluxv1.ListPublishJobsResponse], error)
	CancelPublishJob(context.Context, *connect.Request[pluxv1.CancelPublishJobRequest]) (*connect.Response[pluxv1.CancelPublishJobResponse], error)
}

// NewPublishServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPublishServiceHandler(svc PublishServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	publishServiceMethods := pluxv1.File_plux_v1_publish_proto.Services().ByName("PublishService").Methods()
	publishServicePublishHandler := connect.NewUnaryHandler(
		PublishServicePublishProcedure,
		svc.Publish,
		connect.WithSchema(publishServiceMethods.ByName("Publish")),
		connect.WithHandlerOptions(opts...),
	)
	publishServiceWatchPublishHandler := connect.NewServerStreamHandler(
		PublishServiceWatchPublishProcedure,
		svc.WatchPublish,
		connect.WithSchema(publishServiceMethods.ByName("WatchPublish")),
		connect.WithHandlerOptions(opts...),
	)
	publishServiceGetPublishJobHandler := connect.NewUnaryHandler(
		PublishServiceGetPublishJobProcedure,
		svc.GetPublishJob,
		connect.WithSchema(publishServiceMethods.ByName("GetPublishJob")),
		connect.WithHandlerOptions(opts...),
	)
	publishServiceListPublishJobsHandler := connect.NewUnaryHandler(
		PublishServiceListPublishJobsProcedure,
		svc.ListPublishJobs,
		connect.WithSchema(publishServiceMethods.ByName("ListPublishJobs")),
		connect.WithHandlerOptions(opts...),
	)
	publishServiceCancelPublishJobHandler := connect.NewUnaryHandler(
		PublishServiceCancelPublishJobProcedure,
		svc.CancelPublishJob,
		connect.WithSchema(publishServiceMethods.ByName("CancelPublishJob")),
		connect.WithHandlerOptions(opts...),
	)
	return "/plux.v1.PublishService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PublishServicePublishProcedure:
			publishServicePublishHandler.ServeHTTP(w, r)
		case PublishServiceWatchPublishProcedure:
			publishServiceWatchPublishHandler.ServeHTTP(w, r)
		case PublishServiceGetPublishJobProcedure:
			publishServiceGetPublishJobHandler.ServeHTTP(w, r)
		case PublishServiceListPublishJobsProcedure:
			publishServiceListPublishJobsHandler.ServeHTTP(w, r)
		case PublishServiceCancelPublishJobProcedure:
			publishServiceCancelPublishJobHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPublishServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPublishServiceHandler struct{}

func (UnimplementedPublishServiceHandler) Publish(context.Context, *connect.Request[pluxv1.PublishRequest]) (*connect.Response[pluxv1.PublishResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.PublishService.Publish is not implemented"))
}

func (UnimplementedPublishServiceHandler) WatchPublish(context.Context, *connect.Request[pluxv1.WatchPublishRequest], *connect.ServerStream[pluxv1.WatchPublishResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.PublishService.WatchPublish is not implemented"))
}

func (UnimplementedPublishServiceHandler) GetPublishJob(context.Context, *connect.Request[pluxv1.GetPublishJobRequest]) (*connect.Response[pluxv1.GetPublishJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.PublishService.GetPublishJob is not implemented"))
}

func (UnimplementedPublishServiceHandler) ListPublishJobs(context.Context, *connect.Request[pluxv1.ListPublishJobsRequest]) (*connect.Response[pluxv1.ListPublishJobsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.PublishService.ListPublishJobs is not implemented"))
}

func (UnimplementedPublishServiceHandler) CancelPublishJob(context.Context, *connect.Request[pluxv1.CancelPublishJobRequest]) (*connect.Response[pluxv1.CancelPublishJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.PublishService.CancelPublishJob is not implemented"))
}
