// SPDX-FileCopyrightText: 2026 Plux contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: plux/v1/release.proto

package pluxv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	pluxv1 "github.com/nightCode42/plux3/backend/internal/pluxv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ReleaseServiceName is the fully-qualified name of the ReleaseService service.
	ReleaseServiceName = "plux.v1.ReleaseService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ReleaseServiceGetPluginVersionProcedure is the fully-qualified name of the ReleaseService's
	// GetPluginVersion RPC.
	ReleaseServiceGetPluginVersionProcedure = "/plux.v1.ReleaseService/GetPluginVersion"
	// ReleaseServiceListPluginVersionsProcedure is the fully-qualified name of the ReleaseService's
	// ListPluginVersions RPC.
	ReleaseServiceListPluginVersionsProcedure = "/plux.v1.ReleaseService/ListPluginVersions"
	// ReleaseServiceCreateReleaseProcedure is the fully-qualified name of the ReleaseService's
	// CreateRelease RPC.
	ReleaseServiceCreateReleaseProcedure = "/plux.v1.ReleaseService/CreateRelease"
	// ReleaseServiceGetReleaseProcedure is the fully-qualified name of the ReleaseService's GetRelease
	// RPC.
	ReleaseServiceGetReleaseProcedure = "/plux.v1.ReleaseService/GetRelease"
	// ReleaseServiceListReleasesProcedure is the fully-qualified name of the ReleaseService's
	// ListReleases RPC.
	ReleaseServiceListReleasesProcedure = "/plux.v1.ReleaseService/ListReleases"
	// ReleaseServicePromoteReleaseProcedure is the fully-qualified name of the ReleaseService's
	// PromoteRelease RPC.
	ReleaseServicePromoteReleaseProcedure = "/plux.v1.ReleaseService/PromoteRelease"
	// ReleaseServiceRollbackReleaseProcedure is the fully-qualified name of the ReleaseService's
	// RollbackRelease RPC.
	ReleaseServiceRollbackReleaseProcedure = "/plux.v1.ReleaseService/RollbackRelease"
	// ReleaseServiceGetChangelogProcedure is the fully-qualified name of the ReleaseService's
	// GetChangelog RPC.
	ReleaseServiceGetChangelogProcedure = "/plux.v1.ReleaseService/GetChangelog"
	// ReleaseServiceGetCompatibilityProcedure is the fully-qualified name of the ReleaseService's
	// GetCompatibility RPC.
	ReleaseServiceGetCompatibilityProcedure = "/plux.v1.ReleaseService/GetCompatibility"
)

// ReleaseServiceClient is a client for the plux.v1.ReleaseService service.
type ReleaseServiceClient interface {
	GetPluginVersion(context.Context, *connect.Request[pluxv1.GetPluginVersionRequest]) (*connect.Response[pluxv1.GetPluginVersionResponse], error)
	ListPluginVersions(context.Context, *connect.Request[pluxv1.ListPluginVersionsRequest]) (*connect.Response[pluxv1.ListPluginVersionsResponse], error)
	// CreateRelease validates a candidate set across every plugin and
	// creates an app release; an unresolved reference stops it (REL-003).
	CreateRelease(context.Context, *connect.Request[pluxv1.CreateReleaseRequest]) (*connect.Response[pluxv1.CreateReleaseResponse], error)
	GetRelease(context.Context, *connect.Request[pluxv1.GetReleaseRequest]) (*connect.Response[pluxv1.GetReleaseResponse], error)
	ListReleases(context.Context, *connect.Request[pluxv1.ListReleasesRequest]) (*connect.Response[pluxv1.ListReleasesResponse], error)
	// PromoteRelease points a channel at an existing release. It copies no
	// bytes and recompiles nothing (REL-004).
	PromoteRelease(context.Context, *connect.Request[pluxv1.PromoteReleaseRequest]) (*connect.Response[pluxv1.PromoteReleaseResponse], error)
	// RollbackRelease creates a new release whose content equals an earlier
	// one, so device anti-rollback is never weakened (REL-006).
	RollbackRelease(context.Context, *connect.Request[pluxv1.RollbackReleaseRequest]) (*connect.Response[pluxv1.RollbackReleaseResponse], error)
	// GetChangelog returns the generated changelog of a release (REL-081).
	GetChangelog(context.Context, *connect.Request[pluxv1.GetChangelogRequest]) (*connect.Response[pluxv1.GetChangelogResponse], error)
	// GetCompatibility reports which runtime versions and host builds can
	// use a release, and how many devices are affected (REL-080).
	GetCompatibility(context.Context, *connect.Request[pluxv1.GetCompatibilityRequest]) (*connect.Response[pluxv1.GetCompatibilityResponse], error)
}

// NewReleaseServiceClient constructs a client for the plux.v1.ReleaseService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewReleaseServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ReleaseServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	releaseServiceMethods := pluxv1.File_plux_v1_release_proto.Services().ByName("ReleaseService").Methods()
	return &releaseServiceClient{
		getPluginVersion: connect.NewClient[pluxv1.GetPluginVersionRequest, pluxv1.GetPluginVersionResponse](
			httpClient,
			baseURL+ReleaseServiceGetPluginVersionProcedure,
			connect.WithSchema(releaseServiceMethods.ByName("GetPluginVersion")),
			connect.WithClientOptions(opts...),
		),
		listPluginVersions: connect.NewClient[pluxv1.ListPluginVersionsRequest, pluxv1.ListPluginVersionsResponse](
			httpClient,
			baseURL+ReleaseServiceListPluginVersionsProcedure,
			connect.WithSchema(releaseServiceMethods.ByName("ListPluginVersions")),
			connect.WithClientOptions(opts...),
		),
		createRelease: connect.NewClient[pluxv1.CreateReleaseRequest, pluxv1.CreateReleaseResponse](
			httpClient,
			baseURL+ReleaseServiceCreateReleaseProcedure,
			connect.WithSchema(releaseServiceMethods.ByName("CreateRelease")),
			connect.WithClientOptions(opts...),
		),
		getRelease: connect.NewClient[pluxv1.GetReleaseRequest, pluxv1.GetReleaseResponse](
			httpClient,
			baseURL+ReleaseServiceGetReleaseProcedure,
			connect.WithSchema(releaseServiceMethods.ByName("GetRelease")),
			connect.WithClientOptions(opts...),
		),
		listReleases: connect.NewClient[pluxv1.ListReleasesRequest, pluxv1.ListReleasesResponse](
			httpClient,
			baseURL+ReleaseServiceListReleasesProcedure,
			connect.WithSchema(releaseServiceMethods.ByName("ListReleases")),
			connect.WithClientOptions(opts...),
		),
		promoteRelease: connect.NewClient[pluxv1.PromoteReleaseRequest, pluxv1.PromoteReleaseResponse](
			httpClient,
			baseURL+ReleaseServicePromoteReleaseProcedure,
			connect.WithSchema(releaseServiceMethods.ByName("PromoteRelease")),
			connect.WithClientOptions(opts...),
		),
		rollbackRelease: connect.NewClient[pluxv1.RollbackReleaseRequest, pluxv1.RollbackReleaseResponse](
			httpClient,
			baseURL+ReleaseServiceRollbackReleaseProcedure,
			connect.WithSchema(releaseServiceMethods.ByName("RollbackRelease")),
			connect.WithClientOptions(opts...),
		),
		getChangelog: connect.NewClient[pluxv1.GetChangelogRequest, pluxv1.GetChangelogResponse](
			httpClient,
			baseURL+ReleaseServiceGetChangelogProcedure,
			connect.WithSchema(releaseServiceMethods.ByName("GetChangelog")),
			connect.WithClientOptions(opts...),
		),
		getCompatibility: connect.NewClient[pluxv1.GetCompatibilityRequest, pluxv1.GetCompatibilityResponse](
			httpClient,
			baseURL+ReleaseServiceGetCompatibilityProcedure,
			connect.WithSchema(releaseServiceMethods.ByName("GetCompatibility")),
			connect.WithClientOptions(opts...),
		),
	}
}

// releaseServiceClient implements ReleaseServiceClient.
type releaseServiceClient struct {
	getPluginVersion   *connect.Client[pluxv1.GetPluginVersionRequest, pluxv1.GetPluginVersionResponse]
	listPluginVersions *connect.Client[pluxv1.ListPluginVersionsRequest, pluxv1.ListPluginVersionsResponse]
	createRelease      *connect.Client[pluxv1.CreateReleaseRequest, pluxv1.CreateReleaseResponse]
	getRelease         *connect.Client[pluxv1.GetReleaseRequest, pluxv1.GetReleaseResponse]
	listReleases       *connect.Client[pluxv1.ListReleasesRequest, pluxv1.ListReleasesResponse]
	promoteRelease     *connect.Client[pluxv1.PromoteReleaseRequest, pluxv1.PromoteReleaseResponse]
	rollbackRelease    *connect.Client[pluxv1.RollbackReleaseRequest, pluxv1.RollbackReleaseResponse]
	getChangelog       *connect.Client[pluxv1.GetChangelogRequest, pluxv1.GetChangelogResponse]
	getCompatibility   *connect.Client[pluxv1.GetCompatibilityRequest, pluxv1.GetCompatibilityResponse]
}

// GetPluginVersion calls plux.v1.ReleaseService.GetPluginVersion.
func (c *releaseServiceClient) GetPluginVersion(ctx context.Context, req *connect.Request[pluxv1.GetPluginVersionRequest]) (*connect.Response[pluxv1.GetPluginVersionResponse], error) {
	return c.getPluginVersion.CallUnary(ctx, req)
}

// ListPluginVersions calls plux.v1.ReleaseService.ListPluginVersions.
func (c *releaseServiceClient) ListPluginVersions(ctx context.Context, req *connect.Request[pluxv1.ListPluginVersionsRequest]) (*connect.Response[pluxv1.ListPluginVersionsResponse], error) {
	return c.listPluginVersions.CallUnary(ctx, req)
}

// CreateRelease calls plux.v1.ReleaseService.CreateRelease.
func (c *releaseServiceClient) CreateRelease(ctx context.Context, req *connect.Request[pluxv1.CreateReleaseRequest]) (*connect.Response[pluxv1.CreateReleaseResponse], error) {
	return c.createRelease.CallUnary(ctx, req)
}

// GetRelease calls plux.v1.ReleaseService.GetRelease.
func (c *releaseServiceClient) GetRelease(ctx context.Context, req *connect.Request[pluxv1.GetReleaseRequest]) (*connect.Response[pluxv1.GetReleaseResponse], error) {
	return c.getRelease.CallUnary(ctx, req)
}

// ListReleases calls plux.v1.ReleaseService.ListReleases.
func (c *releaseServiceClient) ListReleases(ctx context.Context, req *connect.Request[pluxv1.ListReleasesRequest]) (*connect.Response[pluxv1.ListReleasesResponse], error) {
	return c.listReleases.CallUnary(ctx, req)
}

// PromoteRelease calls plux.v1.ReleaseService.PromoteRelease.
func (c *releaseServiceClient) PromoteRelease(ctx context.Context, req *connect.Request[pluxv1.PromoteReleaseRequest]) (*connect.Response[pluxv1.PromoteReleaseResponse], error) {
	return c.promoteRelease.CallUnary(ctx, req)
}

// RollbackRelease calls plux.v1.ReleaseService.RollbackRelease.
func (c *releaseServiceClient) RollbackRelease(ctx context.Context, req *connect.Request[pluxv1.RollbackReleaseRequest]) (*connect.Response[pluxv1.RollbackReleaseResponse], error) {
	return c.rollbackRelease.CallUnary(ctx, req)
}

// GetChangelog calls plux.v1.ReleaseService.GetChangelog.
func (c *releaseServiceClient) GetChangelog(ctx context.Context, req *connect.Request[pluxv1.GetChangelogRequest]) (*connect.Response[pluxv1.GetChangelogResponse], error) {
	return c.getChangelog.CallUnary(ctx, req)
}

// GetCompatibility calls plux.v1.ReleaseService.GetCompatibility.
func (c *releaseServiceClient) GetCompatibility(ctx context.Context, req *connect.Request[pluxv1.GetCompatibilityRequest]) (*connect.Response[pluxv1.GetCompatibilityResponse], error) {
	return c.getCompatibility.CallUnary(ctx, req)
}

// ReleaseServiceHandler is an implementation of the plux.v1.ReleaseService service.
type ReleaseServiceHandler interface {
	GetPluginVersion(context.Context, *connect.Request[pluxv1.GetPluginVersionRequest]) (*connect.Response[pluxv1.GetPluginVersionResponse], error)
	ListPluginVersions(context.Context, *connect.Request[pluxv1.ListPluginVersionsRequest]) (*connect.Response[pluxv1.ListPluginVersionsResponse], error)
	// CreateRelease validates a candidate set across every plugin and
	// creates an app release; an unresolved reference stops it (REL-003).
	CreateRelease(context.Context, *connect.Request[pluxv1.CreateReleaseRequest]) (*connect.Response[pluxv1.CreateReleaseResponse], error)
	GetRelease(context.Context, *connect.Request[pluxv1.GetReleaseRequest]) (*connect.Response[pluxv1.GetReleaseResponse], error)
	ListReleases(context.Context, *connect.Request[pluxv1.ListReleasesRequest]) (*connect.Response[pluxv1.ListReleasesResponse], error)
	// PromoteRelease points a channel at an existing release. It copies no
	// bytes and recompiles nothing (REL-004).
	PromoteRelease(context.Context, *connect.Request[pluxv1.PromoteReleaseRequest]) (*connect.Response[pluxv1.PromoteReleaseResponse], error)
	// RollbackRelease creates a new release whose content equals an earlier
	// one, so device anti-rollback is never weakened (REL-006).
	RollbackRelease(context.Context, *connect.Request[pluxv1.RollbackReleaseRequest]) (*connect.Response[pluxv1.RollbackReleaseResponse], error)
	// GetChangelog returns the generated changelog of a release (REL-081).
	GetChangelog(context.Context, *connect.Request[pluxv1.GetChangelogRequest]) (*connect.Response[pluxv1.GetChangelogResponse], error)
	// GetCompatibility reports which runtime versions and host builds can
	// use a release, and how many devices are affected (REL-080).
	GetCompatibility(context.Context, *connect.Request[pluxv1.GetCompatibilityRequest]) (*connect.Response[pluxv1.GetCompatibilityResponse], error)
}

// NewReleaseServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewReleaseServiceHandler(svc ReleaseServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	releaseServiceMethods := pluxv1.File_plux_v1_release_proto.Services().ByName("ReleaseService").Methods()
	releaseServiceGetPluginVersionHandler := connect.NewUnaryHandler(
		ReleaseServiceGetPluginVersionProcedure,
		svc.GetPluginVersion,
		connect.WithSchema(releaseServiceMethods.ByName("GetPluginVersion")),
		connect.WithHandlerOptions(opts...),
	)
	releaseServiceListPluginVersionsHandler := connect.NewUnaryHandler(
		ReleaseServiceListPluginVersionsProcedure,
		svc.ListPluginVersions,
		connect.WithSchema(releaseServiceMethods.ByName("ListPluginVersions")),
		connect.WithHandlerOptions(opts...),
	)
	releaseServiceCreateReleaseHandler := connect.NewUnaryHandler(
		ReleaseServiceCreateReleaseProcedure,
		svc.CreateRelease,
		connect.WithSchema(releaseServiceMethods.ByName("CreateRelease")),
		connect.WithHandlerOptions(opts...),
	)
	releaseServiceGetReleaseHandler := connect.NewUnaryHandler(
		ReleaseServiceGetReleaseProcedure,
		svc.GetRelease,
		connect.WithSchema(releaseServiceMethods.ByName("GetRelease")),
		connect.WithHandlerOptions(opts...),
	)
	releaseServiceListReleasesHandler := connect.NewUnaryHandler(
		ReleaseServiceListReleasesProcedure,
		svc.ListReleases,
		connect.WithSchema(releaseServiceMethods.ByName("ListReleases")),
		connect.WithHandlerOptions(opts...),
	)
	releaseServicePromoteReleaseHandler := connect.NewUnaryHandler(
		ReleaseServicePromoteReleaseProcedure,
		svc.PromoteRelease,
		connect.WithSchema(releaseServiceMethods.ByName("PromoteRelease")),
		connect.WithHandlerOptions(opts...),
	)
	releaseServiceRollbackReleaseHandler := connect.NewUnaryHandler(
		ReleaseServiceRollbackReleaseProcedure,
		svc.RollbackRelease,
		connect.WithSchema(releaseServiceMethods.ByName("RollbackRelease")),
		connect.WithHandlerOptions(opts...),
	)
	releaseServiceGetChangelogHandler := connect.NewUnaryHandler(
		ReleaseServiceGetChangelogProcedure,
		svc.GetChangelog,
		connect.WithSchema(releaseServiceMethods.ByName("GetChangelog")),
		connect.WithHandlerOptions(opts...),
	)
	releaseServiceGetCompatibilityHandler := connect.NewUnaryHandler(
		ReleaseServiceGetCompatibilityProcedure,
		svc.GetCompatibility,
		connect.WithSchema(releaseServiceMethods.ByName("GetCompatibility")),
		connect.WithHandlerOptions(opts...),
	)
	return "/plux.v1.ReleaseService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ReleaseServiceGetPluginVersionProcedure:
			releaseServiceGetPluginVersionHandler.ServeHTTP(w, r)
		case ReleaseServiceListPluginVersionsProcedure:
			releaseServiceListPluginVersionsHandler.ServeHTTP(w, r)
		case ReleaseServiceCreateReleaseProcedure:
			releaseServiceCreateReleaseHandler.ServeHTTP(w, r)
		case ReleaseServiceGetReleaseProcedure:
			releaseServiceGetReleaseHandler.ServeHTTP(w, r)
		case ReleaseServiceListReleasesProcedure:
			releaseServiceListReleasesHandler.ServeHTTP(w, r)
		case ReleaseServicePromoteReleaseProcedure:
			releaseServicePromoteReleaseHandler.ServeHTTP(w, r)
		case ReleaseServiceRollbackReleaseProcedure:
			releaseServiceRollbackReleaseHandler.ServeHTTP(w, r)
		case ReleaseServiceGetChangelogProcedure:
			releaseServiceGetChangelogHandler.ServeHTTP(w, r)
		case ReleaseServiceGetCompatibilityProcedure:
			releaseServiceGetCompatibilityHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedReleaseServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedReleaseServiceHandler struct{}

func (UnimplementedReleaseServiceHandler) GetPluginVersion(context.Context, *connect.Request[pluxv1.GetPluginVersionRequest]) (*connect.Response[pluxv1.GetPluginVersionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.ReleaseService.GetPluginVersion is not implemented"))
}

func (UnimplementedReleaseServiceHandler) ListPluginVersions(context.Context, *connect.Request[pluxv1.ListPluginVersionsRequest]) (*connect.Response[pluxv1.ListPluginVersionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.ReleaseService.ListPluginVersions is not implemented"))
}

func (UnimplementedReleaseServiceHandler) CreateRelease(context.Context, *connect.Request[pluxv1.CreateReleaseRequest]) (*connect.Response[pluxv1.CreateReleaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.ReleaseService.CreateRelease is not implemented"))
}

func (UnimplementedReleaseServiceHandler) GetRelease(context.Context, *connect.Request[pluxv1.GetReleaseRequest]) (*connect.Response[pluxv1.GetReleaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.ReleaseService.GetRelease is not implemented"))
}

func (UnimplementedReleaseServiceHandler) ListReleases(context.Context, *connect.Request[pluxv1.ListReleasesRequest]) (*connect.Response[pluxv1.ListReleasesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.ReleaseService.ListReleases is not implemented"))
}

func (UnimplementedReleaseServiceHandler) PromoteRelease(context.Context, *connect.Request[pluxv1.PromoteReleaseRequest]) (*connect.Response[pluxv1.PromoteReleaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.ReleaseService.PromoteRelease is not implemented"))
}

func (UnimplementedReleaseServiceHandler) RollbackRelease(context.Context, *connect.Request[pluxv1.RollbackReleaseRequest]) (*connect.Response[pluxv1.RollbackReleaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.ReleaseService.RollbackRelease is not implemented"))
}

func (UnimplementedReleaseServiceHandler) GetChangelog(context.Context, *connect.Request[pluxv1.GetChangelogRequest]) (*connect.Response[pluxv1.GetChangelogResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.ReleaseService.GetChangelog is not implemented"))
}

func (UnimplementedReleaseServiceHandler) GetCompatibility(context.Context, *connect.Request[pluxv1.GetCompatibilityRequest]) (*connect.Response[pluxv1.GetCompatibilityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plux.v1.ReleaseService.GetCompatibility is not implemented"))
}
