// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AssetIndex struct {
	_tab flatbuffers.Table
}

func GetRootAsAssetIndex(buf []byte, offset flatbuffers.UOffsetT) *AssetIndex {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AssetIndex{}
	x.Init(buf, n+offset)
	return x
}

func FinishAssetIndexBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAssetIndex(buf []byte, offset flatbuffers.UOffsetT) *AssetIndex {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AssetIndex{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAssetIndexBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AssetIndex) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AssetIndex) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AssetIndex) Assets(obj *Asset, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *AssetIndex) AssetsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func AssetIndexStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func AssetIndexAddAssets(builder *flatbuffers.Builder, assets flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(assets), 0)
}
func AssetIndexStartAssetsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func AssetIndexEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
