// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import "strconv"

type BundleKind byte

const (
	BundleKindUnknown     BundleKind = 0
	BundleKindPlugin      BundleKind = 1
	BundleKindApp         BundleKind = 2
	BundleKindDevelopment BundleKind = 3
)

var EnumNamesBundleKind = map[BundleKind]string{
	BundleKindUnknown:     "Unknown",
	BundleKindPlugin:      "Plugin",
	BundleKindApp:         "App",
	BundleKindDevelopment: "Development",
}

var EnumValuesBundleKind = map[string]BundleKind{
	"Unknown":     BundleKindUnknown,
	"Plugin":      BundleKindPlugin,
	"App":         BundleKindApp,
	"Development": BundleKindDevelopment,
}

func (v BundleKind) String() string {
	if s, ok := EnumNamesBundleKind[v]; ok {
		return s
	}
	return "BundleKind(" + strconv.FormatInt(int64(v), 10) + ")"
}
