// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ComponentSlot struct {
	_tab flatbuffers.Table
}

func GetRootAsComponentSlot(buf []byte, offset flatbuffers.UOffsetT) *ComponentSlot {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ComponentSlot{}
	x.Init(buf, n+offset)
	return x
}

func FinishComponentSlotBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsComponentSlot(buf []byte, offset flatbuffers.UOffsetT) *ComponentSlot {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ComponentSlot{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedComponentSlotBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ComponentSlot) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ComponentSlot) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ComponentSlot) Name() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ComponentSlot) MutateName(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *ComponentSlot) Required() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ComponentSlot) MutateRequired(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func (rcv *ComponentSlot) Multiple() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ComponentSlot) MutateMultiple(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func ComponentSlotStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func ComponentSlotAddName(builder *flatbuffers.Builder, name uint32) {
	builder.PrependUint32Slot(0, name, 0)
}
func ComponentSlotAddRequired(builder *flatbuffers.Builder, required bool) {
	builder.PrependBoolSlot(1, required, false)
}
func ComponentSlotAddMultiple(builder *flatbuffers.Builder, multiple bool) {
	builder.PrependBoolSlot(2, multiple, false)
}
func ComponentSlotEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
