// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import "strconv"

type DataSourceKind byte

const (
	DataSourceKindRest      DataSourceKind = 0
	DataSourceKindGraphql   DataSourceKind = 1
	DataSourceKindWebsocket DataSourceKind = 2
	DataSourceKindSse       DataSourceKind = 3
	DataSourceKindFunction  DataSourceKind = 4
	DataSourceKindDatabase  DataSourceKind = 5
	DataSourceKindStatic    DataSourceKind = 6
)

var EnumNamesDataSourceKind = map[DataSourceKind]string{
	DataSourceKindRest:      "Rest",
	DataSourceKindGraphql:   "Graphql",
	DataSourceKindWebsocket: "Websocket",
	DataSourceKindSse:       "Sse",
	DataSourceKindFunction:  "Function",
	DataSourceKindDatabase:  "Database",
	DataSourceKindStatic:    "Static",
}

var EnumValuesDataSourceKind = map[string]DataSourceKind{
	"Rest":      DataSourceKindRest,
	"Graphql":   DataSourceKindGraphql,
	"Websocket": DataSourceKindWebsocket,
	"Sse":       DataSourceKindSse,
	"Function":  DataSourceKindFunction,
	"Database":  DataSourceKindDatabase,
	"Static":    DataSourceKindStatic,
}

func (v DataSourceKind) String() string {
	if s, ok := EnumNamesDataSourceKind[v]; ok {
		return s
	}
	return "DataSourceKind(" + strconv.FormatInt(int64(v), 10) + ")"
}
