// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FormField struct {
	_tab flatbuffers.Table
}

func GetRootAsFormField(buf []byte, offset flatbuffers.UOffsetT) *FormField {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FormField{}
	x.Init(buf, n+offset)
	return x
}

func FinishFormFieldBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFormField(buf []byte, offset flatbuffers.UOffsetT) *FormField {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FormField{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFormFieldBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FormField) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FormField) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FormField) Name() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FormField) MutateName(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *FormField) Type() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FormField) MutateType(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *FormField) Initial(obj *Value) *Value {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Value)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *FormField) Validators(obj *FormValidator, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *FormField) ValidatorsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func FormFieldStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func FormFieldAddName(builder *flatbuffers.Builder, name uint32) {
	builder.PrependUint32Slot(0, name, 0)
}
func FormFieldAddType(builder *flatbuffers.Builder, type_ uint32) {
	builder.PrependUint32Slot(1, type_, 0)
}
func FormFieldAddInitial(builder *flatbuffers.Builder, initial flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(initial), 0)
}
func FormFieldAddValidators(builder *flatbuffers.Builder, validators flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(validators), 0)
}
func FormFieldStartValidatorsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func FormFieldEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
