// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import "strconv"

type HostEventDirection byte

const (
	HostEventDirectionToHost HostEventDirection = 0
	HostEventDirectionToPlux HostEventDirection = 1
	HostEventDirectionBoth   HostEventDirection = 2
)

var EnumNamesHostEventDirection = map[HostEventDirection]string{
	HostEventDirectionToHost: "ToHost",
	HostEventDirectionToPlux: "ToPlux",
	HostEventDirectionBoth:   "Both",
}

var EnumValuesHostEventDirection = map[string]HostEventDirection{
	"ToHost": HostEventDirectionToHost,
	"ToPlux": HostEventDirectionToPlux,
	"Both":   HostEventDirectionBoth,
}

func (v HostEventDirection) String() string {
	if s, ok := EnumNamesHostEventDirection[v]; ok {
		return s
	}
	return "HostEventDirection(" + strconv.FormatInt(int64(v), 10) + ")"
}
