// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type NativeSlotDecl struct {
	_tab flatbuffers.Table
}

func GetRootAsNativeSlotDecl(buf []byte, offset flatbuffers.UOffsetT) *NativeSlotDecl {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &NativeSlotDecl{}
	x.Init(buf, n+offset)
	return x
}

func FinishNativeSlotDeclBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsNativeSlotDecl(buf []byte, offset flatbuffers.UOffsetT) *NativeSlotDecl {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &NativeSlotDecl{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedNativeSlotDeclBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *NativeSlotDecl) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *NativeSlotDecl) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *NativeSlotDecl) Type() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *NativeSlotDecl) MutateType(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *NativeSlotDecl) Props(obj *Param, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *NativeSlotDecl) PropsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *NativeSlotDecl) Events(obj *ComponentEvent, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *NativeSlotDecl) EventsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func NativeSlotDeclStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func NativeSlotDeclAddType(builder *flatbuffers.Builder, type_ uint32) {
	builder.PrependUint32Slot(0, type_, 0)
}
func NativeSlotDeclAddProps(builder *flatbuffers.Builder, props flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(props), 0)
}
func NativeSlotDeclStartPropsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func NativeSlotDeclAddEvents(builder *flatbuffers.Builder, events flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(events), 0)
}
func NativeSlotDeclStartEventsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func NativeSlotDeclEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
