// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import "strconv"

type PageKind byte

const (
	PageKindScreen           PageKind = 0
	PageKindDialog           PageKind = 1
	PageKindBottomSheet      PageKind = 2
	PageKindFullscreenDialog PageKind = 3
)

var EnumNamesPageKind = map[PageKind]string{
	PageKindScreen:           "Screen",
	PageKindDialog:           "Dialog",
	PageKindBottomSheet:      "BottomSheet",
	PageKindFullscreenDialog: "FullscreenDialog",
}

var EnumValuesPageKind = map[string]PageKind{
	"Screen":           PageKindScreen,
	"Dialog":           PageKindDialog,
	"BottomSheet":      PageKindBottomSheet,
	"FullscreenDialog": PageKindFullscreenDialog,
}

func (v PageKind) String() string {
	if s, ok := EnumNamesPageKind[v]; ok {
		return s
	}
	return "PageKind(" + strconv.FormatInt(int64(v), 10) + ")"
}
