// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import "strconv"

type Persistence byte

const (
	PersistenceMemory    Persistence = 0
	PersistenceSession   Persistence = 1
	PersistencePersisted Persistence = 2
	PersistenceSecure    Persistence = 3
)

var EnumNamesPersistence = map[Persistence]string{
	PersistenceMemory:    "Memory",
	PersistenceSession:   "Session",
	PersistencePersisted: "Persisted",
	PersistenceSecure:    "Secure",
}

var EnumValuesPersistence = map[string]Persistence{
	"Memory":    PersistenceMemory,
	"Session":   PersistenceSession,
	"Persisted": PersistencePersisted,
	"Secure":    PersistenceSecure,
}

func (v Persistence) String() string {
	if s, ok := EnumNamesPersistence[v]; ok {
		return s
	}
	return "Persistence(" + strconv.FormatInt(int64(v), 10) + ")"
}
