// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Push struct {
	_tab flatbuffers.Table
}

func GetRootAsPush(buf []byte, offset flatbuffers.UOffsetT) *Push {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Push{}
	x.Init(buf, n+offset)
	return x
}

func FinishPushBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPush(buf []byte, offset flatbuffers.UOffsetT) *Push {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Push{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPushBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Push) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Push) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Push) Enabled() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *Push) MutateEnabled(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *Push) PayloadKey() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func PushStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func PushAddEnabled(builder *flatbuffers.Builder, enabled bool) {
	builder.PrependBoolSlot(0, enabled, false)
}
func PushAddPayloadKey(builder *flatbuffers.Builder, payloadKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(payloadKey), 0)
}
func PushEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
