// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Spring struct {
	_tab flatbuffers.Table
}

func GetRootAsSpring(buf []byte, offset flatbuffers.UOffsetT) *Spring {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Spring{}
	x.Init(buf, n+offset)
	return x
}

func FinishSpringBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSpring(buf []byte, offset flatbuffers.UOffsetT) *Spring {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Spring{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSpringBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Spring) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Spring) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Spring) Stiffness() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Spring) MutateStiffness(n float64) bool {
	return rcv._tab.MutateFloat64Slot(4, n)
}

func (rcv *Spring) Damping() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Spring) MutateDamping(n float64) bool {
	return rcv._tab.MutateFloat64Slot(6, n)
}

func (rcv *Spring) Mass() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Spring) MutateMass(n float64) bool {
	return rcv._tab.MutateFloat64Slot(8, n)
}

func SpringStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func SpringAddStiffness(builder *flatbuffers.Builder, stiffness float64) {
	builder.PrependFloat64Slot(0, stiffness, 0.0)
}
func SpringAddDamping(builder *flatbuffers.Builder, damping float64) {
	builder.PrependFloat64Slot(1, damping, 0.0)
}
func SpringAddMass(builder *flatbuffers.Builder, mass float64) {
	builder.PrependFloat64Slot(2, mass, 0.0)
}
func SpringEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
